### ISSUE TITLE
[SPIR-V] vk::ext_literal results in compilation error when added for execution scope parameters

### ISSUE THREAD

**Issue by kpentaris** [microsoft/DirectXShaderCompiler#5783] opened 2023-09-26 08:28 UTC
**Description**
Adding `[[vk::ext_literal]]` on a function parameter that represents a SPIR-V operation's execution scope results in compilation error
`fatal error: generated SPIR-V is invalid: <OpName>: expected scope to be a 32-bit int`

**Steps to Reproduce**
Here is a link that reproduces the issue using trunk version of DXC https://godbolt.org/z/3cvKa38zz

In general, a function such as 
```
template<typename T>
[[vk::ext_instruction(/* OpGroupNonUniformShuffle */ 345)]]
T groupShuffle([[vk::ext_literal]] uint executionScope, T value, uint invocationId);
```
fails to compile. Removing the `[[vk::ext_literal]]` fixes the issue but point of it is to tag parameters that should be provided literally as is.

**Actual Behavior**
Per my understanding of how SPIR-V intrinsics work, parameters that are supposed to take literal values directly should be annotated with `[[vk::ext_literal]]`.

**Environment**
- DXC version trunk
- Host Operating System Windows 10 22H2 and whatever godbolt is using

**Comment by s-perron** [comment] 2023-09-26 17:03
You do not want to use `[[vk::ext_literal]]` in this case. The means of `[[vk::ext_literal]]` is that the instruction takes a literal for the parameter. However, the docs for [OpGroupNonUniformShuffle](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpGroupNonUniformShuffle), the scope as [Scope <id>](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Scope_-id-), which is an id and not a literal.

Here is an example where you want to use the attribute: https://godbolt.org/z/KTTveEdf7.

Note that in last operands of the vector shuffle are not the result of an OpConsant, but then ecode the actual literals.

Closing because this is working as designed based on these two cases.

**Closed by s-perron** 2023-09-26 17:03 UTC
Labels: bug, spirv, needs-triage
