### ISSUE TITLE
[SPIR-V] The vk::image_format attribute no longer works (even on the dedicated DXC tests)

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#4334] opened 2022-03-17 11:07 UTC
### Title
[SPIR-V] The `vk::image_format` attribute no longer works (even on the dedicated DXC tests)

### Functional impact
Can't specify SPIR-V resource [image formats](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#vulkan-specific-image-formats). The PR which initially added this feature describes the use cases in more detail https://github.com/microsoft/DirectXShaderCompiler/pull/3395.

### Minimal repro steps
1. Download the (as of this moment) latest DXC release [v1.6.2112](https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.6.2112) (from Dec 09 2021)
2. Compile [vk.attribute.image-format.hlsl.txt](https://github.com/microsoft/DirectXShaderCompiler/files/8283851/vk.attribute.image-format.hlsl.txt) with `dxc.exe -E main -T cs_6_0  -spirv vk.attribute.image-format.hlsl.txt`

### Expected result
The compiled shader should contain the instructions corresponding to the following `OpTypeImage` instruction check comments in the test shader:
```
//CHECK: OpTypeImage %float Buffer 2 0 0 2 Rgba16f
//CHECK: OpTypeImage %float Buffer 2 0 0 2 R32f
//CHECK: OpTypeImage %float Buffer 2 0 0 2 Rgba8Snorm
//CHECK: OpTypeImage %float Buffer 2 0 0 2 Rg16f
//CHECK: OpTypeImage %float Buffer 2 0 0 2 R11fG11fB10f
//CHECK: OpTypeImage %float Buffer 2 0 0 2 Rgb10A2
//CHECK: OpTypeImage %float Buffer 2 0 0 2 Rg8
//CHECK: OpTypeImage %float Buffer 2 0 0 2 R8
//CHECK: OpTypeImage %float Buffer 2 0 0 2 Rg16Snorm
//CHECK: OpTypeImage %float Buffer 2 0 0 2 Rgba32i
//CHECK: OpTypeImage %float Buffer 2 0 0 2 Rg8i
//CHECK: OpTypeImage %float Buffer 2 0 0 2 Rgba16ui
//CHECK: OpTypeImage %float Buffer 2 0 0 2 Rgb10a2ui
```

### Actual result
The compiled shader only contains the following OpTypeImage instructions:
```
%type_buffer_image = OpTypeImage %float Buffer 2 0 0 2 Rgba16f
%type_buffer_image_0 = OpTypeImage %float Buffer 2 0 0 2 R32
```

### Further technical details
* The repro shader is a test from the DXC repo located at `tools/clang/test/CodeGenSPIRV/vk.attribute.image-format.hlsl` (I appended the name with `.txt` to allow upload to github). The other `vk.attribute.image-format*` test files also seem to fail similarly.
* Can only speculate, but as the failure is in a DXC test, the test is probably not being actively run when doing PRs (or is not run for the SPIR-V backend)
* The newer version of DXC from [shader playground](https://shader-playground.timjones.io/cc2bc8190c14f8a3169778060853f3fc) 
(which is `Updated from trunk on 2022-02-05` )  now only has a `Rgba32` instruction for the initially provided example i.e. only:
`%type_buffer_image = OpTypeImage %float Buffer 2 0 0 2 Rgba32f` is present. So it seems the `vk::image_format` attribute is now completely ignored.

**Comment by kuhar** [comment] 2022-03-17 14:18
Thanks for reporting, @Dredhog.
@jaebaek or @sudonatalie, could you take a look?

**Comment by sudonatalie** [comment] 2022-03-17 15:01
These tests are currently passing at tip-of-tree. Tests are run without optimizations by default, so we can easily apply CHECKs on unused variables without them being removed. The 2 that are included in the above results are the 2 that are left after regular optimization since they're used in the entry point function.

Closing as this appears to be working as intended, but feel free to comment/reopen if I've missed something.

**Closed by sudonatalie** 2022-03-17 15:01 UTC
Labels: spirv

**Comment by Dredhog** [comment] 2022-03-17 16:06
@sudonatalie Thank you for the quick response.

It definitely [doesn't work on shader playground](https://shader-playground.timjones.io/610ef3fdd63734ea947e2565fecb33f9) - I made all the buffers from the test be used and DXC only generates a single `Rgba32f` OpImageType (it reports updating DXC from trunk on `2022 02 05` but there could be a bug in shader playground...)

The latest release indeed seems to work correctly, so your explanation relating to optimization makes sense.

Could there be a possibility that the optimized build has regressed after the latest official DXC release? this would explain why the tests would pass at the tip of the repo (due to optimizations being off during tests) but would also explain why it fails on shader playground.

Could you verify this if you haven't already? I won't be able to build the latest DXC very quickly to check myself.
