### ISSUE TITLE
Uniforms in parameter list of entry point

### ISSUE THREAD

**Issue by LukasBanana** [microsoft/DirectXShaderCompiler#2197] opened 2019-05-20 14:39 UTC
I'm not sure whether this is a bug in DXC or the default constant buffer `$Param` is no longer supported.
But the following code sample compiles fine with FXC but fails with DXC because a semantic is missing:
```hlsl
float4 PSMain(uniform float4 FooBar) : SV_Target {
    return FooBar;
}
```

Here is the code sample at [shader-playground.timhones.io](http://shader-playground.timjones.io/):
[FXC Output](http://shader-playground.timjones.io/b444070fe58277a0837f659e5ebe9a48)
[DXC Output](http://shader-playground.timjones.io/19cd5d771ec948364c761118104bc8f1)

**Comment by MrTrillian** [comment] 2019-05-21 15:12
Thanks for reporting! From a quick scan of the code, "uniform" is a legacy keyword which DXC only supports the syntax of, probably so that you can decorate global variables where it's the default anyways. It's more likely that we'll drop the feature than implement full support for it so the best route is to migrate to the newer constant buffer syntax. I will flag this as a bug because we should either properly support the keyword or not have it.

**Comment by LukasBanana** [comment] 2019-05-21 17:14
> I will flag this as a bug because we should either properly support the keyword or not have it.

I agree on that. Thanks for the feedback.

**Comment by tex3d** [comment] 2020-04-24 01:42
I just want to note a few things here:
The new compiler does not support uniform parameters in the entry function, but it supports the syntax to support the intellisense case, and it's fine to have uniform on arguments of a function that is called, but not an entry function.
I merged an update to the Rewriter that should help with porting code that uses this pattern to work with the new compiler in this PR: #2730.

**Comment by pow2clk** [comment] 2020-07-17 21:56
In triage we determined this was working as intended. Won't Fix.

**Closed by pow2clk** 2020-07-17 21:56 UTC
Labels: bug
