### ISSUE TITLE
Do not strip IsNan ops even when no precise metadata is present

### ISSUE THREAD

**Issue by ThomasRaoux** [microsoft/DirectXShaderCompiler#1426] opened 2018-07-16 16:43 UTC
When running D3D12 conf test UnaryFloatOpTest#IsNaN the following DXIL is generated:
%IsNaN = call i1 @dx.op.isSpecialFloat.f32(i32 8, float %3)

Since the precise metadata is not present Intel compiler interprets it as a fast math instruction which gets optimized away to false since fast math assumes no Nan. 

What is the expected behavior? Does IsNan implie "precise" or is it is test issue and the test should have the "precise" mode?

**Comment by hekota** [comment] 2018-11-12 23:36
Yes, that is the expected behavior. Fast math assumes no NaN.

**Comment by TRhomas** [comment] 2018-11-13 01:27
Can the conformance test be fixed then? We currently have a WA because the conformance test doesn't have the precise metadata flag n this instruction but still expects the Nan to be detected correctly.

**Comment by hekota** [comment] 2018-11-16 01:30
Thomas - we reevaluated this and decided to change the behavior to not strip away explicit FP-special ops, even when there are no precise metadata present. I hope this works for you. Changing the title.

**Comment by TRhomas** [comment] 2018-11-16 01:47
Ok sounds good

**Comment by hekota** [comment] 2018-11-16 01:49
Actually let's leave this issue open until we commit the change. Thanks :)

**Comment by llvm-beanz** [comment] 2023-03-06 21:07
This should have been long resolved. Closing as such.

**Closed by llvm-beanz** 2023-03-06 21:07 UTC
Labels: question
