### ISSUE TITLE
Restore support for void in parameter list

### ISSUE THREAD

**Issue by mlrdevgit** [Microsoft/DirectXShaderCompiler#1152] opened 2018-03-19 17:19 UTC
There's an explicit check to remove this from the language, but it appears to be impacting some back compat cases.

So, `[numthreads(1,1,1)] void main(void) {}` should compile fine.

**Comment by hekota** [comment] 2018-03-26 21:52
Duplicate of #1064

**Closed by hekota** 2018-03-26 21:52 UTC
