### ISSUE TITLE
Macro Concatenation

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2338] opened 2019-07-15 08:12 UTC
I declare constant buffers using following macros:
```
#define SBI_VIEWPORT   5
#define BUFFER_I(name, index) cbuffer name : register(b##index) {       // declare a constant buffer with custom buffer index
BUFFER_I(Viewport, SBI_VIEWPORT)
```
I get an error:

> C:\Esenthel\Engine\Source\Shaders/!Header.h:291:1: error: register number should be an integral numeric string
> BUFFER_I(Viewport, SBI_VIEWPORT)
> ^
> C:\Esenthel\Engine\Source\Shaders/!Header.h:157:58: note: expanded from macro 'BUFFER_I'
>    #define BUFFER_I(name, index) cbuffer name : register(b##index) {     // declare a constant buffer with custom buffer index
>                                                          ^
> <scratch space>:2:1: note: expanded from here
> bSBI_VIEWPORT

This code works fine on D3DCompile / FXC and even Nvidia CG

The macro concatenation "b##index" should return b5 not bSBI_VIEWPORT

**Comment by MrTrillian** [comment] 2019-07-15 15:30
Did you try `-flegacy-macro-expansion`? If it doesn't help, then this may be a duplicate of #2158, where a workaround is suggested. FYI @tex3d

**Comment by GregSlazinski** [comment] 2019-07-17 15:38
Thanks, I was able to workaround it using an extra macro:
#define CONCAT(a,b) a##b
Would be cool if it worked out of the box without any compiler switches or extra macros though.

**Comment by MrTrillian** [comment] 2019-07-17 16:13
Glad it helped! There's always a tension between working out of the box for people coming from FXC and and working out of the box for new developers used to C++'s semantics.

**Closed by MrTrillian** 2019-07-17 16:13 UTC
Labels: bug
