### ISSUE TITLE
Add support for device buffer address extension

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/DirectXShaderCompiler#2819] opened 2020-04-08 19:22 UTC
This is going to be a pretty big/interesting ask, but I'll ask it anyway. Now that VK_EXT_buffer_device_address is out and expected to have wide support in drivers, I'd love for some HLSL extensions to be able to use this in Vulkan.

Or alternatively, and I've had discussions about this with several within Microsoft as well, actual pointer support in HLSL or at least something to the effect of buffer_device_address capabilities.

**Comment by simondeschenes** [comment] 2020-11-11 21:20
Being able to use buffer references would be really useful for some of our more complex algorithms.

**Comment by Jasper-Bekkers** [comment] 2021-11-18 21:17
#4069 may offer some solace for people landing on this issue.

**Comment by sudonatalie** [comment] 2023-08-09 16:33
A proposal that would provide this support is currently Under Consideration: [Buffer Pointers in HLSL With vk::BufferPointer](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0010-vk-buffer-ref.md)

**Comment by s-perron** [comment] 2024-07-26 15:19
Closing as a duplicate of https://github.com/microsoft/DirectXShaderCompiler/issues/6489. The `vk::BufferPointer` class will be the mechanism to use device buffer addresses.

**Comment by kanerogers** [comment] 2024-10-02 23:32
> Closing as a duplicate of #6489. The `vk::BufferPointer` class will be the mechanism to use device buffer addresses.

FYI, this issue is still open. 😄

**Closed** 2024-10-02 23:40 UTC
