### ISSUE TITLE
Hull shader has issues with Dead Code Ellimination

### ISSUE THREAD

**Issue by sd20134** [microsoft/DirectXShaderCompiler#6956] opened 2024-10-11 10:30 UTC
**Description**
We have a hull shader which takes a lot of time.
One coworker discovered that this was due to static and global variable initalizations.
This happens only for Hull Shader which is empty. Same issue does not happen on a vertex or pixel shader.
Where in the compiler codebase is the DCE passes and what may be the reason so we can track this out.

**Environment**
- DXC later than 2021
- Host Operating System Windows 11

**Comment by damyanp** [comment] 2024-10-15 17:16
We need more information (such as a repro, and clear details on what the issue is) in order to be able to start thinking about investigating this. Marking this as closed for now, please do reopen if you are able to provide more information.

**Comment by sd20134** [comment] 2024-10-16 06:55
@damyanp  i have no rights to reopen the issue

**Comment by damyanp** [comment] 2024-10-16 17:10
Guidance I have here is that this is likely due to hull shaders having two entry points and so confusing the code that tries to inlines these initializations into a single entry point. A fix for this would likely be involved (and isn't something that we'd be able to invest in for DXC).

This might be a place to start looking: https://github.com/microsoft/DirectXShaderCompiler/blob/main/lib/Transforms/Scalar/ScalarReplAggregatesHLSL.cpp

**Closed by damyanp** 2024-10-16 17:10 UTC
Labels: bug, needs-triage
