### ISSUE TITLE
[SPIR-V] fatal error: generated SPIR-V is invalid: GLSL.std.450 FindUMsb: expected all operands to have the same bit width as Result

### ISSUE THREAD

**Issue by jayfoad** [microsoft/DirectXShaderCompiler#5379] opened 2023-06-30 14:36 UTC
With a `dxc` that I have just built from the `main` branch I get:
```
$ cat z.hlsl 
[numthreads(1, 1, 1)]
void entrypoint()
{
  uint64_t a = 0;
  a = firstbithigh(a);
}
```
```
$ build/bin/dxc -fspv-target-env=vulkan1.1 -spirv -E entrypoint -T cs_6_2 -Od z.hlsl
fatal error: generated SPIR-V is invalid: GLSL.std.450 FindUMsb: expected all operands to have the same bit width as Result Type
  %15 = OpExtInst %uint %1 FindUMsb %13
```

**Comment by s-perron** [comment] 2023-06-30 15:06
Duplicate of https://github.com/microsoft/DirectXShaderCompiler/issues/4702.

**Closed by s-perron** 2023-06-30 15:06 UTC
Labels: bug, spirv, needs-triage
