### ISSUE TITLE
Crash on for loop without loop terminator condition

### ISSUE THREAD

**Issue by ohlenbg** [microsoft/DirectXShaderCompiler#3528] opened 2021-03-01 12:13 UTC
Without adding a loop terminator condition - one that is never hit the - the attached shader causes a hang or a crash.
[loop_crash.txt](https://github.com/microsoft/DirectXShaderCompiler/files/6061487/loop_crash.txt)

**Comment by pow2clk** [comment] 2021-11-18 21:20
For convenience, I'm copying the shader code here

``` hlsl 
// By default, this shader causes a driver hang.  Both of the loops obviously have a maximum number 
// of iterations they could be able to run.
// This occurs while using the October 2020 DirectXShaderCompiler (as well as on earlier versions) 
// and latest NVIDIA drivers (as well as on earlier versions).
// A workaround we discovered was to add a loop terminator condition - one that is never actually hit.
// The addition of this if check causes the shader to run without issue.
// We have observed similar behavior in non-compute shaders as well.
//#define APPLY_LOOP_WORKAROUND

#define MAX_NUMBER_ELEMENT 64 

cbuffer RootConstants : register(b0)
{
	uint  toggle;
	uint2 dimension;
}

Texture2D<float4>   g_buffers[4] : register(t0);

RWTexture2D<float4>  g_composite : register(u0);
RWBuffer<uint4> g_VRAMBuffer : register(u1);
RWBuffer<uint> g_counter : register(u2);

void Sort(uint length)
{
	uint iterCount = 0;
	
	// Note: allow_uav_condition has no effect on whether this crashes or not
	[allow_uav_condition]
	for (uint i = 0; i < length - 1; i++)
	{
#if defined(APPLY_LOOP_WORKAROUND)
		if (iterCount >= MAX_NUMBER_ELEMENT)
			break;
		iterCount++;
#endif
		
		uint4 dummy0 = g_VRAMBuffer[i];
		uint4 dummy1 = g_VRAMBuffer[i + 1];

		float key0 = dummy0.x + dummy0.w;
		float key1 = dummy1.y + dummy1.z;

		if (key0 > key1)
		{
			g_VRAMBuffer[i + 1] = dummy0;
			g_VRAMBuffer[i] = dummy1;
		}
	}
}

[numthreads(16, 16, 1)]
void CSMain(uint2 coord : SV_DispatchThreadID)
{
	// Out of bound.
	if (coord.x >= dimension.x ||
		coord.y >= dimension.y)
	{
		return;
	}

	uint indexElement = 0;
	for (uint i = 0; i < MAX_NUMBER_ELEMENT; ++i)
	{
		float4 data = g_buffers[i % 4].Load(int3(coord, 0)); // Add some buffer reading so it's non-deterministic.
		float res = data.x + data.y + data.z + data.w;
		if (res > 0.5f)
		{
			g_VRAMBuffer[indexElement] = data;
			indexElement++;
		}
	}
	Sort(indexElement);

	float4 final = float4(0.0f, 0.0f, 0.0f, 0.0f);
	if (indexElement > 0)
		final = g_VRAMBuffer[indexElement - 1];

	g_composite[coord] = float4(final);
}
```

**Comment by adam-yang** [comment] 2022-03-30 20:32
Hi @ohlenbg, the output DXIL doesn't look obviously wrong to me. For the loop in `Sort`, could you try changing the condition from:
```
for (uint i = 0; i < length - 1; i++)
```

to

```
for (uint i = 0; i+1 < length; i++)
```

I suspect the hang might be caused by length being 0.

**Comment by damyanp** [comment] 2024-04-17 16:43
As this is many years old, closing this issue as we don't have resources at the moment to investigate further. Please let us know if this is still an ongoing issue for you with more recent DXCs.

**Comment by pow2clk** [comment] 2024-04-17 16:44
Seems to compile fine with the latest in godbolt: https://godbolt.org/z/cKxGMq7TG

**Closed by damyanp** 2024-04-17 16:43 UTC
Labels: needs-triage
