### ISSUE TITLE
[SPIR-V] compiler crash

### ISSUE THREAD

**Issue by apayen** [microsoft/DirectXShaderCompiler#3313] opened 2020-12-12 10:29 UTC
Hello there,

If I declare
`[[vk::binding(3, 0)]] ByteAddressBuffer geometries[256];`
And then does this (first line of the entry point)
`ByteAddressBuffer geometry = geometries[InstanceID()];`
dxcompiler crashes.

The intent here is simply to use `geometry` as an alias. If I use directly `geometries[InstanceID()].Load4()` instead of `geometry.Load4()` it doesn't crash. Is it a bug or is it not allowed to do this?

**Comment by ehsannas** [comment] 2020-12-16 03:06
Thanks for reporting @apayen

**Comment by sudonatalie** [comment] 2022-03-16 20:57
I'm unable to repro a crash, but whether this snippet might cause errors (and the reason for those errors) depends on the shader model kind, extensions provided, and target vulkan environment. Some of those combinations are valid, and some are not. Given the age of this issue (sorry for the slow response!) and that compilation succeeds for me with a simple ray tracing shader, I'm going to close this issue, but feel free to reopen with a specific minimal repro example and command line arguments used.

**Closed by sudonatalie** 2022-03-16 20:57 UTC
Labels: spirv

**Comment by acmarrs-nvidia** [comment] 2022-09-14 22:12
Can we reopen this one? I am able to repro this issue when compiling a ray tracing closest hit shader. Perhaps I'm hitting one of the invalid combinations, but I hope not since the combination I have should be valid. 

Compiling HLSL to SPIRV declaring SM6.6 and Vulkan 1.2 (`-fspv-target-env=vulkan1.2` and `lib_6_6`).

```
[[vk::binding(13, 0)]] ByteAddressBuffer ByteAddrBuffer[] : register(t7, space3);

ByteAddressBuffer GetIndexBuffer(uint meshIndex)
{
    return ByteAddrBuffer[3 + (meshIndex * 2)];
}

uint3 LoadIndices(uint meshIndex, uint primitiveIndex)
{
    uint address = (primitiveIndex * 3) * 4;
    return ByteAddrBuffer[3 + (meshIndex * 2)].Load3(address);  // compiles, works
    //return GetIndexBuffer(meshIndex).Load3(address);          // crashes DXC
}

uint3 indices = LoadIndices(InstanceID(), PrimitiveIndex());
// do things with triangle indices...
```

**Comment by acmarrs-nvidia** [comment] 2022-09-14 22:43
Actually, false alarm. Moving to a newer version of DXC fixes the issue and I can confirm that this in fact does work as expected 🎉
