### ISSUE TITLE
SPIRV: HLSL's SamplerComparisonState does not work properly since Texture2D is not defined correctly

### ISSUE THREAD

**Issue by Cry-Mory** [Microsoft/DirectXShaderCompiler#1190] opened 2018-03-31 12:03 UTC
We have a shader which generates the shadow mask ([ShadowMaskGen@DeferredShadowPS_DeferredShadowPS.hlsl.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1864903/ShadowMaskGen.DeferredShadowPS_DeferredShadowPS.hlsl.txt)). In this shader, we use a depth texture and a comparison sampler state.

```
Texture2D shadowDepthTex:register(t0, space0);
SamplerComparisonState ssShadowComparison:register(s7, space0);
```

The code generated for texture and sampler definitions are as follows (Full generated SPIR-V code can be found in [ShadowMaskGen@DeferredShadowPS_DeferredShadowPS.h_spirv.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1865444/ShadowMaskGen.DeferredShadowPS_DeferredShadowPS.h_spirv.txt)): 

```
%type_2d_image = OpTypeImage %float 2D 0 0 0 1 Unknown
%type_sampler = OpTypeSampler
%_ptr_UniformConstant_type_2d_image = OpTypePointer UniformConstant %type_2d_image
%_ptr_UniformConstant_type_sampler = OpTypePointer UniformConstant %type_sampler
%shadowDepthTex = OpVariable %_ptr_UniformConstant_type_2d_image UniformConstant
%ssShadowComparison = OpVariable %_ptr_UniformConstant_type_sampler UniformConstant
```

The shader code samples the shadowDepthTex and compares it to another depth value by calling **SampleCmpLevelZero** as follows:

```
float fInShadow=shadowDepthTex.SampleCmpLevelZero(ssShadowComparison,P0.xy,P0.z);
```

which maps to the following SPIR-V code:

```
        %101 = OpLoad %type_2d_image %shadowDepthTex
        %105 = OpLoad %type_sampler %ssShadowComparison
        %106 = OpLoad %v4float %P0
        %107 = OpVectorShuffle %v2float %106 %106 0 1
        %108 = OpAccessChain %_ptr_Function_float %P0 %int_2
        %109 = OpLoad %float %108
        %111 = OpSampledImage %type_sampled_image %101 %105
        %113 = OpImageSampleDrefExplicitLod %float %111 %107 %109 Lod %float_0
               OpStore %fInShadow %113
```

The problem is shader is not doing what it intends to do. My investigations show that _**shadowDepthTex.SampleCmpLevelZero**_ does not work correctly. By looking at the shader code in SPIR-V, I find out the 2d image is not defined as a depth image and that is causing this issue. The first 0 in the following definition specifies that the 2d image is non-depth although it is:

```
%type_2d_image = OpTypeImage %float 2D 0 0 0 1 Unknown
```

In addition, I used **_glslang_** to compile the shader and it translates the 2d image definition as follows:

```
108:             TypeImage 6(float) 2D depth sampled format:Unknown
```

Full **_glslang_** generated spirv can be found in [shadowmask.h_spv.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/1865442/shadowmask.h_spv.txt).

**Comment by antiagainst** [comment] 2018-03-31 12:52
Hi @Cry-Mory, thanks for reporting this issue and sorry about the troubles. I think this issue is a duplicate of #1107 and we have discussions over there. I'll close this one.

**Closed by antiagainst** 2018-03-31 12:52 UTC
