### ISSUE TITLE
DXC produces invalid DXIL on dot using argument with double type.

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#6566] opened 2024-04-24 19:17 UTC
**Description**
dot(a, b) will generate invalid DXIL when a and b are vectors of double.
The hlsl intrinsic allows double vector while the dxil op for dot not support double.
**Steps to Reproduce**

dxc -Tps_6_0

double2 a;
double2 b;

float main() : SV_Target {
  return dot(a, b);
}

**Actual Behavior**

DXC generated DXIL that failed validation.
**Environment**
- DXC version : 1.8
- Host Operating System : Windows

**Comment by tex3d** [comment] 2024-04-24 22:31
To be clear, the crash is a temporary regression in the main branch and original 1.8 release that was fixed in point release.  The prior behavior, the current behavior of latest 1.8 releases, and the behavior for main once #6543 merges, will be to produce a validation error due to an illegal DXIL op overload instead.

**Closed** 2024-04-25 17:18 UTC
Labels: bug
