### ISSUE TITLE
"error: reference to 'i' is ambiguous" where loop scoped variable should take priority. Other compilers have no issues

### ISSUE THREAD

**Issue by Dredhog** [microsoft/DirectXShaderCompiler#3132] opened 2020-09-15 11:30 UTC
### Title
Receive `error: reference to 'i' is ambiguous` where loop scoped variable `int i` should take priority. This issue is not present for `FXC`, `glslang` or `C++` compilers

### Functional impact
Failed compilation. Shaders with such shadowing occurrences are not forwards compatible with FXC.

### Minimal repro steps

1. Compile the following pixel shader with `dxc.exe -T ps_6_0 -E PSMain repro_shader.hlsl`
```
struct v2f {
    float4 vertex : SV_POSITION;
    float2 uv : TEXCOORD0;
};

float2 PSMain (v2f i) : SV_Target
{    
    const int array_length = 3;
    const float2 arr[array_length] = {float2(1,1), float2(2,2), float2(3,3)};
    
    float2 acc = float3(i.uv, 0);
    for(int i = 0; i < array_length; i++)
        acc += arr[i];

 	return acc;
}
```
Observe console message:
```
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:11:12: warning: implicit truncation of vector type [-Wconversion]
    float2 acc = float3(i.uv, 0);
           ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:12:13: warning: redefinition of 'i' with a different type: 'int' vs 'v2f' shadows declaration in the outer scope; most recent declaration will be used
    for(int i = 0; i < array_length; i++)
            ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:6:20: note: previous definition is here
float2 PSMain (v2f i) : SV_Target
                   ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:12:20: error: reference to 'i' is ambiguous
    for(int i = 0; i < array_length; i++)
                   ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:12:13: note: candidate found by name lookup is 'i'
    for(int i = 0; i < array_length; i++)
            ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:6:20: note: candidate found by name lookup is 'i'
float2 PSMain (v2f i) : SV_Target
                   ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:12:38: error: reference to 'i' is ambiguous
    for(int i = 0; i < array_length; i++)
                                     ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:12:13: note: candidate found by name lookup is 'i'
    for(int i = 0; i < array_length; i++)
            ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:6:20: note: candidate found by name lookup is 'i'
float2 PSMain (v2f i) : SV_Target
                   ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:13:20: error: reference to 'i' is ambiguous
        acc += arr[i];
                   ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:12:13: note: candidate found by name lookup is 'i'
    for(int i = 0; i < array_length; i++)
            ^
D:\local\Temp\0ea1cf03-17c6-4cb2-917b-3c1fd1a36e5a.hlsl:6:20: note: candidate found by name lookup is 'i'
float2 PSMain (v2f i) : SV_Target
```
### Expected result
Shader compiles successfully by using the integer loop variable `int i` as it shadows `v2f i` in the local scope of the `for` loop

### Actual result
Compilation fails with errors:
```
 reference to 'i' is ambiguous
    for(int i = 0; i < array_length; i++)
                   ^
```
and
```
 reference to 'i' is ambiguous
        acc += arr[i];
                   ^
```

### Further technical details
Example of the same shader source compiling successfully with `glslang`: http://shader-playground.timjones.io/e027184aebe3261412454d05d747f0aa and `C++` clang https://godbolt.org/z/xbaKWx

**Comment by pow2clk** [comment] 2020-09-25 11:58
The scope of iterator variables in HLSL is unusual. The scope of `int i` would not be the local loop scope, but would be accessible following the loop as well. Discrepancies with c++ are expected. The glslang hlsl frontend is an attempt to match the behavior of dxc. So discrepancies there are usually bugs in glslang.

The difference with fxc is not expected. We try to match that behavior as much as possible. So we'll look into it.

That said, given the peculiar scoping of loop variables in HLSL, this shader is going to be ambiguous even if it manages to compile.

**Comment by pow2clk** [comment] 2020-10-05 23:54
We have a longstanding intention of fixing the scoping weirdness as documented here. #584 So we're going to consider this a duplicate of that.

**Closed by pow2clk** 2020-10-05 23:54 UTC
