### ISSUE TITLE
[SPIRV] RwByteAddressBuffer::InterlockedMin does not work for signed-integer

### ISSUE THREAD

**Issue by lifeisforu** [microsoft/DirectXShaderCompiler#4189] opened 2022-01-17 02:07 UTC
I wrote code like below:
```
RWByteAddressBuffer gBuffer;
void someFunction()
{
    int signedValue = XXX;
    uint offset = YYY;
    gBuffer.InterlockedMin(offset, signedValue);
}
```
But SPIR-V validation error occurs like below : 
`fatal error: generated SPIR-V is invalid: AtomicSMin: expected Value to be of type Result Type %348 = OpAtomicSMin %uint %346 %uint_1 %uint_0 %347`

How can I solve this problem?

Thank you. 

@jaebaek

**Comment by jaebaek** [comment] 2022-01-17 14:50
@lifeisforu Thank you for reporting this issue. Could you please provide us with the compile options you used?

**Comment by lifeisforu** [comment] 2022-01-18 01:19
@jaebaek Thank you for your reply. My option is below:
`-all-resources-bound -WX -Wno-ambig-lit-shift -auto-binding-space 0 -spirv -fspv-target-env=vulkan1.2 -fvk-use-dx-layout -fvk-use-dx-position-w`

**Comment by sudonatalie** [comment] 2024-05-09 20:54
Closing as duplicate of #3196

**Closed by sudonatalie** 2024-05-09 20:54 UTC
Labels: spirv
