### ISSUE TITLE
[SPIR-V] DXC crashes when sampling float1 texture

### ISSUE THREAD

**Issue by shobomaru** [microsoft/DirectXShaderCompiler#6782] opened 2024-07-14 12:40 UTC
**Description**
LLVM assertion failed.

**Steps to Reproduce**
`dxc -T ps_6_0 -spirv path/to/file.hlsl`

HLSL code:

```
Texture2D<float1> Texture;
SamplerState Sampler;

float4 main() : SV_Target
{
	float bar = Texture.Sample(Sampler, (float2)0);
	return bar.xxxx;
}
```

If change the code in one of the following ways, the issue is not occurred.

- `Texture2D<float1>` to `Texture2D<float>`
- use Load() instead of Sample()

**Actual Behavior**
> Assertion failed: (vecType->isBuiltinType() || vecType->isDependentType()), function getExtVectorType, file ASTContext.cpp, line 2941.

**Environment**
- DXC version: libdxcompiler.dylib: 1.8(dev;4661-a54abe84)
- Host Operating System: Windows 11 23H2 and macOS 14.5

**Comment by damyanp** [comment] 2024-07-16 17:11
@s-perron - is this something you want to have a look at?  I'm not sure if it is spirv specific or not.

**Comment by s-perron** [comment] 2024-07-29 19:48
This was a duplicate of https://github.com/microsoft/DirectXShaderCompiler/issues/6568, and it is already fixed.

**Closed by s-perron** 2024-07-29 19:48 UTC
Labels: bug, spirv
