### ISSUE TITLE
[SPIRV] Invalid Image Operand for OpImageSampleImplicitLod

### ISSUE THREAD

**Issue by mmostajab** [Microsoft/DirectXShaderCompiler#1401] opened 2018-07-05 10:00 UTC
I am compiling [AuxTextPS.hlsl.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/2165978/AuxTextPS.hlsl.txt). There is a problem with creating graphics pipeline using the generated SPIRV code on mobile phones. By comparing the DXC resulting shader with _glslangvalidator_ result (which is working fine in this case), I find out that the following line in the SPIRV code is causing this issue:

 %27 = OpImageSampleImplicitLod %v4float %26 %22 **None**

which maps to the following one in glslangvalidator result:

 156:   13(fvec4) ImageSampleImplicitLod 154 86

According to SPIRV documentation, the image operand (**None**) is optional and according to the same documentation, image operand is:

> Additional operands to sampling, or getting texels from, an image. Bits that are set can indicate that another operand follows. If there are multiple following operands indicated, they are ordered: Those indicated by smaller-numbered bits appear first. **At least one bit must be set (None is invalid).**

so the image operand in above SPIRV instruction (%27) must not be "None" since it is an invalid value.

**Comment by Cry-Mory** [comment] 2018-07-05 10:41
Also I have this issue with running this shader on Android.

**Comment by ehsannas** [comment] 2018-07-05 14:18
Thanks for reporting. I'll take this one.

**Comment by ehsannas** [comment] 2018-07-05 14:32
Hi @mmostajab & @Cry-Mory 
Are you using the top of the tree? I believe this issue has already been fixed by [this change](https://github.com/Microsoft/DirectXShaderCompiler/commit/f28b030c748b66b086b2306a6f7e2e81e7a963be).

I am not able to reproduce the issue with the hlsl you have provided. I will close the issue; if you still see the issue on the latest DXC, please reopen.

Thanks

**Closed by ehsannas** 2018-07-05 14:32 UTC
Labels: spirv
