### ISSUE TITLE
[SPIR-V] DXC generates bad SPIR-V for simple geometry shader

### ISSUE THREAD

**Issue by adamnv** [Microsoft/DirectXShaderCompiler#1435] opened 2018-07-18 20:18 UTC
```

#pragma pack_matrix(row_major)

// GS to replicate a quad into 6 cube faces

struct GSInput
{
    float4 position : SV_Position;
    float2 uv : UV;
};

struct GSOutput
{
    float4 position : SV_Position;
    float2 uv : UV;
    uint arrayIndex : SV_RenderTargetArrayIndex;
};

[maxvertexcount(3)]
[instance(6)]
void cubemap_gs(
    triangle GSInput Input[3],
    uint instanceID : SV_GSInstanceID,
    inout TriangleStream<GSOutput> Output)
{
    GSOutput OutputVertex;
    OutputVertex.arrayIndex = instanceID;

    OutputVertex.position = Input[0].position;
    OutputVertex.uv = Input[0].uv;
    Output.Append(OutputVertex);

    OutputVertex.position = Input[1].position;
    OutputVertex.uv = Input[1].uv;
    Output.Append(OutputVertex);

    OutputVertex.position = Input[2].position;
    OutputVertex.uv = Input[2].uv;
    Output.Append(OutputVertex);
}
```

The resulting SPIR-V yields this validation error:
**[Vulkan: location=0 code=5, layerPrefix='Validation'] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: According to the Vulkan spec BuiltIn Position variable needs to be a 4-component 32-bit float vector. ID <2> (OpVariable) is not a float vector.**

Here's the disassembly of the resulting SPIR-V:

```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 33
; Schema: 0
               OpCapability Geometry
               OpMemoryModel Logical GLSL450
               OpEntryPoint Geometry %cubemap_gs "cubemap_gs" %gl_Position %in_var_UV %gl_InvocationID %gl_Position_0 %out_var_UV %gl_Layer
               OpExecutionMode %cubemap_gs OutputVertices 3
               OpExecutionMode %cubemap_gs Invocations 6
               OpExecutionMode %cubemap_gs Triangles
               OpExecutionMode %cubemap_gs OutputTriangleStrip
               OpSource HLSL 600
               OpName %cubemap_gs "cubemap_gs"
               OpName %in_var_UV "in.var.UV"
               OpName %out_var_UV "out.var.UV"
               OpDecorate %gl_Position BuiltIn Position
               OpDecorate %gl_InvocationID BuiltIn InvocationId
               OpDecorate %gl_Position_0 BuiltIn Position
               OpDecorate %gl_Layer BuiltIn Layer
               OpDecorate %in_var_UV Location 0
               OpDecorate %out_var_UV Location 0
      %float = OpTypeFloat 32
       %uint = OpTypeInt 32 0
       %void = OpTypeVoid
         %11 = OpTypeFunction %void
    %v4float = OpTypeVector %float 4
    %v2float = OpTypeVector %float 2
     %uint_3 = OpConstant %uint 3
%_arr_v4float_uint_3 = OpTypeArray %v4float %uint_3
%_ptr_Input__arr_v4float_uint_3 = OpTypePointer Input %_arr_v4float_uint_3
%_arr_v2float_uint_3 = OpTypeArray %v2float %uint_3
%_ptr_Input__arr_v2float_uint_3 = OpTypePointer Input %_arr_v2float_uint_3
%_ptr_Input_uint = OpTypePointer Input %uint
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_ptr_Output_v2float = OpTypePointer Output %v2float
%_ptr_Output_uint = OpTypePointer Output %uint
%gl_Position = OpVariable %_ptr_Input__arr_v4float_uint_3 Input
  %in_var_UV = OpVariable %_ptr_Input__arr_v2float_uint_3 Input
%gl_InvocationID = OpVariable %_ptr_Input_uint Input
%gl_Position_0 = OpVariable %_ptr_Output_v4float Output
 %out_var_UV = OpVariable %_ptr_Output_v2float Output
   %gl_Layer = OpVariable %_ptr_Output_uint Output
 %cubemap_gs = OpFunction %void None %11
         %23 = OpLabel
         %24 = OpLoad %_arr_v4float_uint_3 %gl_Position
         %25 = OpLoad %_arr_v2float_uint_3 %in_var_UV
         %26 = OpCompositeExtract %v4float %24 0
         %27 = OpCompositeExtract %v2float %25 0
         %28 = OpCompositeExtract %v4float %24 1
         %29 = OpCompositeExtract %v2float %25 1
         %30 = OpCompositeExtract %v4float %24 2
         %31 = OpCompositeExtract %v2float %25 2
         %32 = OpLoad %uint %gl_InvocationID
               OpStore %gl_Position_0 %26
               OpStore %out_var_UV %27
               OpStore %gl_Layer %32
               OpEmitVertex
               OpStore %gl_Position_0 %28
               OpStore %out_var_UV %29
               OpStore %gl_Layer %32
               OpEmitVertex
               OpStore %gl_Position_0 %30
               OpStore %out_var_UV %31
               OpStore %gl_Layer %32
               OpEmitVertex
               OpReturn
               OpFunctionEnd

```
The bug occurs with assorted DXC builds up to and including c24c9de9f80f244221e155899801e9d763f6de68 (17th July 2018)

**Comment by ehsannas** [comment] 2018-07-18 20:33
I believe this is a duplicate of #1335 

Please see the discussion #1335 and https://github.com/KhronosGroup/SPIRV-Tools/issues/1598

**Closed by ehsannas** 2018-07-18 20:33 UTC

**Comment by adamnv** [comment] 2018-07-18 20:39
So it's actually a validation error?  Interesting.  Thanks.
