### ISSUE TITLE
Conversion operator is not recognised with empty struct

### ISSUE THREAD

**Issue by KStocky** [microsoft/DirectXShaderCompiler#6063] opened 2023-11-25 15:16 UTC
**Description**
As the title states. using a type's conversion operators fails to compile when the type has no non-static data members (i.e. is empty).

**Steps to Reproduce**
The following is an example of conversion operators working with a type that has a non-static data member
https://shader-playground.timjones.io/d5cf6c6d984a057c29c61f77982fdcdb

The following is an example of the error that is produced if that non-static data member is removed
https://shader-playground.timjones.io/55cca3aae9d403567364f463315b9087

**Actual Behavior**
The error message that I get when I try to use a conversion operator of an empty type is as follows.
error: cannot convert from 'MyStruct' to 'bool'
    bool t = (bool)testStruct;

**Expected Behaviour** 
I would have expected conversion operators to work the same regardless of if the type is empty or not.

**Environment**
- DXC version 1.7.2308.12
- Host Operating System Windows 10 Pro 22H2

**Comment by devshgraphicsprogramming** [comment] 2023-11-29 20:09
waait, wasn't the conversion operator disabled some time ago?

**Comment by KStocky** [comment] 2023-11-29 20:18
They work just fine... in most scenarios... They just don't result in implicit conversions. i.e. you need to explicitly cast to invoke them.

**Comment by devshgraphicsprogramming** [comment] 2023-11-30 09:05
> They work just fine... in most scenarios... They just don't result in implicit conversions. i.e. you need to explicitly cast to invoke them.

aah ok, whats the reason for omitting implicit conversions, was the `explicit` keyword that hard to add?

**Comment by KStocky** [comment] 2023-11-30 12:58
> waait, wasn't the conversion operator disabled some time ago?
> 
> I swear I tried it in one of my unholy Pointer & Reference emulation experiments and couldn't get it to be invoked.


Actually after a little more playing around this morning. You are absolutely correct. Conversion operators compile but they do absolutely nothing. They just try to convert the first member of the object to the type that you are trying to cast to. So when your struct is empty, there is nothing to cast, and so it fails compilation. I made a bug for it here https://github.com/microsoft/DirectXShaderCompiler/issues/6081 since I could not find any other issues that reference this or anyone talking about it elsewhere.

**Comment by devshgraphicsprogramming** [comment] 2023-11-30 15:24
> > waait, wasn't the conversion operator disabled some time ago?
> > I swear I tried it in one of my unholy Pointer & Reference emulation experiments and couldn't get it to be invoked.
> 
> Actually after a little more playing around this morning. You are absolutely correct. Conversion operators compile but they do absolutely nothing. They just try to convert the first member of the object to the type that you are trying to cast to. So when your struct is empty, there is nothing to cast, and so it fails compilation. I made a bug for it here #6081 since I could not find any other issues that reference this or anyone talking about it elsewhere. I also couldn't find a mention in any release notes from here https://github.com/microsoft/DirectXShaderCompiler/releases

I think they got axed (maybe too eagerly) in the commit that removed assignment operators, etc. because there were issues around DXC not having references which makes it impossible to make such operators.

Also the lack of `const` method overloads which follows.

**Comment by KStocky** [comment] 2023-11-30 15:27
Yeah that is fair. But if they got removed I would expect that syntax to simply not compile with a nice error message that says "No conversion operators yet." The announcement also states that they exist https://devblogs.microsoft.com/directx/announcing-hlsl-2021/

**Comment by damyanp** [comment] 2024-10-29 17:20
Duplicate of #5103.

**Closed by damyanp** 2024-10-29 17:20 UTC
Labels: bug, hlsl2021
