### ISSUE TITLE
nointerpolation matrix bug

### ISSUE THREAD

**Issue by scottkircher** [microsoft/DirectXShaderCompiler#2755] opened 2020-03-09 13:43 UTC
We've encountered two separate cases now where a matrix (one was a float3x3 and one was a float4x4) passed from vertex shader to pixel shader via a semantic marked as **nointerpolation** resulted in incorrect results. The vertex shader is calculating the same value for all vertices, and this works fine when the nointerpolation flag is not present. When it is present, however, the matrices in the pixel shader appear to be interpolated with some other garbage value (i.e. correct near some triangle corners and completely wrong near others).

This is happening only with the DXIL back-end (i.e. we do not see this bug in Vulkan using the SPIR-V back-end).

**Comment by pow2clk** [comment] 2020-09-25 15:07
Hi @scottkircher!

Sorry it took us so long to get to this. I'm afraid I'm unable to reproduce the issue with your description. Would it be possible to provide a short repro case to make sure we're on the same page?

**Comment by pow2clk** [comment] 2020-10-02 21:59
If you come up with a shader, please file a new issue. Lacking a response or a repro, I'm closing this.

**Closed by pow2clk** 2020-10-02 21:59 UTC
