### ISSUE TITLE
[SPIR-V] Shader failes to compile when activating debug infos

### ISSUE THREAD

**Issue by Clothoid1** [microsoft/DirectXShaderCompiler#4911] opened 2023-01-04 13:54 UTC
The following reproducer does not compile, leading to the error message:
```
fatal error : generated SPIR-V is invalid: ID '52[%52]' has not been defined
1>  %51 = OpExtInst %void %1 DebugTypeFunction %uint_3 %52 %48 %49
1>
1>note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

Reproducer:
```hlsl
StructuredBuffer<uint16_t> myIntersectionMaskBuffer_BitCompressed : register(t0);

class CompressedIntersectionBits
{
	uint16_t myCompressedData;

	static CompressedIntersectionBits read_const(StructuredBuffer<uint16_t> aIntersectionMaskBuffer_BitCompressed_in, const uint aRayIndex_in)
	{
		CompressedIntersectionBits aCompressedIntersectionBits;
		aCompressedIntersectionBits.myCompressedData = aIntersectionMaskBuffer_BitCompressed_in[aRayIndex_in];
		return aCompressedIntersectionBits;
	}
};

class CompressedIntersectionBits_Test
{
	static CompressedIntersectionBits read_const(StructuredBuffer<uint16_t> aIntersectionMaskBuffer_BitCompressed_in, const uint aRayIndex_in)
	{
		CompressedIntersectionBits aCompressedIntersectionBits;
		aCompressedIntersectionBits.myCompressedData = aIntersectionMaskBuffer_BitCompressed_in[aRayIndex_in];
		return aCompressedIntersectionBits;
	}
};

void runKernel(const uint aIndexX_in, const uint aIndexY_in)
{
	uint aRayIndex = aIndexY_in * 512 + aIndexX_in;

	CompressedIntersectionBits aCompressedIntersectionBits = CompressedIntersectionBits::read_const(myIntersectionMaskBuffer_BitCompressed, aRayIndex);
	//CompressedIntersectionBits aCompressedIntersectionBits = CompressedIntersectionBits_Test::read_const(myIntersectionMaskBuffer_BitCompressed, aRayIndex);
}

[numthreads(8, 8, 1)]
void main(uint3 GlobalInvocationID : SV_DispatchThreadID, uint3 LocalInvocationID : SV_GroupThreadID)
{
	runKernel(GlobalInvocationID[0], GlobalInvocationID[1]);
}
```

Command Line used:
`dxc.exe -spirv -T cs_6_7 -fvk-use-scalar-layout -enable-16bit-types -fspv-target-env=vulkan1.3 -fspv-debug=vulkan-with-source -E main `

dxc version used:
`dxcompiler.dll: 1.7 - 1.7.0.3774 (2168dcb4f)`

Operating System used: 
Windows 10

When removing the option
`-fspv-debug=vulkan-with-source`
the file compiles without a problem.

The issue also vanishes, when calling
```hlsl
CompressedIntersectionBits_Test::read_const(myIntersectionMaskBuffer_BitCompressed, aRayIndex);
```
instead of 
```hlsl
CompressedIntersectionBits::read_const(myIntersectionMaskBuffer_BitCompressed, aRayIndex);
```

**Comment by Keenuts** [comment] 2023-01-05 16:08
Hi! Thanks for complete the report!

Was able to reproduce at head with:
```hlsl
class MyClass
{
	static MyClass my_func()
	{
		MyClass tmp;
		return tmp;
	}
};

[numthreads(1, 1, 1)]
void main(uint3 GlobalInvocationID : SV_DispatchThreadID)
{
  const uint index = GlobalInvocationID[0];
	MyClass::my_func();
}
```

```
./build/bin/dxc -spirv -T cs_6_7 -fspv-debug=vulkan-with-source -E main repro.hlsl
```

The issue seems to be linked to the optimizer, and the compact-ids pass, IDs gets rearranged, and the ID ends up being used before being defined:

```python
10747 %26 = OpExtInst %void %1 DebugLexicalBlock %12 %uint_4 %uint_2 %22
10748 %28 = OpExtInst %void %1 DebugLocalVariable %27 %19 %12 %uint_5 %uint_11 %26 %uint_4
```

```python
10853 %24 = OpExtInst %void %1 DebugTypeFunction %uint_3 %26
[...]
10855 %26 = OpExtInst %void %1 DebugTypeComposite %8 %uint_0 %19 %uint_1 %uint_7 %20 %8 %uint_0 %uint_3 %27
```

**Comment by Keenuts** [comment] 2023-05-22 14:45
Hello! Sorry haven't had much time for DXC.
Seems like this issue is related to https://github.com/KhronosGroup/SPIRV-Tools/issues/5229 but this is not enough to fix it.
Seems like there is also a fix to do in the debug instruction ordering code.

**Comment by Clothoid1** [comment] 2023-07-18 12:34
I just tested this issue with latest DXC compiler.
I can now no longer reproduce this issue.
Instead i only get the warning:
CUSTOMBUILD : warning : Member functions will not be linked to their class in the debug information. See https://github.com/KhronosGroup/SPIRV-Registry/issues/203

Theoretically this issue could now be closed.
Or should it be kept open until also the warning is also solved?

**Comment by Clothoid1** [comment] 2023-07-18 12:40
When activating debug infos now all shaders compile - with the exception of our raytracing shaders.
But it seems to me that this remaining issue was already reported:
#5113

**Comment by Keenuts** [comment] 2023-07-18 12:43
Hello! So yes, thanks, for now, the issue is "resolved" as "it doesn't crash".
We can close this, but we now need to change the SPIR-V spec to solve this long-term.
(This will take longer, as we need to define the spec, and figure out how to propagate it, maybe wait a spirv release?)

For the second issue, seems unrelated to this (as in it's a different error/crash).

**Closed by Keenuts** 2023-07-18 12:43 UTC
Labels: bug, spirv
