### ISSUE TITLE
[SPIR-V] Casting from float to uint16/int16 inserts a cast to float16 in between. 

### ISSUE THREAD

**Issue by forbiddencactus** [microsoft/DirectXShaderCompiler#6535] opened 2024-04-16 00:37 UTC
**Description**
The following HLSL code generates SPIR-V with a cast to float16 in between the float and the uint16 target when compiled in DXC:

```
struct VS_OUTPUT
{ 
    float4 Pos		: SV_Position;
};

PS_OUTPUT ps(VS_OUTPUT inputs)
{
uint16_t2 uv = uint16_t2(inputs.Pos.xy);	
}

```

**Steps to Reproduce**
Compile the following code using DXC and verify the SPIR-V. 

**Actual Behaviour**
Observe the following SPIR-V being generated at the point of the cast:

```
 %18 = OpFConvert %v2half %17
 %19 = OpConvertFToU %v2ushort %18
```

Further details may be found on my first erroneous issue file to SPIR-V Cross:

https://github.com/KhronosGroup/SPIRV-Cross/issues/2307

**Comment by Keenuts** [comment] 2024-04-17 14:55
Hi! Thanks for the issue!
Duplicate of #6501 . PR is in review to fix this.

**Closed by Keenuts** 2024-04-17 14:55 UTC
Labels: bug, spirv, needs-triage

**Comment by Keenuts** [comment] 2024-04-17 15:01
Confirmed the PR will fix this issue, replacing the 2 instructions by a single `OpConvertFToU`.
