### ISSUE TITLE
A new FATAL error in compiling to spirv results when enabling vulkan source level shader debugging

### ISSUE THREAD

**Issue by yuvicii** [microsoft/DirectXShaderCompiler#5243] opened 2023-05-29 11:05 UTC
After the last time I reported a fatal error caused by a member function with vulkan source level shader debugging, I encountered a new fatal error, this time related to the parameters passed in the function

**When I pass an element of array into the function, I get the following fatal error. And when I modify the parameter I passed into a variable, the fatal error disappears**
```
fatal error: generated SPIR-V is invalid: NonSemantic.Shader.DebugInfo.100 DebugDeclare: expected operand Variable must be a result id of OpVariable or OpFunctionParameter
  %954 = OpExtInst %void %2 DebugDeclare %370 %944 %185

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

Here is my code :

```
// the function:
void FFX_DNSR_Reflections_LoadNeighborhood(
    int2 pixel_coordinate,
    out min16radiance4 radiance,
    out min16float variance,
    out min16float3 normal,
    out float depth,
    int2 screen_size)

// the call of the function
for (int i = 0; i < 4; ++i) {
        FFX_DNSR_Reflections_LoadNeighborhood(dispatch_thread_id + offset[i], radiance[i], variance[i], normal[i], depth[i], screen_size);
}

```
When I check my spirv-module like last time, I found the following problem：
in debuginfo.100 spec :
![image](https://github.com/microsoft/DirectXShaderCompiler/assets/130118168/c6c5ad19-4410-49b8-ae31-06eca1c88b58)

but in my spirv-module, I find the variable is OpAccessChain , which may be the reason of this fatal error.
![image](https://github.com/microsoft/DirectXShaderCompiler/assets/130118168/fa6f26d2-848a-4293-8657-a4076cba97f9)

**You can reproduce this fatal error by meeting the following points at the same time**

- in a loop 
- pass array[i]
- the function parameter  with inout/out

like this simple code sample：
```
#pragma vertex VSMain
#pragma pixel PSMain

void test(inout float4 testf){

}

struct VertexIn
{
    float4 posLS : POSITION;
};

struct VertexOut
{
    float4 posHS : SV_POSITION;
};

VertexOut VSMain(VertexIn vin)
{
    VertexOut vout = (VertexOut)0;
    vout.posHS = vin.posLS;
    return vout;
}

float4 PSMain(VertexOut pin) : SV_TARGET
{
    float4 testArray[4];
    for(int i = 0; i < 4; i++){
        test(testArray[i]);
    }
    return float4(1,1,1,1);
}
```

**Comment by yuvicii** [comment] 2023-05-29 12:18
My compiler options: 
`-E PSMain -T ps_6_2  -spirv -fspv-target-env=vulkan1.2 -fspv-extension=SPV_KHR_non_semantic_info -fspv-debug=vulkan-with-source`

**Comment by ncesario-lunarg** [comment] 2023-06-07 15:38
It looks like this is a duplicate of #5191.

**Comment by s-perron** [comment] 2023-06-13 19:19
Closing as a duplicate. It seems like someone from LunarG is working on a fix.

**Closed by s-perron** 2023-06-13 19:19 UTC
Labels: bug, spirv
