### ISSUE TITLE
OpTypeAccelerationStructureKHR store generated in SPIR-V when assigning to struct variable

### ISSUE THREAD

**Issue by carllloyd-eg** [microsoft/DirectXShaderCompiler#5052] opened 2023-02-23 15:07 UTC
We are seeing an issue when using RaytracingAccelerationStructure inside of a struct in HLSL, it generates an OpTypeAccelerationStructureKHR store in the SPIR-V which while fine on most drivers is invalid behavior.

From the Spec:

Invalid SPIR-V. The shaders are generating code that violates the following spec rule: "Objects of types OpTypeImage, OpTypeSampler, OpTypeSampledImage, OpTypeAccelerationStructureKHR, and arrays of these types must not be stored to or modified"

An example use case:

```
struct FRayTracedStruct
{
    RaytracingAccelerationStructure TLAS;
}

float4 SomeFunction(RayTracedStruct RTStruct)
{}

RayTracedStruct RTStruct;

// Invalid behavior for SPIR-V and the generated SPIR-V attempts to assign the TLAS
RTStruct.TLAS = TLAS;
SomeFunction(RTStruct);
```

**Comment by s-perron** [comment] 2023-06-27 18:59
@carllloyd-eg Can you provide sample that can be compiled? I can't tell if the problem is that the optimization passes are not being run or if the optimization passes are not effective.

**Comment by s-perron** [comment] 2023-09-26 19:02
Closing until we get a full test case to reproduce the issue.

**Closed by s-perron** 2023-09-26 19:02 UTC
Labels: bug, spirv
