### ISSUE TITLE
dxc silently crashes for atomic ops involving unsupported types

### ISSUE THREAD

**Issue by vcsharma** [microsoft/DirectXShaderCompiler#2483] opened 2019-09-24 18:11 UTC
The below one fails to compile on FXC with an error message `"cs_5_1 only supports interlocked operations on scalar int or uint data"`, but silently crashes when compiled using DXC.

```
RWBuffer<float> test;
[numthreads(8,8,1)]
void main() {
  InterlockedAdd(test[0],1.f);
}
```

**Comment by pow2clk** [comment] 2020-07-23 03:06
This is actually a dupe of #2077. The cause is exactly the same, we allow a cast to a reference parameter, which gets ignored by dxilgen and results in a pointer of the wrong type being passed, producing a very late assert and crash.

**Closed** 2020-07-28 19:56 UTC
Labels: bug
