### ISSUE TITLE
dxc crashes with custom shaders

### ISSUE THREAD

**Issue by capitalknew** [Microsoft/DirectXShaderCompiler#451] opened 2017-07-21 20:31 UTC
These shaders are pass validation, but not a compilation i.e. dxc crashes. I don't know why it happens, I have no test case where it can crash. Shaders are much different, with different roles. But all shaders is compute. 
https://github.com/capitalknew/paper-render-2/tree/master/directx-sdk

I found issues with layout, and with memory usage. I found problems of HLSL with structures.

**Comment by python3kgae** [comment] 2017-07-25 07:27
Hi, 
I tried to run build-shaders.cmd under direct-sdk.
It finished without crash.
Could you offer more detail of the crash?

Thanks
Xiang

**Comment by capitalknew** [comment] 2017-07-25 07:28
Try older commits, It had crashes (with nested structures). I enspecial reformed code.

**Comment by python3kgae** [comment] 2017-07-25 20:28
Could you offer a file name or commit link?

**Comment by capitalknew** [comment] 2017-07-25 20:30
uniform.hlsl (early named)

**Comment by python3kgae** [comment] 2017-07-25 21:31
Cannot find uniform.hlsl, only uniforms.hlsl which is a header file.
Tried old commit link: https://github.com/capitalknew/paper-render-2/commit/13f56ab65ac28bbdcb17e45d103062fd9615dd42
Still cannot reproduce.

Could you please offer a reproduce command line and a commit link for the files.

**Comment by capitalknew** [comment] 2017-07-26 06:08
This commit and header. 
https://github.com/capitalknew/paper-render-2/blob/7fb68c9e4b130f59b6f117869769ca4bddc759bc/directx-sdk/include/uniforms.hlsl

**Comment by python3kgae** [comment] 2017-07-26 20:24
Thanks for the feedback.
2 issues here.
1. nested struct on uav not work.
2. use share memory as argument not work.

Fixing.

**Comment by python3kgae** [comment] 2017-07-27 00:07
Fixed with https://github.com/Microsoft/DirectXShaderCompiler/pull/473 and https://github.com/Microsoft/DirectXShaderCompiler/pull/472
Will check in after pass test.

**Comment by python3kgae** [comment] 2017-07-27 01:25
Fixes are checked in.
Hope it fix all your issues.

Thanks
Xiang

**Comment by marcelolr** [comment] 2017-08-29 22:02
@capitalknew, please reopen or file a new issue if you're still running into problems here - thanks!

**Closed by marcelolr** 2017-08-29 22:02 UTC
