### ISSUE TITLE
Gather with non-constant offset

### ISSUE THREAD

**Issue by jmccarthy634** [microsoft/DirectXShaderCompiler#3690] opened 2021-04-16 02:14 UTC
When compiling this HLSL snippet with `-T ps_6_0 -E psMain -O3`
```
Texture2D<float> g_texture : register(t0);
SamplerState g_samplerState : register(s0);

void psMain(
	in float3 texCoords : TEXCOORD0,
	out float4 outColor : SV_Target0)
{
	float4 col = float4(0.f, 0.f, 0.f, 1.f);
	int x = 0, y = 0;
	for( y = -5; y <= 5; y += 2 )
	{
		[loop]
		for( x = -5; x <= 5; x += 2 )
		{
			float4 d4 = g_texture.Gather(g_samplerState, texCoords.xy, int2(x, y));
			col += d4;
		}
	}
	outColor = col;
}
```
I get this error:
```
gather_loop.hlsl:15:16: error: Offsets to texture access operations must be immediate values.
                        float4 d4 = g_texture.Gather(g_samplerState, texCoords.xy, int2(x, y));
                                    ^
gather_loop.hlsl:15:16: error: Offsets to texture access operations must be immediate values.
gather_loop.hlsl:15:16: error: Offsets to texture access operations must be immediate values.
gather_loop.hlsl:15:16: error: Offsets to texture access operations must be immediate values.
gather_loop.hlsl:15:16: error: Offsets to texture access operations must be immediate values.
gather_loop.hlsl:15:16: error: Offsets to texture access operations must be immediate values. Unrolling the loop containing the offset value manually and using -O3 may help in some cases.
```

Is this really an error? The HLSL docs don't make mention of offset needing to be constant for Gather functions (and AFAIK spir-v explicitly _allows_ for non constant offsets for gather instructions), only for Load and Sample, and this code seems to compile just fine on FXC and older versions of DXC.

**Comment by jaebaek** [comment] 2021-04-19 13:55
IIUC, you used `-spirv` option, right?
This bug was fixed by #3656. I just doublechecked it with your code and it worked fine.

FYI, spir-v does not allow non-constant offsets for `OpImage*`, which is regulated by a recent spirv-val PR https://github.com/KhronosGroup/SPIRV-Tools/pull/4118.

**Comment by jmccarthy634** [comment] 2021-04-19 19:31
Sorry no, this is not using `-spirv`.

**Comment by jaebaek** [comment] 2021-04-19 20:30
Thank you for clarifying it.

@pow2clk FYI .. since I tagged it as a SPIR-V issue, I might make you guys confused. This is not a SPIR-V issue.

**Comment by pow2clk** [comment] 2021-04-19 20:45
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-to-gather

"The texture offsets need to be static." is meant to indicate that offsets have to be literal integers. It could probably use a rewording. Nevertheless, while this was allowed by DXC for a while, it has never been specced to work. So even though the compiler accepted it, the result may not have been what was intended for all platforms. 

There is a chance this is revisited for future shader models, but we need feedback from hardware vendors to do that. We cannot do it unilaterally. As such, this is working as intended.

**Closed by pow2clk** 2021-04-19 20:45 UTC

**Comment by jmccarthy634** [comment] 2021-04-19 20:51
Thanks for clarifying.
