### ISSUE TITLE
[Feature Request] Support SPV_NV_shader_invocation_reorder

### ISSUE THREAD

**Issue by NoSW** [microsoft/DirectXShaderCompiler#6994] opened 2024-11-01 03:12 UTC

**Comment by damyanp** [comment] 2024-11-05 18:11
Duplicate of microsoft/hlsl-specs#277

**Closed by damyanp** 2024-11-05 18:11 UTC
Labels: enhancement, needs-triage

**Comment by devshgraphicsprogramming** [comment] 2024-11-06 09:27
I think this should be doable in Inline SPIR-V
