### ISSUE TITLE
`Texture2DArray.SampleLevel()` errors with `Module bitcode is invalid.`

### ISSUE THREAD

**Issue by ben-clayton** [microsoft/DirectXShaderCompiler#5082] opened 2023-03-06 13:28 UTC
HLSL:

```hlsl
Texture2DArray<float4> t : register(t0, space1);
SamplerState s : register(s1, space1);
RWByteAddressBuffer prevent_dce : register(u0, space2);

void fragment_main() {
  float4 res = t.SampleLevel(s, (1).xxx, 1.0f, (1).xx);
  prevent_dce.Store4(0u, asuint(res));
}
```

Compiling with: `dxc test.hlsl -Tps_6_0 -E fragment_main`, gives the following output:

```
warning: DXIL.dll not found.  Resulting DXIL will not be signed for use in release environments.

error: validation errors
error: Module bitcode is invalid.
error: Call parameter type does not match function signature!
i64 1
 i32  %4 = call %dx.types.ResRet.f32 @dx.op.sampleLevel.f32(i32 62, %dx.types.Handle %2, %dx.types.Handle %3, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float undef, i64 1, i64 1, i32 undef, float 1.000000e+00)

Validation failed.
```

Reproduced with 7a45cbbf8bab340d212d72c3cfe9f8c5f5837ccf

**Comment by ben-clayton** [comment] 2023-03-06 13:36
Same thing for `SampleBias`:

```hlsl
Texture2D<float4> t : register(t0, space1);
SamplerState s : register(s1, space1);
RWByteAddressBuffer prevent_dce : register(u0, space2);

void fragment_main() {
  float4 res = t.SampleBias(s, (1).xx, 1, (1).xx);
  prevent_dce.Store4(0u, asuint(res));
}
```

`SampleCmpLevelZero`:

```hlsl
Texture2DArray t : register(t0, space1);
SamplerComparisonState s : register(s1, space1);
RWByteAddressBuffer prevent_dce : register(u0, space2);

void fragment_main() {
  float res = t.SampleCmpLevelZero(s, (1).xxx, 1, (1).xx);
  prevent_dce.Store(0u, asuint(res));
}
```

and `SampleGrad`:

```hlsl
Texture2DArray<float4> t : register(t0, space1);
SamplerState s : register(s1, space1);
RWByteAddressBuffer prevent_dce : register(u0, space2);

void fragment_main() {
  float4 res = t.SampleGrad(s, (1).xxx, 1, 1, (1).xx);
  prevent_dce.Store4(0u, asuint(res));
}
```

**Comment by ben-clayton** [comment] 2023-03-06 13:45
Actually, it looks like most (all?) of the texture sampling operations have the same issue.

Am I passing invalid arguments? If so, should the frontend be pointing me at the invalid argument(s)?
FWIW, I seem to be able to compile these with FXC.

**Comment by vettoreldaniele** [comment] 2023-03-06 14:49
The problem here seems to be the `(1).xx` notation. This expands a `uint` into a `uint2`, while the arguments the function takes are float2. This does work with use `(1.0).xx`. I agree the error message should definitely be better.

**Comment by ben-clayton** [comment] 2023-03-06 14:57
> The problem here seems to be the `(1).xx` notation. This expands a `uint` into a `uint2`, while the arguments the function takes are float2

The first argument takes a float2, but the `offset` argument (last argument) should take an `int2`

**Comment by ben-clayton** [comment] 2023-03-06 14:58
Also - I thought HLSL did implicit conversion of int -> float for arguments like this?

**Comment by vettoreldaniele** [comment] 2023-03-06 15:20
You're right, `offset` should a be uint2. It's really weird. The following works, which seems to point at a problem in handling a literal uint -> uint2. The second argument is correctly made into a float2 with a uint literal though.

```
uint y = 1;
float4 res = t.SampleBias(s, (1).xx, 1, (y).xx);
```

https://shader-playground.timjones.io/2aedc281a448744bbb62f9f66e0f40ed

**Comment by ben-clayton** [comment] 2023-03-06 15:44
> You're right, `offset` should a be uint2. It's really weird. The following works, which seems to point at a problem in handling a literal uint -> uint2. The second argument is correctly made into a float2 with a uint literal though.

`int2`, not `uint2`. `offset` is signed.

**Comment by teoxoy** [comment] 2023-05-09 13:40
Just bumped into this as well. 👋 @ben-clayton

```
error: validation errors
error: Module bitcode is invalid.
error: Call parameter type does not match function signature!
i64 3
 i32  %5 = call %dx.types.ResRet.f32 @dx.op.textureGatherCmp.f32(i32 74, %dx.types.Handle %1, %dx.types.Handle %2, float 5.000000e-01, float 5.000000e-01, float undef, float undef, i64 3, i64 3, i32 0, float 5.000000e-01)

Validation failed.
```

Based on the error and some experimentation it seems to me that literals without an explicit suffix that are splatted inline (and passed for the offset arg) are interpreted as i64.

```hlsl
SamplerComparisonState sampler_cmp : register(s1, space1);
Texture2D<float> image_2d_depth : register(t2, space1);

float4 PSMain() : SV_Target0
{
    return image_2d_depth.GatherCmp(sampler_cmp, (0.5).xx, 0.5, (3).xx);
    //                                                           ^ adding any suffix here u/l (or even 64bit ones L/U) seems to fix the issue
}
```

For reference, FXC is not exhibiting this behavior.

**Comment by teoxoy** [comment] 2023-05-09 13:43
To be clear, the issue is caused whenever an unsuffixed literal is splatted and passed to the **`offset`** argument. Splatted unsuffixed literals passed to any of the other arguments work just fine.

**Comment by damyanp** [comment] 2024-08-28 17:15
https://godbolt.org/z/sd9474YWW

**Comment by damyanp** [comment] 2024-08-28 17:17
This is resolved in HLSL 202x https://godbolt.org/z/xsG7f87rY

**Closed by damyanp** 2024-08-28 17:17 UTC
Labels: bug
