### ISSUE TITLE
-fspv-debug=vulkan-with-source crash issue

### ISSUE THREAD

**Issue by Goshido** [microsoft/DirectXShaderCompiler#5441] opened 2023-07-20 15:32 UTC
I decided to compile _HLSL → SPIR-V_ with source file information. My target is _RenderDoc 1.27_ and "original"-like shaders in _Edit shader_ window. I followed [_RenderDoc_'s best practices](https://renderdoc.org/docs/how/how_debug_shader.html) and got compiler error after adding `-fspv-debug=vulkan-with-source` flag.

### Minimal repro steps

I attached minimal reproducible example with vertex shader sources and bat script with all compilation parameters. You need to change `DXC_LOCATION` variable inside the `build_test.bat` to `dxc.exe` v1.7.2212.10216 executable (commit SHA-1 `2096d1b8054d1de864924ef0c5009f533597b9d4`).

[Direct link to issue-001.zip](https://github.com/microsoft/DirectXShaderCompiler/files/12111378/issue-001.zip)

### Expected result

Compilation success. _DXC_ produces _SPIR-V_ binaries.

### Actual result

Compilation error:

```powershell
Compiling: D:\Development\DXC-builds\Release-2023-07-04\bin\dxc.exe -HV 2021 -spirv -fvk-use-dx-layout -fspv-reduce-load-size -fspv-target-env=vulkan1.1 -enable-16bit-types -WX -I .\..\..\..\hlsl -I .\..\..\..\cpp\include\pbr -Od -fspv-debug=vulkan-with-source -E VS -T vs_6_7 -Fo .\..\..\..\assets\shaders\common_opaque.vs.spv .\..\..\..\hlsl\common_opaque.vs
Internal compiler error: access violation. Attempted to read from address 0x0000000000000000
Done
```

No _SPIR-V_ binaries.

### Further technical details

- `git submodule update --init` has been invoked before build
- `hctbuild` build parameters: `-official -rel -x64 -vs2022 -speak-up -no-dxilconv -spirv`
- _Visual Studio 2022 Community_ components were up to date.
- _Windows 11 Pro 64-bit (22621.1992, Version 22H2)_
- `dxc.exe` v1.7.2212.10216 executable, commit SHA-1 `2096d1b8054d1de864924ef0c5009f533597b9d4`

Would you kindly help?

**P.S.** I tried _DirectX Shader Compiler_ 1.7.2212.10142. Same result.

**Comment by s-perron** [comment] 2023-07-21 15:17
I suspect this is the same as #5113.

**Comment by Goshido** [comment] 2023-07-24 04:23
@s-perron do you have any insides when this issue could be fixed. Is it serious and require big _DXC_ refactoring?

**Comment by s-perron** [comment] 2023-07-24 14:36
This is not the same as #5113. It is a duplicate of #5080.

**Closed by s-perron** 2023-07-24 14:36 UTC
Labels: bug, spirv
