### ISSUE TITLE
Marking struct member as globally coherent will emit a false positive warning

### ISSUE THREAD

**Issue by KStocky** [microsoft/DirectXShaderCompiler#6103] opened 2023-12-11 16:55 UTC
**Description**

If a struct has a member that is marked as globally coherent, it will produce seemingly correct DXIL. However, it will also emit the following warning "'globallycoherent' attribute only applies to variables and functions". If the DXIL is correct then I don't think that this warning is correct.

**Steps to Reproduce**

With -WX: https://shader-playground.timjones.io/0298d3616e5fc41e80aad4ca955e1f64
Without -WX: https://shader-playground.timjones.io/4638770e2b3a102105b2ed15df815647

**Actual Behavior**
Warning emitted when it shouldn't be.

**Environment**
- DXC version 1.7.2308.12
- Host Operating System Windows 10 Pro 22H2

**Comment by llvm-beanz** [comment] 2023-12-11 22:26
This is a duplicate of #6092.

**Closed by llvm-beanz** 2023-12-11 22:26 UTC
Labels: bug, needs-triage
