### ISSUE TITLE
fatal error: generated SPIR-V is invalid: Expected input to have the same total bit width as Result Type: Bitcast

### ISSUE THREAD

**Issue by jayfoad** [microsoft/DirectXShaderCompiler#5318] opened 2023-06-23 11:10 UTC
With a `dxc` that I have just built from the `main` branch I get:
```
$ cat y.hlsl
[numthreads(1, 1, 1)]
void entrypoint()
{
  bool a = false;
  uint64_t b = a ? (1 << 56) : 0;
}
```
```
$ ~/git/DirectXShaderCompiler/build/bin/dxc -fspv-target-env=vulkan1.1 -spirv -E entrypoint -T cs_6_2 -Od y.hlsl
fatal error: generated SPIR-V is invalid: Expected input to have the same total bit width as Result Type: Bitcast
  %24 = OpBitcast %ulong %23

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

**Comment by jayfoad** [comment] 2023-06-23 14:32
Bisects to #4935.

**Comment by s-perron** [comment] 2023-06-23 16:15
Closing as a duplicate of https://github.com/microsoft/DirectXShaderCompiler/issues/5319

**Closed by s-perron** 2023-06-23 16:15 UTC
Labels: bug, spirv
