### ISSUE TITLE
IDxcResult of failed compilation can report that there is no DXC_OUT_ERRORS output with GetOutputByIndex

### ISSUE THREAD

**Issue by KStocky** [microsoft/DirectXShaderCompiler#5923] opened 2023-10-25 08:31 UTC
**Description**
With most failed compilations, trying to retrieve the error output using IDxcResult::GetNumOutputs and IDxcResult::GetOutputByIndex to inspect all parts of an IDxcResult works fine. However, with some failed compilations, this method will fail as there will be a single output reported by IDxcResult::GetNumOutputs and it will be of type DXC_OUT_NONE. Despite this, in these circumstances, the error buffer can be retrieved using IDxcResult::GetOutput with DXC_OUT_ERRORS or with IDxcOperationalResult::GetErrorBuffer.

**Steps to Reproduce**

Compile the following shader
```
RWBuffer<float> Buff;

float16_t InVal;
[numthreads(1,1,1)]
void Main(uint3 DispatchThreadId : SV_DispatchThreadID)
{
    Buff[DispatchThreadId.x] = 32.0h * InVal;
}
```
with the following arguments
-E Main -T cs_6_0 -Zs -Zss -Zpr -O3 -enable-16bit-types

with IDxcCompiler3::Compile

**Actual Behavior**
Calling IDxcResult::GetNumOutputs will return 1
Calling IDxcResult::GetOutputByIndex(0) will return an output of type DXC_OUT_NONE
Calling IDxCResult::GetOutput with DXC_OUT_ERRORS will succeed and provide the expected error

**Expected Behaviour**
I would expect that if there was an error output for it to be retrieved using IDxcResult::GetOutputByIndex

**Environment**
- DXC version 1.7.2308
- Host Operating System Windows 10 Pro: 22H2

**Comment by llvm-beanz** [comment] 2023-10-25 15:20
Here's a [godbolt link](https://godbolt.org/z/MExG59qoP).

**Comment by damyanp** [comment] 2024-10-24 17:16
Duplicate of #6523

**Closed by damyanp** 2024-10-24 17:16 UTC
Labels: bug
