### ISSUE TITLE
Optimizing pow with a literal exponent

### ISSUE THREAD

**Issue by TheRealMJP** [Microsoft/DirectXShaderCompiler#1244] opened 2018-04-24 00:27 UTC
Hey guys! The old FXC compiler would always optimize certain cases of pow with a literal exponent. The classic case is something like this, with an exponent of 2.0:

```
float PSMain(in float x : X) : SV_Target0
{
    return pow(x, 2.0f);
}
```

FXC produces the following DXBC output for this:

```
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.x
dcl_output o0.x
mul o0.x, v0.x, v0.x
ret
```

As you can see it removed the pow and instead multplied x with itself, which I would assume is always going to be cheaper than the log2/mul/exp2 sequence that you get with an non-constant exponent. It looks like dxc doesn't do this transformation:

```
define void @PSMain() {
entry:
  %0 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 0, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %Log = call float @dx.op.unary.f32(i32 23, float %0)  ; Log(value)
  %1 = fmul fast float %Log, 2.000000e+00
  %Exp = call float @dx.op.unary.f32(i32 21, float %1)  ; Exp(value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %Exp)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void
}
```

Do you guys know if this is intentional? If not, I think it would be nice to include that optimization for cases where people use pow(x, 1), pow(x, 2) or pow(x, 4) for convenience.

**Comment by hekota** [comment] 2018-04-25 21:26
Thank you for the suggestion! It would certainly be nice to optimize these cases. I'll see what we can do!

**Comment by gwihlidal** [comment] 2018-09-11 19:14
This would be a welcome optimization; it is very common to see `pow(x, 2)`, `pow(x, 3)`, etc.. in a variety of shaders, and this is a perf and numerical regression compared to fxc.

Getting power expansion up to 16 would likely cover what fxc was doing.

**Comment by hekota** [comment] 2018-09-11 19:43
We are considering adding pow and a few other routines to core intrinsics, meaning they would be provided to the driver for custom optimization and enabling the use of hardware implementation when available.

**Comment by tex3d** [comment] 2018-11-01 23:00
For backwards compatibility, the referenced changes will do what fxc did, as long as you pass -HV 2016 (HLSL Version 2016).  This should cover existing code you don't want to edit.  The issue is that this expansion isn't always correct according to the spec (and IEEE safe mode doesn't correct it on fxc either).

Currently, when we lower (and expand to muls or log/mul/exp), we don't yet know whether things are marked precise, so we can't decide whether mul expansion is ok.  Later, when we have precise marking, we would have to match the log-mul-exp pattern without precise and replace it with a mul expansion.  Since doing this is extra work and the ideal optimization will be dependent on the target device, it's probably best left to the driver to decide whether to do this optimization.

Additionally, in future shader models, we plan on having a native pow intrinsic in DXIL, so this can be more easily matched for optimization.  But the ideal expansion should still be performed by the driver compiler.

For new/modified HLSL, you can use your own manual multiply expansion if that's really what you want.  Then you don't have to worry about the spec issues.  Here's a function to do the expansion, with overloads for vector sizes, that should optimize to the code you want when using a literal uint up to 15.

**Comment by vcsharma** [comment] 2018-11-04 06:06
Thanks @tex3d for the additional explanation! 

Given that we have added support to match fxc's behavior for pow with literal exponent in #1564 which is available with `-HV 2016` flag, I am closing this issue.

**Closed by vcsharma** 2018-11-04 06:06 UTC
Labels: performance
