### ISSUE TITLE
[SPIR-V] Bitfield members are broken

### ISSUE THREAD

**Issue by DBouma** [microsoft/DirectXShaderCompiler#4295] opened 2022-02-23 16:36 UTC
Given the following struct:

```hlsl
struct ResourceHandleData {
    uint index : 23;
    uint tag : 3;
    uint version : 6;
};
```
It should be represented as a 32 bit uint. When `ResourceHandleData` is read from a push constant slot, a validation layer error is given by the Vulkan validation layer that the specific push constant (which should contain the `RenderHandleData` in my case) is out of range, following with a device removal. 

However this behavior works perfectly fine when using DXIL, ~~my assumption is that bitfield members are not properly represented when used in combination with push constants. I have yet to test this with non-pushconstants however, but that may also be broken.~~ 

EDIT: Simple casting from uint to `ResourceHandleData` from a different location other then push constants also causes the same broken behavior.

**Comment by sudonatalie** [comment] 2022-02-24 21:28
SPIR-V codegen does not yet support bitfield members, however we plan to implement it in the near future as part of our HLSL 2021 support.

Duplicate of #4140

**Closed** 2022-02-24 21:28 UTC
