### ISSUE TITLE
Unexpected conversion of wave intrinsics to 64-bit with literal argument

### ISSUE THREAD

**Issue by scottp101** [microsoft/DirectXShaderCompiler#3401] opened 2021-01-28 01:16 UTC
Compiling this compute shader:

```hlsl
RWStructuredBuffer<uint> data : register(u0);
[numthreads(16,1,1)]
void main(uint3 tid : SV_DispatchThreadID )
{
    data[tid.x] = WaveActiveSum(1);
}
```

yields:

```llvm
define void @main() {
  %1 = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 1, i32 0, i32 0, i1 false)
  %2 = call i32 @dx.op.threadId.i32(i32 93, i32 0)
  %3 = call i64 @dx.op.waveActiveOp.i64(i32 119, i64 1, i8 0, i8 0)
  %4 = trunc i64 %3 to i32
  call void @dx.op.rawBufferStore.i32(i32 140, %dx.types.Handle %1, i32 %2, i32 0, i32 %4, i32 undef, i32 undef, i32 undef, i8 1, i32 4)
  ret void
}
```

whereas doing WaveActiveSum(**1U**) yields:

```llvm
%3 = call i32 @dx.op.waveActiveOp.i32(i32 119, i32 1, i8 0, i8 1)
```

### Functional impact
Platforms that do not support 64-bit ops may not compile this correctly. There may also be a performance impact.

I haven't tested all wave intrinsics but this also occurs with `WavePrefixSum(1)` so it's not specific to `WaveActiveSum`.

### Minimal repro steps
Take the [v1.5.2010](https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.5.2010) release of dxc and compile the above shader with:

```dxc.exe -T cs_6_5 shader.hlsl -Fc output.dxil -E main```

### Expected result
I would expect this to generate a 32-bit version of the wave op or possibly an ambiguous overload error message.

**Comment by pow2clk** [comment] 2021-11-18 20:08
Hi @scottp101!

This is a duplicate of #3380 and should be fixed shortly

**Closed by pow2clk** 2021-11-18 20:08 UTC
