### ISSUE TITLE
Nested loop unrolling fails when the bound depends on the outer loop iteration variable

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/DirectXShaderCompiler#1946] opened 2019-02-19 20:26 UTC
Repro:
```
int main() : OUT
{
    int x = 0;
    [unroll]
    for (uint i = 0; i < 1; i++)
    {
        [unroll]
        for (uint j = 0; j < i; j++)
            x++;
    }
    return x;
}
```
DXC: `error: Could not unroll loop. Use /Zi for source location.`
FXC: 
```
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_output o0.x
mov o0.x, l(0)
ret
```

**Comment by galop1n** [comment] 2019-06-06 15:34
Some shaders in the raytracing fallback layer also suffers from the "could not unroll loop." problem. They use to be fine, obviously, so it is looks like a regression.

**Comment by pearcewf** [comment] 2019-06-19 14:09
In case it helps, I thought I might add that I notice this happens when creating .cso output, but not when SPIR-V options are enabled.

I.e., building the same shader with the flags -spirv and -fspv-target-env=vulkan1.1 works as expected.

**Comment by MrTrillian** [comment] 2019-06-19 15:25
@pearcewf Thanks for commenting. The SPIR-V path is completely separate from the normal (DXIL) path, so codegen issues like this are not expected to be shared between both backends.

**Comment by BitMD** [comment] 2021-02-22 22:04
fixed by Adam

**Closed by BitMD** 2021-02-22 22:04 UTC
Labels: bug
