### ISSUE TITLE
Linux compilation

### ISSUE THREAD

**Issue by gwihlidal** [Microsoft/DirectXShaderCompiler#1082] opened 2018-02-20 10:35 UTC
Compilation support for Linux is really important for us (ideally, we want to have multiple shader building services using Docker and Kubernetes). Since DXC is LLVM based, I don't feel like there are major obstacles to overcome here, but the repo has been Windows-centric for a while, so there are some areas that would need to be addressed to handle this (Batch scripts, COM usage, DXGI dependency, etc..)

Has this been discussed yet? I'm willing to contribute in this area, but ideally it would be a larger push from the owners, as well. I think the first step is replacing the build batch scripts with something like python, so the cmake overrides can be applied consistently on both Windows and Linux. Many other scripts in the hctbuild directory are already python, so it seems like a good fit.

Thank you!
Graham

**Comment by oscarbg** [comment] 2018-02-27 07:35
Now with Vulkan SDK MacOS available also DirectXShaderCompiler SPIR-V support maybe useful on that platform..
@gwihlidal  hopefully the efforts of a Linux port will bring MacOS support with minimal changes, right?

**Comment by ehsannas** [comment] 2018-05-08 19:25
Hi @gwihlidal , This seems to be a duplicate of #1236 . So I will close this one and will report status there.
Thanks

**Closed by ehsannas** 2018-05-08 19:25 UTC
