### ISSUE TITLE
[SPIRV] Missing gl_NumWorkGroups

### ISSUE THREAD

**Issue by Eichenherz** [microsoft/DirectXShaderCompiler#4217] opened 2022-01-30 15:26 UTC
I'm currently using this to atomically count the workgroups as such:
```glsl
if( ( gl_LocalInvocationID.x == 0 ) && ( workgrAtomicCounterShared == gl_NumWorkGroups.x - 1 ) )
//...... DO some work on the final value of a counter
```
In SPIRV gl_NumWorkGroups would be:
```spirv
OpDecorate %gl_NumWorkGroups BuiltIn NumWorkgroups
```

How do I access the same BuiltIn in HLSL as it's not exposed through any SV ?

**Comment by pow2clk** [comment] 2022-02-07 22:33
Hi @Eichenherz!

There is not currently an HLSL equivalent to `g_NumWorkGroups`. I'm inferring from the information provided that you'd like this to target SPIRV. As such, I'll leave it to the SPIRV folks @jaebaek and @sudonatalie if they plan to do something here.

In the meantime, you might consider passing the information through a constant buffer (UBO in GL speak) good luck!

**Comment by Eichenherz** [comment] 2022-02-08 06:49
Yes, precisely for HLSL to SPIRV. I did try the vk::ext_decorate(24) as that's the NumWorkgroups ID. But it would not produce any "OpDecorate Builtin NumWorkgroups".

**Comment by jaebaek** [comment] 2022-02-08 23:18
Sorry for being late. We will take a look. Definitely, we have to consider adding some new intrinsics. We currently experience intense workloads. It can be delayed. Sorry about that in advance.

**Comment by sudonatalie** [comment] 2022-04-29 17:11
`[[vk::ext_decorate(/* BuiltIn */ 11, /* NumWorkGroups */ 24)]]` does correctly generate the desired `OpDecorate %var BuiltIn NumWorkgroups`, but the problem is getting `%var` to be the correct type with our current implementation. If you decorate a global, then it gets wrapped in the `Globals` struct, and the decoration is incorrectly applied to the wrapper. If an entry point input variable is decorated, then it needs a semantic string. I think this issue should be handled along with #4195, but I'll leave it to @jaebaek to determine if it's a duplicate before closing.

**Comment by jaebaek** [comment] 2022-05-03 17:01
I think we can define a variable like the following example:
```
RWStructuredBuffer<int> A;

[numthreads(1,1,1)]
void main() {
  [[vk::ext_storage_class(1)]]
  [[vk::ext_decorate(11, 24)]]
  uint3 numWorkgroups;

  A[0] = numWorkgroups.x;
}
```

However, the validation layer report an error
```
fatal error: generated SPIR-V is invalid: Interface variable id <2> is used by entry point 'main' id <1>, but is not listed as an interface
  %numWorkgroups = OpVariable %_ptr_Input_v3uint Input
```

We have to check the variable storage class and add it as an operand of the entry point.

**Comment by forbiddencactus** [comment] 2023-03-17 03:53
@jaebaek

Do you have any update on this issue? I'm keen to take advantage of the code snipped you posted above but I'm running into the same `is not listed as an interface` issue.

**Comment by s-perron** [comment] 2023-06-02 18:40
This is going to be a bigger issues to fix. I don't want to just do another hack with the existing inline spir-v. I'm going to look into revamping the whole feature.

**Comment by s-perron** [comment] 2023-06-13 18:45
I opened https://github.com/microsoft/hlsl-specs/pull/59. This should add a new attribute that can be used to properly define builtin input and output.

**Comment by kpentaris** [comment] 2023-06-30 10:33
Also looking for a similar fix regarding access to Compute Shader globals  (gl_GlobalInvocationID, gl_LocalInvocationIndex etc). Please note that these need to be **globally** accessible from a shader file that is `#include`d and has no access to any entry point!

```
#include "utils.hlsl"
// Contains the following
void initializeArr() {
  [[vk::ext_storage_class(1)]]
  [[vk::ext_decorate(11, 28)]]
  uint3 gl_GlobalInvocationID;
  arr[gl_GlobalInvocationID.x] = 0;
}
// end of utils.hlsl

void main() {
  initializeArr();
}
```

**Comment by s-perron** [comment] 2023-06-30 13:35
@kpentaris That is the current plan in https://github.com/microsoft/hlsl-specs/pull/59.

**Comment by devshgraphicsprogramming** [comment] 2023-07-31 11:33
> @kpentaris That is the current plan in [microsoft/hlsl-specs#59](https://github.com/microsoft/hlsl-specs/pull/59).

and when will it land in DXC?

**Comment by s-perron** [comment] 2023-08-08 15:08
No idea when it will land.

**Comment by OlesenJonas** [comment] 2023-12-18 12:17
It seems possible to override an existing input as a workaround. Eg: im currently (ab)using SV_GroupIndex to get the SubgroupID:
```[[vk::ext_decorate(11/*BuiltIn*/, 40/*SubgroupId*/)]] int waveIndex : SV_GroupIndex```

**Closed** 2024-01-02 14:41 UTC
Labels: spirv

**Comment by devshgraphicsprogramming** [comment] 2024-01-02 22:45
@kptentaris
