### ISSUE TITLE
[SPIR-V] Templated Load inconsistency

### ISSUE THREAD

**Issue by artamonovoleg** [microsoft/DirectXShaderCompiler#6425] opened 2024-03-17 15:04 UTC
Templated Load is inconsistent for matrix types.

**Steps to Reproduce**
Recently, I rewrote a shader section that previously loaded a structure to instead partially load its fields. After making this change, I noticed that matrices in DXIL appeared to be transposed, while in SPIR-V, they continued to work correctly.

Minimal example: https://godbolt.org/z/rc8n4qKEc

**Comment by damyanp** [comment] 2024-03-18 16:45
@sudonatalie - Microsoft thinks that DXIL is likely correct in this case.  Could you have a look and confirm, or let us know if you think DXIL is at fault?  Thanks!

**Comment by sudonatalie** [comment] 2024-03-18 18:26
@damyanp It looks to me like the matrix packing is the same for both in SPIR-V, but DXIL has a `colMatToRowMat` cast for the struct-wrapped example, which I'm guessing transposes from column-major to row-major. If this is correct, do you have any pointers to HLSL/DX documentation that might explain it? Otherwise my assumption would also be that the SPIR-V seems correct.

**Comment by damyanp** [comment] 2024-03-20 20:24
@tex3d / @python3kgae - do either of you have any insights here or references to any DX documentation that covers this?

**Comment by python3kgae** [comment] 2024-03-20 23:29
> @tex3d / @python3kgae - do either of you have any insights here or references to any DX documentation that covers this?

I think it is an issue for the Load<float4x4> case.
We could fix this case. 

But Load<row_major float4x4> will need to make different major real different types, since the template will ignore the matrix major qualifiers. We plan to not do this big change for DXC.

**Comment by artamonovoleg** [comment] 2024-03-21 07:13
> > @tex3d / @python3kgae - do either of you have any insights here or references to any DX documentation that covers this?
> 
> I think it is an issue for the Load< float4x4 > case. We could fix this case.
> 
> But Load<row_major float4x4> will need to make different major real different types, since the template will ignore the matrix major qualifiers. We plan to not do this big change for DXC.

If this is possible, I would prefer the SPIR-V variant, since modifiers for structure are ignored anyway. It's logical if it will be the same for float4x4 and other matrix types.

**Comment by plekakis** [comment] 2024-03-21 15:32
For what it's worth, you can specify the following:
**-fspv-use-legacy-buffer-matrix-order**
Which for me solves the problem, at least now my buffer loads/stores are treated as row major.

Relevant thread: 
https://github.com/microsoft/DirectXShaderCompiler/issues/3370

**Comment by sudonatalie** [comment] 2024-03-26 17:24
I think this issue can be closed as a duplicate of #3370. It seems like too breaking of a change to be likely to be fixed on the DX side, so the `-fspv-use-legacy-buffer-matrix-order` is the recommended approach to make SPIR-V match DXIL.

**Closed by sudonatalie** 2024-03-26 17:24 UTC
Labels: bug, spirv, matrix-bug, needs-triage
