### ISSUE TITLE
DXC crashes if Patch Constant Function is defined *after* the Hull shader entry point

### ISSUE THREAD

**Issue by ehsannas** [Microsoft/DirectXShaderCompiler#677] opened 2017-10-04 19:58 UTC
The following Hull shader compiles successfully:
```hlsl
// -*- mode: hlsl; hlsl-entry: SubDToBezierHS; hlsl-target: hs_6_0; hlsl-args: /Zi; -*-

#define MAX_POINTS 32

// Input control point
struct VS_CONTROL_POINT_OUTPUT
{
  float3 vPosition : WORLDPOS;
  float2 vUV       : TEXCOORD0;
  float3 vTangent  : TANGENT;
};

// Output control point
struct BEZIER_CONTROL_POINT
{
  float3 vPosition	: BEZIERPOS;
};

// Output patch constant data.
struct HS_CONSTANT_DATA_OUTPUT
{
  float Edges[4]        : SV_TessFactor;
  float Inside[2]       : SV_InsideTessFactor;
};

// Patch Constant Function
HS_CONSTANT_DATA_OUTPUT SubDToBezierConstantsHS(InputPatch<VS_CONTROL_POINT_OUTPUT, MAX_POINTS> ip, uint PatchID : SV_PrimitiveID) {
  HS_CONSTANT_DATA_OUTPUT Output;
  
  // Must initialize Edges and Inside; otherwise HLSL validation will fail.
  Output.Edges[0]  = 1.0;
  Output.Edges[1]  = 2.0;
  Output.Edges[2]  = 3.0;
  Output.Edges[3]  = 4.0;
  Output.Inside[0] = 5.0;
  Output.Inside[1] = 6.0;
  
  return Output;
}

[domain("quad")]
[partitioning("fractional_odd")]
[outputtopology("triangle_cw")]
[outputcontrolpoints(16)]
[patchconstantfunc("SubDToBezierConstantsHS")]
BEZIER_CONTROL_POINT SubDToBezierHS(InputPatch<VS_CONTROL_POINT_OUTPUT, MAX_POINTS> ip, uint i : SV_OutputControlPointID, uint PatchID : SV_PrimitiveID) {
  VS_CONTROL_POINT_OUTPUT vsOutput;

  // Insert code to compute Output here.
  BEZIER_CONTROL_POINT result;
  result.vPosition = vsOutput.vPosition;
  
  return result;
}
```

However, if I move the Patch Constant Function after the entry point, DXC crashes:
```hlsl
// -*- mode: hlsl; hlsl-entry: SubDToBezierHS; hlsl-target: hs_6_0; hlsl-args: /Zi; -*-

#define MAX_POINTS 32

// Input control point
struct VS_CONTROL_POINT_OUTPUT
{
  float3 vPosition : WORLDPOS;
  float2 vUV       : TEXCOORD0;
  float3 vTangent  : TANGENT;
};

// Output control point
struct BEZIER_CONTROL_POINT
{
  float3 vPosition	: BEZIERPOS;
};

// Output patch constant data.
struct HS_CONSTANT_DATA_OUTPUT
{
  float Edges[4]        : SV_TessFactor;
  float Inside[2]       : SV_InsideTessFactor;
};

[domain("quad")]
[partitioning("fractional_odd")]
[outputtopology("triangle_cw")]
[outputcontrolpoints(16)]
[patchconstantfunc("SubDToBezierConstantsHS")]
BEZIER_CONTROL_POINT SubDToBezierHS(InputPatch<VS_CONTROL_POINT_OUTPUT, MAX_POINTS> ip, uint i : SV_OutputControlPointID, uint PatchID : SV_PrimitiveID) {
  VS_CONTROL_POINT_OUTPUT vsOutput;

  // Insert code to compute Output here.
  BEZIER_CONTROL_POINT result;
  result.vPosition = vsOutput.vPosition;
  
  return result;
}

// Patch Constant Function
HS_CONSTANT_DATA_OUTPUT SubDToBezierConstantsHS(InputPatch<VS_CONTROL_POINT_OUTPUT, MAX_POINTS> ip, uint PatchID : SV_PrimitiveID) {
  HS_CONSTANT_DATA_OUTPUT Output;
  
  // Must initialize Edges and Inside; otherwise HLSL validation will fail.
  Output.Edges[0]  = 1.0;
  Output.Edges[1]  = 2.0;
  Output.Edges[2]  = 3.0;
  Output.Edges[3]  = 4.0;
  Output.Inside[0] = 5.0;
  Output.Inside[1] = 6.0;
  
  return Output;
}
```

**Comment by ehsannas** [comment] 2017-10-04 19:58
fyi @antiagainst

**Comment by simontaylor81** [comment] 2017-10-29 11:30
Possible duplicate of #167?

**Comment by ehsannas** [comment] 2017-10-30 14:24
Yes, seems to be the same issue!

**Comment by jpporto** [comment] 2017-10-31 17:41
PR #748 should have fixed this.

**Closed by jpporto** 2017-10-31 17:41 UTC

**Comment by ehsannas** [comment] 2017-10-31 20:54
Thank you @jpporto
