### ISSUE TITLE
[SPIR-V] change breaks existing functionality

### ISSUE THREAD

**Issue by artamonovoleg** [microsoft/DirectXShaderCompiler#6118] opened 2023-12-29 17:00 UTC
beaf633eb05b7c07bacda9a00c117858a792996b (Refactor create stage vars (#6059))

Commit breaks SPIR-V codegen with -fvk-support-nonzero-base-instance enabled

Steps to Reproduce:
Compile any shader that uses SV_InstanceID builtin

Expected Behavior:
Shader compiles.

Actual Behavior:
Invalid SPIR-V generated.

```
fatal error: generated SPIR-V is invalid: OpLoad Result Type <id> '14[%uint]' does not match Pointer <id> '3[%gl_BaseInstance]'s type.
  %41 = OpLoad %uint %gl_BaseInstance
```

**Comment by s-perron** [comment] 2024-01-02 19:09
Thanks for reporting the regression. The issue is that gl_BaseIntance is not created with the correct type. Here is a link that shows the problem: https://godbolt.org/z/cWWPcoYn4.

**Comment by artamonovoleg** [comment] 2024-01-03 17:56
Thanks! I'll close this issue then.

**Comment by s-perron** [comment] 2024-01-03 17:58
We should wait for the PR to be merged before closing.

**Closed** 2024-01-03 21:12 UTC
Labels: bug, spirv
