### ISSUE TITLE
Template specialization does not work for  "out" or "inout" struct parameters

### ISSUE THREAD

**Issue by xander890** [microsoft/DirectXShaderCompiler#5195] opened 2023-05-09 13:06 UTC
As for title, minimal example (https://godbolt.org/z/q1Wf9nvT3)

```hlsl
struct PSInput
{
    float4 position : SV_Position;
};

struct Stuff
{
    float4 color;
};

template<typename T>
void increment(inout T X) { // <--- the inout marker here seems to cause the issue
}

template<>
void increment(inout Stuff X) {
  X.color.x += 1.0;
}

float4 PSMain(PSInput input) : SV_Target0
{
    Stuff x;
    x.color = 0;
    increment(x);
    return x.color;
}
```

Compiler flags:  `-T ps_6_6 -E PSMain -O3 -HV 2021`
This gives the following error:

```
<source>:19:6: error: no function template matches function template specialization 'increment'
void increment(inout Stuff X) {
     ^
<source>:15:6: note: candidate template ignored: could not match 'type-parameter-0-0 &' against 'Stuff'
void increment(inout T X) {
     ^
Compiler returned: 5
```
As far as the documentation goes, this should work. If I use the "in" marker, or I use a built-in type in the specialization (e.g. float3), the shader compiles correctly.

Is this expected behavior or a bug? The HLSL 2021 post https://devblogs.microsoft.com/directx/announcing-hlsl-2021/ implies that partial template specializations can be used with inout.

**Comment by llvm-beanz** [comment] 2023-06-30 15:38
This is caused by #5377, which I've been working on sorting out.

Because we don't accurately represent `out` and `inout` parameters in the AST they don't get correctly replicated during template instantiation.

I have verified that this test works correctly in my development branch. There is a draft PR in #5249, which contains the fix, but still has some other tests failing which need to be resolved before I can merge the PR.

Please follow #5377 for updates on when this will be merged.

**Closed by llvm-beanz** 2023-06-30 15:38 UTC
Labels: bug, hlsl2021
