### ISSUE TITLE
[SPIRV] Partial template specialization

### ISSUE THREAD

**Issue by atkurtul** [microsoft/DirectXShaderCompiler#5826] opened 2023-10-04 11:57 UTC
**Description**
[trying to instantiate partial template specialization](https://godbolt.org/z/fKo8ahax9) confuses DXC

**Steps to Reproduce**
try to compile the following snippet of code with flags:
`-spirv -HV 202x -T ps_6_7 -enable-16bit-types -fvk-use-scalar-layout -fspv-debug=source -fspv-debug=tool `
```cpp
template<uint64_t N, uint16_t bits_log2>
struct clz
{
    static const uint64_t SHIFT = 1ull<<(bits_log2-1);
    static const uint64_t LO_MASK = (1ull<<SHIFT)-1;
    static const bool CHOOSE_HIGH = N&(LO_MASK<<SHIFT);
    static const uint64_t value   = clz<(CHOOSE_HIGH ? (N>>SHIFT):N)&LO_MASK,bits_log2-1>::value + (CHOOSE_HIGH ? 0ull:SHIFT);
};

template<uint64_t N>
struct clz<N, 0>
{
    static const uint64_t value = 1 - (N & 1);
};


float main() : SV_TARGET
{
    return clz<16, 4>::value;
}
```

**Actual Behavior**
fails to compile with the following message
```
<source>:10:19: fatal error: found unregistered decl
template<uint64_t N>
                  ^
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

Compiler returned: 5
```

**Environment**
- DXC version : libdxcompiler.so: 1.7(dev;1-e5ce1714)
- Host Operating System: godbolt

**Comment by devshgraphicsprogramming** [comment] 2023-10-04 12:03
Removing `-spirv` makes it compile, so I guess another SPIR-V out bug?

**Comment by llvm-beanz** [comment] 2023-10-05 15:36
I _strongly_ recommend not passing `-HV 202x`. At present the HLSL 202x language mode should be identical to the HLSL 2021 mode, but as features get added to that mode it will be unstable.

"202x" is the placeholder version string for the next language version and it hasn't been fully defined, but it will almost certainly have some amount of breaking changes that will go through a few iterations of development before being finalized.

**Comment by devshgraphicsprogramming** [comment] 2023-10-05 18:05
> I _strongly_ recommend not passing `-HV 202x`. At present the HLSL 202x language mode should be identical to the HLSL 2021 mode, but as features get added to that mode it will be unstable.
> 
> "202x" is the placeholder version string for the next language version and it hasn't been fully defined, but it will almost certainly have some amount of breaking changes that will go through a few iterations of development before being finalized.

we'll make sure to test with `-HV 2021` on future bug reports

**Comment by devshgraphicsprogramming** [comment] 2023-10-06 11:36
ok it still breaks with `-HV 2021`

**Comment by sudonatalie** [comment] 2023-10-17 18:31
Closing as duplicate of #5563

**Closed by sudonatalie** 2023-10-17 18:31 UTC
Labels: bug, spirv, hlsl2021, needs-triage
