### ISSUE TITLE
Random crash when compiling shaders 

### ISSUE THREAD

**Issue by gjaegy** [microsoft/DirectXShaderCompiler#5566] opened 2023-08-18 14:18 UTC
**Description**
We experience some random crash (i.e. doesn't occur every time) when compiling our shaders. The shaders are being compiled in a multithreaded context (i.e. multiple threads compiling simultaneously, each thread compiling one shader using one different dxc compiler instance).

**Steps to Reproduce**
We have no idea how to reproduce the issue I'm afraid. It occurs randomly. And sometimes it doesn't occur.

We compile using the following options:
-spirv
-fspv-target-env=vulkan1.1
-Wall
-Wno-unused-const-variable
-fspv-extension=SPV_EXT_descriptor_indexing
-fspv-extension=SPV_KHR_non_semantic_info
-fspv-debug=vulkan-with-source

**Actual Behavior**
See attached screenshot showing the exact crash location. The crash occurs randomly, meaning it sometimes doesn't occur, but when it occurs, it always occurs at the same location.

**Environment**
- DXC version 1.7.2308
- Host Operating System Windows 11

<img width="1306" alt="image" src="https://github.com/microsoft/DirectXShaderCompiler/assets/900305/588a495b-73f5-47ac-b814-12cf3bdc4fd8">

**Comment by sudonatalie** [comment] 2023-08-22 14:27
Are you able to provide the shaders that result in the crash? Without being able to reproduce it it's probably not going to be feasible for us to identify a fix. Alternatively, you could compile with a [debug build of DXC](https://github.com/microsoft/DirectXShaderCompiler#building-sources) and you should hit an assertion at the point that the nullptr is added to `debugInstructions`. With a call stack from that point in execution it's more likely we could identify the issue without repro shaders.

**Comment by sudonatalie** [comment] 2023-09-07 16:23
Without additional repro steps this isn't an issue we can likely fix. Closing this issue for now but we'd be happy to re-open it if the information requested above is added in a comment.

**Comment by gjaegy** [comment] 2023-09-11 07:03
I haven't been able to reproduce the issue using a debug build until now. It seems it doesn't happen. I will let you know if that changes... Possibly a concurrency issue ?

**Comment by gjaegy** [comment] 2023-09-12 13:24
Unfortunately, the crash doesn't occur when using a debug build of the library. I've tried dozen of times but each of these runs went through flawlessly. No crash.

As a reminder, I can't reproduce the bug either when compiling our shaders in a single thread. Only when compiling simultaneously using multiple threads (one compiler by thread).

Since the crash is not reproducible every time, and nevers occurs when compiling the shaders in a single thread, I tend to think it could be down to a concurrency issue. However, I don't know the code so that's just an assumption.

Looking at the code, I can't see how a NULL instruction could be added to the list. To me, it can occur in the case the allocation fails (new (contect) ....) and that's pretty much all. But I haven't been able to figure out if that's the case. I assume the allocator is thread-safe, isn't it ?

**Comment by sudonatalie** [comment] 2023-09-14 14:05
Reopening for us to take another look into this.

**Comment by Keenuts** [comment] 2023-09-15 12:00
Hi!

Thanks for the report!
I'd need a bit more info to look into that:

You mention the build is multithread, how so? The DXC's executable is not multi-threaded, so each external invocation being its own process we should be fairly safe (unless that's a file read/write race condition leading to some weird bug).

- How do you run each DXC invocation? Is it through a build-system, hence multiple processes, or are you using the libdxcompiler.dll directly thus have really multiple threads you manage yourself?
- What file are you reading/writing to?
- Is it always the same shader compilation crashing, or a random one in the list you compile?
- Could you provide the full callstack in case of a crash?

The screen you have shows you have debug information attached to the line, are you using the binary and PDB file from the release page to get this?

Were you able to reproduce this bug with a custom compilation of DXC (release mode)?
If so, but you cannot build using assert, could you add the following line in `SpirvModule.cpp` in the `addDebugInfo` function to get the stacktrace when we add null?
```diff
void SpirvModule::addDebugInfo(SpirvDebugInstruction *info) {
+ if (info == nullptr) { *((volatile int*)1) = 0xCAFE; }
- assert(info);
  debugInstructions.push_back(info);
}
```

Thanks,

Nathan

**Comment by Keenuts** [comment] 2023-09-15 12:31
If you use `libdxcompiler.so` directly through the API, and handle multithreading by yourself, maybe 2 thread running the `WrapCompile` function?
If that happens, it could explain the `nullptr`:
 -> when the compiler if finished with a file, it released the `SpirvContext`, which contains referenced to debug info. This calls `debugType->releaseMemory()`. But if another thread was still processing that list, it could end-up adding a debug info.

I'm not 100% sure — but almost — that none of the DXC's API functions are thread-safe. Because of those global states. If you handle threading like that, I'd suggest going the fork way.

**Comment by TLaviron** [comment] 2023-09-18 11:11
Hi,

Replying on behalf of @gjaegy since he is away for the week.

> * How do you run each DXC invocation? Is it through a build-system, hence multiple processes, or are you using the libdxcompiler.dll directly thus have really multiple threads you manage yourself?

We're using the shared library API as described in [the Wiki](https://github.com/microsoft/DirectXShaderCompiler/wiki/Using-dxc.exe-and-dxcompiler.dll#dxcompiler-dll-interface)

We're creating one `IDxcCompiler3` and one `IDxcLibrary` for each thread that compiles shaders. These are created through calls to `DxcCreateInstance` which happen to be mutex-protected (according to the docs, calls to `DxcCreateInstance` are thread safe; the mutex is here to protect the data structure that stores the threadID->compiler instance mappings).
Compile jobs run in a thread pool using as many threads as there are physical threads on the machine; each job uses the compiler instance for the thread it's running on.

> NOTE: The call to DxcCreateInstance is thread-safe, but objects created by DxcCreateInstance aren't thread-safe. Compiler objects should be created and then used on the same thread.

I've interpreted this part of the docs as meaning we should create different compiler objects to compile shaders in parallel, assuming that distinct compiler objects don't interfere with each other.
Obviously if the library has global, mutable state accessed by every compiler instance then this won't work.

> * What file are you reading/writing to?

We don't do any file I/O through dxcompiler, source code is loaded into memory (being loaded from disk first, with some files possibly shared between shaders) and get the compiled SPIR-V from memory (optionally saving it to disk for caching, though this is not done in the configuration where we see bugs).

> * Is it always the same shader compilation crashing, or a random one in the list you compile?

Not 100% sure, but I think this is random.

> * Could you provide the full callstack in case of a crash?

The screen above shows every stack frame from `dxcompiler.dll` I believe. Below that should be only our code / system code
We could add the complete stack frame if you think ot would be useful. We could also add stack frames of concurrent threads if this could help.

> The screen you have shows you have debug information attached to the line, are you using the binary and PDB file from the release page to get this?

We build dxc locally, currently using tagged version 1.7.2308 (commit hash 69e54e29086b7035acffb304cec57a350225f8b0)
 
> Were you able to reproduce this bug with a custom compilation of DXC (release mode)? If so, but you cannot build using assert, could you add the following line in `SpirvModule.cpp` in the `addDebugInfo` function to get the stacktrace when we add null?

We'll try this, and let you know what we find.

An additional note: we only observed bugs on higher core count machines (16c/32t); lower core count machines (8c/8t, 8c/16t) never exhibited the issue.

**Comment by TLaviron** [comment] 2023-09-21 14:21
Hi, I have new information to share,

First, the change in `SpirvModule::addDebugInfo()` yielded no results; the test for the forced error was never true, even when a crash occured.

Second, while the crash is not limited to a single shader, it seems to be that only a subset of all our shaders are prone to crashing the compiler.

Third, while the crash always happen at the same location, the faulty pointer can hve different values: sometimes its `nullptr`, somtimes its `UINT64_MAX`, sometimes its something completely different, like the capture below:
![image](https://github.com/microsoft/DirectXShaderCompiler/assets/19927604/387c8fcc-f2d9-42b6-a192-f92fd8755cf9)

I've examined the contents of the `debugInstructions` vector, using the values of `BeginX` and `EndX`, but the faulty pointer values never appeared in it in any of the crashes; they all looked to be valid pointers to `clang::spirv::SpirvDebugInstruction`.
However, I have noticed that the loop variables `<begin>$L11` and `<end>$L11` don't match with the current vector extents.
Could it be that the visitor invocation inserts new debug instructions into the vector, causing a reallocation and invalidating the iterators used by the loop?

This would be consistent with the observations so far. In the cases where there is no crash, it could simply be because the discarded vector memory hasn't been overwritten yet, and the crash could happen as a result of another thread compiling another shader, for which the memory allocator (which i assume is both shared and thread-safe) returns the memory block that the first thread still has dangling references to.

**Comment by gjaegy** [comment] 2023-10-02 14:36
Hi, 
It seems Thierry's findings are quite relevant here, in my opinion, and could explaing the issue. 
Has anyone managed to check wether any insertion in the vector is indeed being made while looping over the container ?
Thanks for any information !

**Comment by Keenuts** [comment] 2023-10-02 14:56
Hi!

Thanks @TLaviron for the details!
But no, I haven't had time to check back on this issue yet, but it should give me more info to try to root cause the issue.

**Comment by gjaegy** [comment] 2023-10-13 08:26
Hi Nathan, do we have any update on that one ? 
Sorry for harassing you ;)

**Comment by Keenuts** [comment] 2023-10-19 07:50
Hi @gjaegy! No worries, if I don't answer, you definitely have the right to ping me 😊
Booking my morning to look into that now.

**Comment by gjaegy** [comment] 2023-10-19 08:03
Cool, thanks for that Nathan ;)

**Comment by Keenuts** [comment] 2023-10-25 13:23
Hello again!
Sorry this took a bit more time than expected.
The PR I just sent in will unblock you, but I wanted to be able to automatically find this bug so I could check if we had the same pattern all around the code.

Now that I am able to track similar issues automatically, I'll be fixing them one by one.
But on your end, you should now be unblocked.

note: I noticed we also have another big concurrency issue around unicode: we call setlocale()   in many places when building. This means your threads could end-up calling setlocale concurrently. So far I haven't noticed issues on my compilations, but just in case this comes up on your end.
Fixing this particular concurrency issue might not be trivial, I need to think about it.

**Comment by gjaegy** [comment] 2023-11-08 09:08
Hi Nathan,
Thanks a lot for that, we really appreciate it. I've just compiled a version we were using (1.7.2308 release) that has your two commits merged.
We'll test and let you know the results, looking at your commits, I'm pretty confident it will solve our specific issue !

**Comment by gjaegy** [comment] 2023-11-08 09:09
Regarding the setlocale() call, is it called frequently during the compilation of one single shader ? Would a simple mutex-based protection around that call solve the issue ?

**Comment by gjaegy** [comment] 2023-11-13 09:07
Hi, it seems the fix indeed fix our issue, thanks for that !

**Closed** 2023-11-13 12:58 UTC
Labels: bug, spirv

**Comment by xOrfe** [comment] 2025-04-03 04:36
While researching to write a test software to detect CPUs with permanent damage due to a faulty microcode in the 13th and 14th generation Intel CPUs, I came across this topic. If you are using a 13th or 14th generation Intel CPU, this could be the cause of the issue. This problem occurs in p-cores under heavy load (usually during shader compilation).
