### ISSUE TITLE
use of unrecognized compiler options with slash (not dash) breaks dx.source.* info

### ISSUE THREAD

**Issue by jeffnn** [microsoft/DirectXShaderCompiler#3515] opened 2021-02-26 19:44 UTC
In my case, I had some older code that passed /enable_unbounded_descriptor_tables. 
Look what happens to the source info when this (older, now unrecognized) argument is specified:
Metadata !0 should have the source filename as its first entry, not this unrecognized flag.

```
!dx.source.contents = !{!0}
!dx.source.defines = !{!1}
!dx.source.mainFileName = !{!2}
!dx.source.args = !{!3}
!dx.version = !{!4}
!dx.shaderModel = !{!5}
!dx.entryPoints = !{!6}

!0 = !{!"\5Cenable_unbounded_descriptor_tables", !"//*********************************************************\0D\0A//\0D\0A// Copyright (c) Microsoft. .. (deleted to fit in the email)
!1 = !{!"ENABLE_16BIT_TYPES=1"}
!2 = !{!"/enable_unbounded_descriptor_tables"}
!3 = !{!"MeshShaders\5CMeshShaders.hlsl", !"-E", !"ASMain", !"-T", !"as_6_5", !"-enable-16bit-types", !"/Od", !"/Zi", !"-D", !"ENABLE_16BIT_TYPES=1", !"-Qembed_debug"}

```
If I pass -enable_unbounded_descriptor_tables (with a – instead of a /), then I get an expected error.

**Comment by bob80905** [comment] 2022-01-04 19:48
Because /enable_unbounded_descriptor_tables is an unrecognized argument, the parser can only assume it is the input file because no other input file was specified, and it starts with a "/". This is expected behavior. I will close this bug by design.

**Closed by bob80905** 2022-01-04 19:48 UTC
