### ISSUE TITLE
Clang crash with specific shader

### ISSUE THREAD

**Issue by turanszkij** [Microsoft/DirectXShaderCompiler#1091] opened 2018-02-23 11:44 UTC
Hello, I have a compute shader that crashes the compiler without any information as to why. I couldn't investigate further yet, but I will provide a case to reproduce.

The attached zip contains shader files:
[clang_crash.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/1751500/clang_crash.zip)

I am trying to compile like this:

`dxc lightCullingCS.hlsl -T cs_6_0 -flegacy-macro-expansion`

**Comment by turanszkij** [comment] 2018-02-23 16:02
Turns out the compiler crash can be triggered if I have a structure member function to fill out its data and I call it on a groupshared object. Consider this:

```
struct AABB
{
	float3 c; // center
	float3 e; // half extents

        void fromMinMax(float3 _min, float3 _max)
	{
		c = (_min + _max) * 0.5f;
		e = abs(_max - c);
	}
};
```

and I use it like this:

```
groupshared AABB myAABB;
// ...
myAABB.fromMinMax(myMin, myMax)
```

Whereas if I declare a function outside the struct like this:

```
void AABBfromMinMax(inout AABB aabb, float3 _min, float3 _max)
{
	aabb.c = (_min + _max) * 0.5f;
	aabb.e = abs(_max - aabb.c);
}
```

I can call it without the compiler crashing. I haven't got a chance yet to debug the compiler itself, and while this crash can be worked around, I'll leave this issue here for the time being.

**Comment by python3kgae** [comment] 2018-02-27 03:05
Thanks for the feedback.
The crash is caused by not support addrspacecast when flatten global varaible.
Working on a fix.

**Comment by python3kgae** [comment] 2018-02-28 01:17
Fixed with https://github.com/Microsoft/DirectXShaderCompiler/pull/1103

Thanks
Xiang

**Closed** 2018-03-26 16:56 UTC
