### ISSUE TITLE
Operator *= for array elements does not work

### ISSUE THREAD

**Issue by seppala2** [Microsoft/DirectXShaderCompiler#909] opened 2017-12-12 10:10 UTC
When optimization is disabled, the following example will produce red, even though the result should be almost black:

```
float4 PS(in float4 pos : SV_Position) : SV_Target0
{
    float x = 1.0f;

    #if 1
    {
        float values[2];
        values[0] = x;
        values[1] = 0.0f;

        values[0] *= 0.01f;

        return float4(values[0], 0.f, 0.f, 1.f);
    }
    #else
    {
        // This should give the same result as above
        float value = x;
        value *= 0.01f;
        return float4(value, 0.f, 0.f, 1.f);
    }
    #endif
}
```

I tested this with the flags -Ges -O0 -WX -Zi

With the flags -Ges -O3 -WX -Zi (optimization enabled) the result is correct for this example. Also multiplying by 0 instead of 0.01 will not reproduce this bug.

**Comment by python3kgae** [comment] 2017-12-13 20:48
The dxil output looks fine.

  %x = alloca float, align 4
  %values = alloca [2 x float], align 4
 ;  x = 1.0f
  store float 1.000000e+00, float* %x, align 4, !dbg !51
  %9 = load float, float* %x, align 4, !dbg !58
  %arrayidx = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 0, !dbg !59
  ; values[0] = x
  store float %9, float* %arrayidx, align 4, !dbg !60
  %arrayidx1 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 1, !dbg !61
  ; values[1] = 0
  store float 0.000000e+00, float* %arrayidx1, align 4, !dbg !62
  %arrayidx2 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 0, !dbg !63
  %10 = load float, float* %arrayidx2, align 4, !dbg !64
  ; values[0] * 0.01.
  %mul = fmul fast float %10, 0x3F847AE140000000, !dbg !64
  ;  values[0] = %mul
  store float %mul, float* %arrayidx2, align 4, !dbg !64

  %arrayidx3 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 0, !dbg !65
  %11 = load float, float* %arrayidx3, align 4, !dbg !65
  ; return values[0] as x channel.
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %11), !dbg !66  

Could you share the GPU and driver version you're using?

**Comment by ehsannas** [comment] 2017-12-13 21:51
@seppala2 , are you looking at DXIL or SPIR-V?

The SPIR-V output seems reasonable too.

**Comment by seppala2** [comment] 2017-12-14 07:35
@ehsannas this actually happens only with DXIL when optimization is disabled, SPIR-V seems to work fine with and without optimization.

@python3kgae I am running AMD Radeon RX Vega 64 with driver version 23.20.15002.11

I also checked that using `values[0] = values[0] * 0.01f` produces the correct result although the resulting DXIL is almost identical (only the getelementptr instruction is duplicated in the second example) :

DXIL with the original shader (using values[0] *= 0.01f):
```
define void @PS() {
  %1 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 0, i32 undef), !dbg !48  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %2 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 1, i32 undef), !dbg !48  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %3 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 2, i32 undef), !dbg !48  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %4 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 3, i32 undef), !dbg !48  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %5 = alloca [4 x float]
  %x = alloca float, align 4
  %values = alloca [2 x float], align 4
  %6 = getelementptr inbounds [4 x float], [4 x float]* %5, i32 0, i32 0
  store float %1, float* %6
  %7 = getelementptr inbounds [4 x float], [4 x float]* %5, i32 0, i32 1
  store float %2, float* %7
  %8 = getelementptr inbounds [4 x float], [4 x float]* %5, i32 0, i32 2
  store float %3, float* %8
  %9 = getelementptr inbounds [4 x float], [4 x float]* %5, i32 0, i32 3
  store float %4, float* %9
  call void @llvm.dbg.declare(metadata float* %x, metadata !49, metadata !50), !dbg !51
  store float 1.000000e+00, float* %x, align 4, !dbg !51
  call void @llvm.dbg.declare(metadata [2 x float]* %values, metadata !52, metadata !50), !dbg !57
  %10 = load float, float* %x, align 4, !dbg !58
  %11 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 0, !dbg !59
  store float %10, float* %11, align 4, !dbg !60
  %12 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 1, !dbg !61
  store float 0.000000e+00, float* %12, align 4, !dbg !62
  %13 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 0, !dbg !63
  %14 = load float, float* %13, align 4, !dbg !64
  %15 = fmul fast float %14, 0x3F847AE140000000, !dbg !64
  store float %15, float* %13, align 4, !dbg !64
  %16 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 0, !dbg !65
  %17 = load float, float* %16, align 4, !dbg !65
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %17), !dbg !66  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 1, float 0.000000e+00), !dbg !66  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 2, float 0.000000e+00), !dbg !66  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 3, float 1.000000e+00), !dbg !66  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void, !dbg !66
}
```

DXIL with changing the multiplication to `values[0] = values[0] * 0.01f`:
```
define void @PS() {
  %1 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 0, i32 undef), !dbg !48  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %2 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 1, i32 undef), !dbg !48  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %3 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 2, i32 undef), !dbg !48  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %4 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 3, i32 undef), !dbg !48  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %5 = alloca [4 x float]
  %x = alloca float, align 4
  %values = alloca [2 x float], align 4
  %6 = getelementptr inbounds [4 x float], [4 x float]* %5, i32 0, i32 0
  store float %1, float* %6
  %7 = getelementptr inbounds [4 x float], [4 x float]* %5, i32 0, i32 1
  store float %2, float* %7
  %8 = getelementptr inbounds [4 x float], [4 x float]* %5, i32 0, i32 2
  store float %3, float* %8
  %9 = getelementptr inbounds [4 x float], [4 x float]* %5, i32 0, i32 3
  store float %4, float* %9
  call void @llvm.dbg.declare(metadata float* %x, metadata !49, metadata !50), !dbg !51
  store float 1.000000e+00, float* %x, align 4, !dbg !51
  call void @llvm.dbg.declare(metadata [2 x float]* %values, metadata !52, metadata !50), !dbg !57
  %10 = load float, float* %x, align 4, !dbg !58
  %11 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 0, !dbg !59
  store float %10, float* %11, align 4, !dbg !60
  %12 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 1, !dbg !61
  store float 0.000000e+00, float* %12, align 4, !dbg !62
  %13 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 0, !dbg !63
  %14 = load float, float* %13, align 4, !dbg !63
  %15 = fmul fast float %14, 0x3F847AE140000000, !dbg !64
  %16 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 0, !dbg !65
  store float %15, float* %16, align 4, !dbg !66
  %17 = getelementptr inbounds [2 x float], [2 x float]* %values, i32 0, i32 0, !dbg !67
  %18 = load float, float* %17, align 4, !dbg !67
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %18), !dbg !68  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 1, float 0.000000e+00), !dbg !68  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 2, float 0.000000e+00), !dbg !68  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 3, float 1.000000e+00), !dbg !68  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void, !dbg !68
}
```

This bytecode produces the correct result on the RX Vega but the first one does not

**Comment by markherdeg** [comment] 2017-12-15 20:13
The driver version you gave is really just the OpenCL version, but are you using the current Radeon Software version 17.12.1?

This shader compiled to correct looking AMD code for me. In fact, both variants optimize to the same constant move in the final GPU ISA code.

I did notice one problem with the debugger intrinsics being present in the DXIL, so can you try it without -Zi just to make sure that isn't involved?

**Comment by seppala2** [comment] 2017-12-18 09:36
I just noticed that the test application was actually using WARP. With the normal adapter this issue does not show up.

So this seems to be an issue in WARP instead of the GPU drivers. My Windows version is 10.0.16294.1 with Graphics Tools installed.

**Comment by python3kgae** [comment] 2017-12-19 19:57
Hi @seppala2,
Thanks for the feedback, WARP team has found the root cause and will fix it today.
But WARP is part of Windows:(  It will be an early 2018 release which has the fix.
Sorry for the inconvience.

Thanks
Xiang

**Comment by hekota** [comment] 2018-05-15 23:13
This should be fixed in the Windows 10 April 2018 update. Feel free to reopen if that's not the case.

**Closed by hekota** 2018-05-15 23:13 UTC
Labels: bug, external
