### ISSUE TITLE
[SPIR-V] Invalid SPIR-V generated with -fpsv-debug=vulkan-with-source

### ISSUE THREAD

**Issue by TLaviron** [microsoft/DirectXShaderCompiler#4767] opened 2022-11-04 15:59 UTC
The following shader causes a fatal error when compiled with SPIR-V debug info:

```hlsl
struct VertexOutput
{
	float4 Position : POSITION;
	float2 Data : TEXCOORD0;
};

void Foo(out float x)
{
	x = 1.0;
}

VertexOutput mainvert()
{
	VertexOutput OUT;
	OUT.Position = float4 (0.0, 0.0, 0.0, 1.0);
	OUT.Data.x = 0;
	Foo(OUT.Data.y);
	
	return OUT;
}

```
Compiling this shader with `dxc.exe test.hlsl -E mainvert -T vs_6_0 -spirv -fspv-target-env=vulkan1.1 -fspv-extension=SPV_KHR_non_semantic_info -fspv-debug=vulkan-with-source -Fo test.vert.spv` causes a fatal error:
```
fatal error: generated SPIR-V is invalid: NonSemantic.Shader.DebugInfo.100 DebugDeclare: expected operand Variable must be a result id of OpVariable or OpFunctionParameter
  %96 = OpExtInst %void %1 DebugDeclare %35 %94 %19
```

This can be worked around by using a local variable of the same type as the output parameter, like so:
```hlsl
    // Foo(OUT.Data.y);
    float tmp;
    Foo(tmp);
    OUT.Data.y = tmp;
```

**Comment by cassiebeckley** [comment] 2022-11-04 21:38
Thanks for reporting this issue!

**Comment by s-perron** [comment] 2023-07-24 14:35
Looks like a duplicate of #5191

**Closed by s-perron** 2023-07-24 14:35 UTC
Labels: spirv
