### ISSUE TITLE
Resources not culled if usage impossible due to min

### ISSUE THREAD

**Issue by simontaylor81** [microsoft/DirectXShaderCompiler#2563] opened 2019-10-31 10:43 UTC
(Possibly related to #2446.)

Bit tricky to explain this one, hope this makes sense! If you have a shader that conditionally references a cbuffer, but it turns out that it is impossible to actually reference the constant because of a `min` operation with a constant, then in FXC the cbuffer would be considered unreferenced, but in DXC it is still referenced.

Hopefully an example will clear things up! I made the cbuffers have overlapping register assignments to the problem is obvious. Compile with `-E main -T ps_6_0`. This will work fine in FXC, but DXC will fail (with `resource cb1 at register 0 overlaps with resource cb0 at register 0, space 0`).

```
cbuffer cb0 : register(b0)
{
	float4 g_param;
}

cbuffer cb1 : register(b0)
{
	const int g_mode;
}

float4 main() : SV_Target0
{
  	uint mode = min(0, g_mode);
	if (mode == 1)
		return g_param;
	return 0;
}
```

**Comment by simontaylor81** [comment] 2019-10-31 10:47
I should add that the real case we hit this is more complicated, it isn't just 0 or 1 that it's selecting over (it's 0 to 5, I believe). This is just the simplest repro case I could come up with.

**Comment by pow2clk** [comment] 2020-08-16 06:25
This is a duplicate of #2415 which we just closed as won't fix.

**Closed by pow2clk** 2020-08-16 06:25 UTC

**Comment by simontaylor81** [comment] 2020-08-24 14:42
Why is this won't fix? This is a clear regression from fxc. This isn't harmless, it will require us to bind additional resources at runtime, possibly stream them in, etc.

**Comment by pow2clk** [comment] 2020-09-25 13:19
Apologies for the delayed response. FXC was inconsistent with and more aggressive at resource culling than was intended. That's why we are unwilling to propagate that inconsistent aggression to DXC.

We have designs to add support for constexpr or something similar which should help in these scenarios, but I'm afraid that's not a short term project either.
