### ISSUE TITLE
out semantic requires paramater to be initalized before call, which is weird

### ISSUE THREAD

**Issue by otanter-at-ubi** [microsoft/DirectXShaderCompiler#2538] opened 2019-10-21 15:10 UTC
[dxc_warn.txt](https://github.com/microsoft/DirectXShaderCompiler/files/3754241/dxc_warn.txt)
Hi,

Basically we get this warning on any out parameter:

	dxc_warn.hlsl:29:13: warning: variable 'inVert' is uninitialized when used here
        loadVertex(inVert, instId * VERTEX_STRIDE);
                   ^~~~~~
	dxc_warn.hlsl:28:15: note: initialize the variable 'inVert' to silence this warning
			Vertex inVert;

Of course, said paramater is fully initialized in the called function (loadVertex here).

See attached file for a full example: [dxc_warn.txt](https://github.com/microsoft/DirectXShaderCompiler/files/3754242/dxc_warn.txt)

Also may be related to https://github.com/microsoft/DirectXShaderCompiler/issues/1186

Cheers,
Olivier

edit: fixed typo in sample.

**Comment by tex3d** [comment] 2019-10-25 00:24
Duplicate of #2494.

**Comment by tex3d** [comment] 2019-10-25 00:25
Thanks for the repro, but we'll close this issue, as we already have another issue tracking it.

**Closed by tex3d** 2019-10-25 00:25 UTC
Labels: bug
