### ISSUE TITLE
DispatchMesh accepts on groupshared payload param without warning/error

### ISSUE THREAD

**Issue by joeldevahl** [microsoft/DirectXShaderCompiler#3332] opened 2020-12-29 12:27 UTC
When implementing a mesh shader test I hit the potential issue where DXC silently accepts a non group shared parameter as payload. This does not work since the spec says that the payload has to be in group shared memory. Writing code like this
```
struct Payload
{
	float3 offset;
};
[NumThreads(1, 1, 1)]
void main()
{
	Payload meshletPayload;
	meshletPayload.offset = float3(0.0f, 0.0f, -10.0f);
	DispatchMesh(1, 1, 1, meshletPayload);
}
```
Will compile but not work at runtime. Throwing an error here would be appreciated.

Also, the tests in DXC does use this pattern which is even more confusing.

https://github.com/microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenHLSL/mesh-val/amplification.hlsl

**Comment by pow2clk** [comment] 2021-02-08 19:17
Hi @joeldevahl!

Thanks for the bug report. However, I think this is the result of a misreading of the spec. It's understandable as it's a bit ambiguous and it took me a few internal conversations to work out what was intended.

I suspect you are referring to this section https://microsoft.github.io/DirectX-Specs/d3d/MeshShader.html#dispatchmesh-intrinsic

probably specifically this prototype:

```c++
template <typename payload_t>
DispatchMesh(uint ThreadGroupCountX,
             uint ThreadGroupCountY,
             uint ThreadGroupCountZ,
             groupshared payload_t MeshPayload);
```

The `groupshared` on the payload parameter doesn't mean that the variable provided to that parameter has to be groupshared. Rather, similar to a `const` qualified parameter, it means that whatever is passed into this variable will be copied into a groupshared variable, which is why the size of it counts against the groupshared limits.

The prospect of a non-groupshared variable is explicitly addressed a bit further down where it reads, "The arguments are treated as uniform for the group, meaning that they are read from the first thread if not group-uniform (or groupshared)."

As a result, the code you provided is valid. I'll see about clarifying the spec language, but I'm closing this issue.

**Closed by pow2clk** 2021-02-08 19:17 UTC
