### ISSUE TITLE
No clear header and lib deployment + no header in windows sdk

### ISSUE THREAD

**Issue by galop1n** [Microsoft/DirectXShaderCompiler#1132] opened 2018-03-12 18:00 UTC
Hi,

Right now, it is unclear of what is the set of headers and lib a deployed version of a dxc build should contain as we do not want to pollute or source control with hundreds of LLVM stuff.

Right now, i pull from the folders, the 4 headers below but i imagine it may need a few others depending on future needs. These are enough to compile and do some basic manipulation of the DXIL container ( part kind enum, etc ) :
dxcapi.h
HLSL/DXilCompType.h
HLSL/DxilConstants.h
HLSL/DxilContainer.h

It is worth to say that the current windows 10 sdk is also missing any of these files, and only contains dxc.exe and the proxy DLL to hijack the old compiler.

Ideally, we should only need a single header/library like we use to with d3dcompiler.h

**Comment by marcelolr** [comment] 2018-03-12 18:09
Hehe, I just filed #1131 for this. I was thinking of only including enough to call into dxcompiler, not the container functionality though.

You should be able to do most (all?) of the container manipulation via APIs in any case - is there something missing from our API surface for that?

**Comment by galop1n** [comment] 2018-03-12 18:50
dxcapi.h has what it needs to manipulate the container, but dxilcontainer.h has the enums and constants. The other two headers are dependencies ( dxilcomptype.h is not a dependency anymore on the latest revision )

The elements that are mandatory to work on a dxil container are :
* DxilFourCC to recognize the part types
* All the ShaderFeatureInfo_ to figure uses in the shader ( to validate match at runtime against D3D12_OPTIONSX members )

In the future, when things like DFCC_ShaderStatistics are implemented, or if something cannot be transposed back to an ID3D12ShaderReflection object, we may have to parse deeper ourself in the DXIL container part and need other declarations, but for the moment, nothing more is needed.

**Comment by hekota** [comment] 2018-05-15 23:03
Duplicate of #1131.

**Closed by hekota** 2018-05-15 23:03 UTC
