### ISSUE TITLE
Either Support AST Merging or linking of SPIR-V

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/DirectXShaderCompiler#4779] opened 2022-11-09 12:43 UTC
Right now I can't link `lib_6_x` target with some other target because `lib_6_x` cannot be emitted to SPIR-V because SPIR-V doesn't support linking for any target environment except OpenCL (this is an issue of SPIR-V Tools not DXC really).

I was a bit surprised that SPIR-V is generated from the AST directly instead of DXIL, I guess there are reasons for that. It just seems weird not to use the Intermediate Langauge when its there, I hope the LLVM support of HLSL will also translate into LLVM IR support of SPIR-V not only DXIL so we can avoid this mess in the future.

So there remains the last and only option, theoretically I could forward declare all my `export` functions and literally just "glue" my parsed ASTs together much how I'd do for a unity build done via pasting the sources together.

Is there a way to do it, and will I gain much in terms of compile time vs. unity build?

**Comment by vettoreldaniele** [comment] 2022-11-15 15:38
Duplicate of #2633.

**Closed** 2022-11-15 15:39 UTC
