### ISSUE TITLE
[SPIRV] Useless copy of all VtxInput elements

### ISSUE THREAD

**Issue by GregSlazinski** [microsoft/DirectXShaderCompiler#2381] opened 2019-07-29 11:25 UTC
I have this shader:
```
#define Bool     bool
#define Int      int
#define UInt     uint
#define Flt      float
#define VecI2    int2
#define VecI     int3
#define VecI4    int4
#define VecU2    uint2
#define VecU     uint3
#define VecU4    uint4
#define Vec2     float2
#define Vec      float3
#define Vec4     float4

   #define Half     min16float
   #define VecH2    min16float2
   #define VecH     min16float3
   #define VecH4    min16float4
   #define MatrixH3 min16float3x3
   #define MatrixH  min16float4x3
   #define MatrixH4 min16float4x4

struct VtxInput // Vertex Input, use this class to access vertex data in vertex shaders
{
   Vec4  _pos     :ATTR0 ;
   VecH  _hlp     :ATTR1 ;
   VecH  _nrm     :ATTR2 ;
   VecH4 _tan     :ATTR3 ;
   Vec2  _tex     :ATTR4 ;
   Vec2  _tex1    :ATTR5 ;
   Vec2  _tex2    :ATTR6 ;
   Half  _size    :ATTR7 ;
   Vec4  _bone    :ATTR8 ;
   VecH4 _weight  :ATTR9 ;
   VecH4 _material:ATTR10;
   VecH4 _color   :ATTR11;

   VecH4 color1()
   {
      return VecH4(_color.rgb+1, _color.a);
   }
};
void Draw2DTexCol_VS(VtxInput vtx,
                 out VecH4 outCol:COLOR   ,
                 out Vec4  outVtx:POSITION)
{
   outCol=vtx.color1();
   outVtx=0;
}
void Draw2DTexCol_PS()
{}
```
After converting to Spir-V to GLSL using https://github.com/KhronosGroup/SPIRV-Cross/
It gives me:
```
Shader:Draw2DTexCol VS
struct VtxInput
{
vec4 _pos;
mediump vec3 _hlp;
mediump vec3 _nrm;
mediump vec4 _tan;
vec2 _tex;
vec2 _tex1;
vec2 _tex2;
mediump float _size;
vec4 _bone;
mediump vec4 _weight;
mediump vec4 _material;
mediump vec4 _color;
};
layout(location=0)in vec4 ATTR0;
layout(location=1)in mediump vec3 ATTR1;
layout(location=2)in mediump vec3 ATTR2;
layout(location=3)in mediump vec4 ATTR3;
layout(location=4)in vec2 ATTR4;
layout(location=5)in vec2 ATTR5;
layout(location=6)in vec2 ATTR6;
layout(location=7)in mediump float ATTR7;
layout(location=8)in vec4 ATTR8;
layout(location=9)in mediump vec4 ATTR9;
layout(location=10)in mediump vec4 ATTR10;
layout(location=11)in mediump vec4 ATTR11;
out vec4 IO0;
out vec4 IO1;
void main()
{
VtxInput param_var_vtx=VtxInput(ATTR0,ATTR1,ATTR2,ATTR3,ATTR4,ATTR5,ATTR6,ATTR7,ATTR8,ATTR9,ATTR10,ATTR11);
IO0=vec4(param_var_vtx._color.xyz+vec3(1.0),param_var_vtx._color.w);
IO1=vec4(0.0);
}
```
It performs a useless copy of all VtxInput elements:
`VtxInput param_var_vtx=VtxInput(ATTR0,ATTR1,ATTR2,ATTR3,ATTR4,ATTR5,ATTR6,ATTR7,ATTR8,ATTR9,ATTR10,ATTR11);`

**Comment by jaebaek** [comment] 2019-08-06 15:32
I compiled this HLSL shader using `dxc.exe -Tvs_6_0 -EDraw2DTexCol_VS vtx_input.hlsl -fcgl -spirv -Fc vtx_input.spv` and it emits

```
...
%Draw2DTexCol_VS = OpFunction %void None %33
         %34 = OpLabel
%param_var_vtx = OpVariable %_ptr_Function_VtxInput Function
%param_var_outCol = OpVariable %_ptr_Function_v4float Function
%param_var_outVtx = OpVariable %_ptr_Function_v4float Function
         %41 = OpLoad %v4float %in_var_ATTR0
         %42 = OpLoad %v3float %in_var_ATTR1
         %43 = OpLoad %v3float %in_var_ATTR2
         %44 = OpLoad %v4float %in_var_ATTR3
         %45 = OpLoad %v2float %in_var_ATTR4
         %46 = OpLoad %v2float %in_var_ATTR5
         %47 = OpLoad %v2float %in_var_ATTR6
         %48 = OpLoad %float %in_var_ATTR7
         %49 = OpLoad %v4float %in_var_ATTR8
         %50 = OpLoad %v4float %in_var_ATTR9
         %51 = OpLoad %v4float %in_var_ATTR10
         %52 = OpLoad %v4float %in_var_ATTR11
         %53 = OpCompositeConstruct %VtxInput %41 %42 %43 %44 %45 %46 %47 %48 %49 %50 %51 %52
               OpStore %param_var_vtx %53
         %54 = OpFunctionCall %void %src_Draw2DTexCol_VS %param_var_vtx %param_var_outCol %param_var_outVtx
         %56 = OpLoad %v4float %param_var_outCol
               OpStore %out_var_COLOR %56
         %57 = OpLoad %v4float %param_var_outVtx
               OpStore %out_var_POSITION %57
               OpReturn
               OpFunctionEnd
%src_Draw2DTexCol_VS = OpFunction %void None %58
        %vtx = OpFunctionParameter %_ptr_Function_VtxInput
     %outCol = OpFunctionParameter %_ptr_Function_v4float
     %outVtx = OpFunctionParameter %_ptr_Function_v4float
   %bb_entry = OpLabel
         %63 = OpFunctionCall %v4float %VtxInput_color1 %vtx
               OpStore %outCol %63
               OpStore %outVtx %19
               OpReturn
               OpFunctionEnd
...
```

DXC creates a function whose name is `%Draw2DTexCol_VS` that is indeed a wrapper function of `%src_Draw2DTexCol_VS`.

The reason why DXC creates this wrapper function is described [here](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#shader-entry-function).

Briefly, in SPIR-V, there is no concept of function arguments/function return value of shader entry. On the other hands, HLSL shader entry function has arguments and return value.

Because of this gap, we let DXC create a wrapper function for the entry. In addition, DXC creates variables for arguments and return value of HLSL shader entry e.g., `param_var_vtx`. SPIR-V get/save values using these new variables instead of function arguments and return value.

I think the example you showed is intentional and it is not a bug.

**Comment by jaebaek** [comment] 2019-08-06 15:34
@GregSlazinski Let me close this issue after you confirm my comment

**Comment by GregSlazinski** [comment] 2019-08-06 15:57
I'm not saying it's a bug, this will affect performance of the shader. I don't think this issue should be closed without removing the extra copy. The glsl code performs useless operations compared to hlsl. So it will work slower on GL than DX, but the goal is to have the same performance.

**Comment by jaebaek** [comment] 2019-08-06 19:43
I am sorry. I did not clearly understand the situation. I think this is spirv-opt issue that it does not inline the code. I just opened an issue [here](https://github.com/KhronosGroup/SPIRV-Tools/issues/2786).

**Comment by jaebaek** [comment] 2019-08-08 18:12
#2398 solves this issue. @GregSlazinski please doublecheck this with the current master branch.

**Closed** 2019-08-09 16:19 UTC
Labels: spirv

**Comment by GregSlazinski** [comment] 2019-08-10 05:44
Thank you very much, problem solved
