### ISSUE TITLE
[SPIR-V] Validation error when push constant is passed into a function

### ISSUE THREAD

**Issue by godlikepanos** [microsoft/DirectXShaderCompiler#5808] opened 2023-10-02 14:54 UTC
**Description**
Getting a compiler error (thrown by SPIR-V validation) when a push constant is passed straight into a function. This error is thrown on trunk but not on DXC 1.7. ~~Please note that the SPIR-V generated between trunk and 1.7 is identical so either the problem was always there and the updated spirv-val caught it or newer spir-val is broken~~ (scratch that, seems I was wrong).

**Steps to Reproduce**
Simple repro case
```
struct Foo
{
    float m_x;
};
 
[[vk::push_constant]] ConstantBuffer<Foo> g_pc;
RWStructuredBuffer<float> g_buff;

float mul1(Foo m, float4 v)
{
	return m.m_x + v.x;
}
 
[numthreads(1, 1, 1)] void main()
{
    g_buff[0] = mul1(g_pc, float4(1, 0, 0, 1));
}
```

And the error is:
```
fatal error: generated SPIR-V is invalid: OpLoad Result Type <id> '7[%type_ConstantBuffer_Foo]' does not match Pointer <id> '4[%g_pc]'s type.
  %21 = OpLoad %type_ConstantBuffer_Foo %g_pc

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

**Actual Behavior**
There shouldn't be an error.

**Environment**
- DXC version: Trunk (6b4b0eb5)
- Host Operating System: Linux

**Comment by s-perron** [comment] 2023-10-17 13:47
This regression was caused by [SPIR-V] Handle non-global ConstantBuffer (#5446).

**Comment by s-perron** [comment] 2023-10-17 13:49
@cassiebeckley We can discuss possible solutions once you had a chance to look at it. I'm thinking we need to do something in spirv-opt.

**Comment by natevm** [comment] 2023-11-02 02:36
I seem to be running into a very similar issue, but with vk::shader_record_ext. Unfortunately this is a breaking change for me as well.

**Comment by natevm** [comment] 2023-11-02 02:47
Here's a working version with 1.7 : https://godbolt.org/z/7cd3ce8jc
And then here's the broken results with trunk: https://godbolt.org/z/Gr5e1P56P

@s-perron Would it be possible to include this as a test as a requirement before closing this issue?

**Comment by cassiebeckley** [comment] 2023-11-09 19:26
@natevm sure, I can do that

**Closed** 2023-11-22 14:19 UTC
Labels: bug, spirv
