### ISSUE TITLE
[SPIR-V] Compiler generates invalid SPIR-V when compiling with vulkan-with-source

### ISSUE THREAD

**Issue by Przemog1** [microsoft/DirectXShaderCompiler#5710] opened 2023-09-13 15:46 UTC
**Description**

SPIR-V generation fails with
```
fatal error: generated SPIR-V is invalid: Result type (OpTypeArray) does not match the type that results from indexing into the composite (OpTypeArray).
  %1152 = OpCompositeExtract %_arr_float_uint_14_0 %1140 5
```

Compile options used:
```
-spirv -HV 2021 -T ps_6_7 -enable-16bit-types -fvk-use-scalar-layout -fspv-debug=vulkan-with-source -fspv-target-env=vulkan1.3
```

**Steps to Reproduce**
https://godbolt.org/z/5P5dz4Gs6

**Actual Behavior**
SPIR-V validation fails when compiling with vulkan-with-source

**Environment**
- DXC version `2168dcb4fb0ac7841624228f8e186cc28f4cca91` and `libdxcompiler.so: 1.7(dev;1-843019ab)`
- Host Operating System: Windows but DXC as a lib and Godbolt (so Linux

**Comment by Przemog1** [comment] 2023-09-13 15:50
@greg-lunarg

**Comment by devshgraphicsprogramming** [comment] 2023-09-14 10:46
This seems different to #5218 as this si something about the validitity of indexing the `float[14]` when debug is emitted

**Comment by sudonatalie** [comment] 2023-09-20 19:55
This looks to be a duplicate of #5625 since it is the same error message and also fixed by replacing the same line:

```
LineStyleClipper<float> clipper = { lineStyles[mainObjects[currentMainObjectIdx].styleIdx] };
```

with:

```
LineStyleClipper<float> clipper = LineStyleClipper<float>::construct(lineStyles[mainObjects[currentMainObjectIdx].styleIdx]);
```

**Closed by sudonatalie** 2023-09-20 19:55 UTC
Labels: bug, spirv, hlsl2021, needs-triage
