### ISSUE TITLE
Index out of bounds in `DxilPrecisePropagatePass::PropagateThroughGEPs`

### ISSUE THREAD

**Issue by LukasBanana** [microsoft/DirectXShaderCompiler#4193] opened 2022-01-18 20:17 UTC
I have a ray generation shader that causes DXC to crash inside `DxilPrecisePropagatePass::PropagateThroughGEPs` because an index for `idxList` is out of bounds. @tex3D added this code a while ago, but perhaps this issue never occurred because the input to this parameter is usually a `SmallVector` with a guaranteed number of 8 or so elements:
https://github.com/microsoft/DirectXShaderCompiler/blob/0917aa9c0c20528b5cfb051f277eb01a222e51f2/lib/HLSL/DxilPrecisePropagatePass.cpp#L245

I haven't tracked down where the input comes from, but in my case `idxList` has only one element but `i` is 1, i.e. pointing out of the list. Changing the loop condition to this seems to fix the crash:
```cpp
while (idx != GEP->idx_end() && i < idxList.size())
```

Any thoughts on this change?

Thanks
Lukas

**Comment by tex3d** [comment] 2022-01-18 21:25
GEP index array OOB Issue with `DxilPrecisePropagatePass::PropagateThroughGEPs`:
https://github.com/microsoft/DirectXShaderCompiler/issues/4193

Thanks for the report!

Looking at this code, I think there are potential problems here, but it would be most helpful to have some HLSL that reproduces the problem.

As I reason through the code with the change you propose, I do think it could be correct, but it's difficult to be sure without digging in further and seeing the scenario that broke the assumption in the first place.

Here's my analysis so far.  Please let me know if this looks right according to your observations.

Intention of code looks like this:
- In marking GEP as precise,
- search for matching GEPs, such that instructions leading to stores to the same pointer location through independent GEPs are also marked as precise.
- Do so by decomposing the base pointer and index list for this GEP,
- then recursively search for other GEP users of base pointer, matching by the same index list,
- and mark each match as precise.
- Along the way, there may be multiple GEPs in a chain to reach the element being marked, which is handled by recursion and offsetting of the index array.

I suspect the issue may go something like this:
- While the multiple GEPs to reach the target element is handled, it's also possible for the element being marked to be an aggregate,
- in this case, it's possible that other GEPs being matched drill deeper than the original index list accounts for.
- Since we want to mark the entire aggregate as precise, we should consider any sub-element as a match needing to be marked precise.

With the fix, as soon as the matching element is reached, we should stop drilling into GEP indices and consider this a match.  `i` will be equal to `idxList.size()` after the loop, which will accomplish this goal.

**Comment by LukasBanana** [comment] 2022-01-18 21:47
Thank you for looking into this. I have to wrap my head around this part of DXC to provide proper feedback here, but I'm checking with my colleagues to send you the shader via email that reproduces the issue.

**Closed** 2022-01-22 03:31 UTC
Labels: bug
