### ISSUE TITLE
[SPIR-V] Fatal error in compilation when using nointerpolation modifier

### ISSUE THREAD

**Issue by Mr-Wiseguy** [microsoft/DirectXShaderCompiler#5326] opened 2023-06-26 19:54 UTC
The following code fails to compile when emitting SPIR-V, but compiles fine when emitting DXIL:
```hlsl
void PSMain(nointerpolation in float4 flatColor : COLOR0, out float4 resultColor : SV_TARGET)
{
    resultColor = flatColor;
}
```
The error is as follows:
```
fatal error: generated SPIR-V is invalid: OpStore Pointer <id> '3[%out_var_SV_TARGET]'s type does not match Object <id> '14[%14]'s type.
  OpStore %out_var_SV_TARGET %14
```

**Comment by s-perron** [comment] 2023-06-27 13:39
Duplicate of https://github.com/microsoft/DirectXShaderCompiler/issues/5270.

**Closed by s-perron** 2023-06-27 13:39 UTC
Labels: bug, spirv
