### ISSUE TITLE
Uninitialized resource didn't get compile error

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#6361] opened 2024-02-27 20:20 UTC
**Description**

When compile to ps_6_6, following shader didn't get compile/validation error for uninitialized resource.

```
struct S
{
    Texture2D m_texture;
};

[RootSignature("")]
float4 main() : SV_Target
{
    S s;
    return s.m_texture.Load(int3(0, 0, 0));
}

```
**Steps to Reproduce**

https://godbolt.org/z/qKPsKa5eK

**Actual Behavior**

@dx.op.annotateHandle(i32 216, %dx.types.Handle zeroinitializer, %dx.types.ResourceProperties { i32 2, i32 1033 })

**Comment by damyanp** [comment] 2024-11-05 18:23
Duplicate of #4415

**Closed by damyanp** 2024-11-05 18:23 UTC
Labels: bug, validation
