### ISSUE TITLE
DXC_MICROCOM_ADDREF_RELEASE_IMPL no longer usable from user code

### ISSUE THREAD

**Issue by simontaylor81** [microsoft/DirectXShaderCompiler#1391] opened 2018-06-28 15:13 UTC
I just synced to the latest version, and my custom include handler no longer compiles, due to it using `DXC_MICROCOM_ADDREF_RELEASE_IMPL`. This was recently changed in #1309 to use generic atomics instead of referencing the windows functions directly, and now using it gives a linker error as those functions are not inlined.

Our application #includes the dxc header files then dynamically loads the dll. We do not link against any llvm libs, and doing so would require a significant rework of our build system.

**Comment by pow2clk** [comment] 2018-06-28 15:51
Hi @simontaylor81 

I regret that this change disrupted your code. If you're interested in using the defines as they were, they were relatively simple and it seems you could reimplement them as they were and include them from a separate header with slightly different names or even undef the ones from the dxc header and redefine them as suits you.

Alternatively, the Atomic implementation is fairly constrained within the Atomic.* files in lib/Support LLVM. You might be able to add them to your source base without too much hassle.

The DXC headers are written with the expectation that they will be linked with LLVM code, but in this case I think there's a reasonable solution. This alteration was made to enable support for non-Windows platforms.

**Comment by pow2clk** [comment] 2018-06-28 15:53
Here's a header you might try
[addref.h.txt](https://github.com/Microsoft/DirectXShaderCompiler/files/2145993/addref.h.txt)

**Comment by simontaylor81** [comment] 2018-06-29 15:56
Yep, the actual macro is fairly trivial, I actually already re-implemented it.

What worries me more is this: "The DXC headers are written with the expectation that they will be linked with LLVM code"

From what I understood this was very much not the assumption -- the Windows SDK ships dxcompiler.dll, and I thought the expectation is that all you needed to use this was the header files and the dll. If we have to static-link against the llvm .libs, then it doesn't seem worth having a dll at all.

Is there an official line on this @marcelolr?

**Comment by pow2clk** [comment] 2018-06-29 16:41
I would be interested as well to hear what @marcelolr has to say about this. If the change violated a design paradigm, I'd be happy to look into another solution.

I based my summary of the constraints on the headers in dxc/Support on what was already there. They contain numerous elements that rely on LLVM for their implementations. A cursory examination includes `llvm:StringRef`, `llvm::SmallVector`, `llvm::opt::InputArgList`,  `llvm::raw_ostream`, `llvm::OptTable`, etc. I view microcom.h and the other headers here not as defining a public interface to dxcompiler.dll interface, which exports just two functions, but the headers used to implement dxcompiler.dll, which in this project, depends on LLVM.

**Comment by marcelolr** [comment] 2018-06-29 17:21
The DLL is definitely meant to be used with just headers and a dynamic library. The exports from the DLL are limited, by design. The approach is a clean micro/nano-COM design (so COM patterns but without COM runtime support - registration/marshalling/etc.) - you create objects by CLSID with a factory function and access them via IID/v-tables. That's what include/dxc headers provide.

There are some extra goodies that are available beyond what the DLL does, but "it's complicated". It turns out these things are useful, but we don't make them part of the DLL functionality because they are often very general in nature (for example, microcom.h started off as a way of having atlbase.h functionality but without pulling in more Windows stuff into scope).

The stuff under include/dxc/Support is where the line blurs. It's there to support both internal usage as well as to simplify the code for callers (in particular, dxcapi.use.h is clearly marked as being there for callers to pick up, and ErrorCodes.h is there to help crack HRESULTs). Some of the functionality there has a bit more meat on it, like the various ways to create streams and blob helpers. For those, we expect folks will statically link some of the libraries with the backing implementation.

For things in that directory, we should probably clean up into standalone and library-dependant, and then not move things in a way that will break users.

**Comment by pow2clk** [comment] 2018-06-29 17:45
thanks @marcelor. Informative as usual. In such a clean up to make dxc/Support library-independent, would you consider the `ADDREF` macros something that should be part of the interface or something that should be moved somewhere internal? 

On a less related note, where would that internal location be? dxc/Support mirrors llvm/Support kind of nicely I think, but then again there's that Emerson quote about foolish consistency. . .

**Closed** 2020-07-06 23:35 UTC
