### ISSUE TITLE
[SPIR-V] Add support for 64 bit atomics

### ISSUE THREAD

**Issue by natevm** [microsoft/DirectXShaderCompiler#5965] opened 2023-11-02 22:07 UTC
**Is your feature request related to a problem? Please describe.**
When I attempt to use something like "InterlockedAdd64", dxc returns "error GCC929F7B: intrinsic 'InterlockedAdd64' method unimplemented" when targeting SPIR-V. (minimal reproducer: https://godbolt.org/z/oe1bG7T3d)

**Describe the solution you'd like**
We should instead request a `-fspv-extension=SPV_KHR_shader_atomic_int64` in the compilation flags, then allow functions like InterlockedAdd64 to emit opcodes like OpAtomicIAdd with 64 bit types for inputs/output/comparands. 

**Describe alternatives you've considered**
Perhaps it could theoretically be possible to emit custom SPIR-V, but OpAtomicIAdd requires a complex pointer type for the RWByteAddressBuffer that I'm trying to use, and I can't figure out how to actually write this with GL_EXT_spirv_intrinsics... 

**Additional context**
64 bit atomic adds are necessary for certain operations when implementing a single pass parallel prefix sum, as described here: https://research.nvidia.com/sites/default/files/pubs/2016-03_Single-pass-Parallel-Prefix/nvr-2016-002.pdf. These prefix sums in turn are fundamental building blocks to many parallel algorithms relevant in ray tracing (eg, PLOC tree construction). Without 64 bit atomics, a single pass prefix sum is still possible, but requires some expensive memory fences.

**Comment by devshgraphicsprogramming** [comment] 2023-11-03 00:33
> and I can't figure out how to actually write this with GL_EXT_spirv_intrinsics...

Like this:
https://github.com/Devsh-Graphics-Programming/Nabla/blob/6b33b9730c65bd23569ffe977abcdbb426686d0b/include/nbl/builtin/hlsl/spirv_intrinsics/core.hlsl#L23-L30

Then you can add one more layer of wrapping (to hide the memory semantics and scope) if you like playing with fire and relying on `inout T` being a `T restrict &` (which will break/no-longer-be-possible with the merging of #5249)

> 64 bit atomic adds are necessary for certain operations when implementing a single pass parallel prefix sum, as described here: https://research.nvidia.com/sites/default/files/pubs/2016-03_Single-pass-Parallel-Prefix/nvr-2016-002.pdf.

Damn, and I thought I independently invented that one 2 years ago.

**Comment by natevm** [comment] 2023-11-03 01:03
Aha, perfect! Thank you for the help! Honestly I was studying some of your previous posts too haha

64 bit intrinsics would still be nice to natively support. 

In retrospect, the single pass approach could also use 32 bit atomics, just limited to 30 bit unsigned integers.

**Comment by natevm** [comment] 2023-11-03 01:40
@devshgraphicsprogramming Hmm… do these work with RWByteAddressBuffers? I’m guessing they don’t, since byte address buffers don’t have an array operator.

**Comment by s-perron** [comment] 2023-11-03 15:28
It is on our list of missing features to implement. No timeline on when we will get to it. I'll link this issue to our internal work list, which will increase its priority a little.

**Comment by natevm** [comment] 2023-11-03 17:58
> It is on our list of missing features to implement. No timeline on when we will get to it. I'll link this issue to our internal work list, which will increase its priority a little.

Awesome, thanks! Another motivating example for 64 bit atomics would probably be to support 64 bit keys in this "OneSweep" sorting algorithm which uses a similar atomic pattern for the lookback : https://arxiv.org/abs/2206.01784 

This seems to be what's currently "state of the art" in GPU sorting these days. Today, we can implement a 2^30 bit key sort, but for tree construction algorithms, having more precise keys translates to more precise space filling curve codes, or being able to more efficiently sort key-value pairs.

**Comment by AntonTokarev** [comment] 2023-11-04 22:20
Doesn't the InterlockedAdd on StructuredBuffer do the same already? https://godbolt.org/z/ed9nsqT93

**Comment by natevm** [comment] 2023-11-04 22:52
On mobile atm, unfortunately godbolt doesn’t seem to work there. I was pretty sure that InterlockedAdd casts the input parameters to 32 bit integers. 

InterlockedAdd64 would be the function to test. 

@devshgraphicsprogramming ’s inline SPIR-V solution would work for 64 bit integers in structured buffers, but doesn’t work if you’re constrained to using RWByteAddressBuffers.

**Comment by devshgraphicsprogramming** [comment] 2023-11-04 23:47
> On mobile atm, unfortunately godbolt doesn’t seem to work there. I was pretty sure that InterlockedAdd casts the input parameters to 32 bit integers.
> 
> InterlockedAdd64 would be the function to test.
> 
> @devshgraphicsprogramming ’s inline SPIR-V solution would work for 64 bit integers in structured buffers, but doesn’t work if you’re constrained to using RWByteAddressBuffers.

Once proposal 0011 is in (AFAIK its being implemented right now), atomics might finally work with BDA so there'd be no reason to use ByteAddressBuffers on Vulkan.

**Comment by s-perron** [comment] 2023-11-15 19:09
Unfortunately, it will not be possible to implement The `Interlocked*64` member functions for `RWByteAddressBuffer`s. The problem is that SPIR-V cannot express it in logical addressing mode.

The `RWByteAddressBuffer` is suppose to be unaware of its type. The type for the load or store is determined during the actual load or store operation. That does not directly translate to SPIR-V, which requires the declaration of the variable to have a type and all loads and stores have to match that type. In general, we get around this by declaring the variable to be an array of `uint32`. A load as a 64-bit int would be implemented as two 32-bit loads and have the two value merged together using bit operations.

When it comes to atomic operations, we cannot split the operations to act on 32-bit values because that would break atomicity for the the 64-bit memory location. Sorry this cannot be implemented in DXC until there is a change to SPIR-V. We will keep this in our list of missing features, and implement if SPIR-V get a change that will allow it.

FYI: @alan-baker

**Comment by devshgraphicsprogramming** [comment] 2023-11-15 19:37
I believe that you, @natevm are a heavy user of BDA (at least in the past) and having proposals 0010 and 0011 implemented would achieve what you want,

**Closed** 2024-02-13 16:02 UTC
Labels: enhancement, spirv

**Comment by natevm** [comment] 2024-02-13 16:49
@s-perron we should keep this issue open. Vulkan and SPIR-V do support 64 bit atomics through VK_KHR_shader_atomic_int64 and VK_EXT_shader_image_atomic_int64.

**Comment by s-perron** [comment] 2024-02-13 17:02
RWByteAddressBuffers are represented as an array of int32s. We are not allowed to cast the pointer to point to 64-bit memory to pass it to the atomic operations. We need a way to get arbitrary type pointers to memory on a RWByteAddressBuffer.

**Comment by s-perron** [comment] 2024-02-13 17:39
Yes they should. If not, open a new more specific bug.
