### ISSUE TITLE
IDxcResult of successful compilation reports that there is no reflection part when it does exist

### ISSUE THREAD

**Issue by KStocky** [microsoft/DirectXShaderCompiler#5948] opened 2023-10-28 14:02 UTC
**Description**
With all successful compilations, trying to retrieve the reflection output using IDxcResult::GetNumOutputs and IDxcResult::GetOutputByIndex fails. 

**Steps to Reproduce**
Compile the following shader https://shader-playground.timjones.io/4383ead8234740624dc8664e24182dbf
with IDxcCompiler3::Compile

**Actual Behavior**
Calling IDxcResult::GetNumOutputs will return 6
Calling IDxcResult::GetOutputByIndex with indexes 0 to 5 results in
DXC_OUT_OBJECT
DXC_OUT_ERRORS
DXC_OUT_PDB
DXC_OUT_SHADER_HASH
DXC_OUT_NONE
DXC_OUT_NONE

Calling IDxCResult::GetOutput with DXC_OUT_REFLECTION will succeed.

**Expected Behaviour**
I would expect that if there was a reflection output for it to be retrieved using IDxcResult::GetOutputByIndex

**Environment**
DXC version 1.7.2308
Host Operating System Windows 10 Pro: 22H2

**Comment by damyanp** [comment] 2024-10-24 17:29
Duplicate of #6523.

**Closed by damyanp** 2024-10-24 17:29 UTC
Labels: bug
