### ISSUE TITLE
[SPIR-V] Sample and Load offsets fail to build

### ISSUE THREAD

**Issue by pearcewf** [microsoft/DirectXShaderCompiler#3807] opened 2021-05-31 21:58 UTC
The following code using sampling offsets fails with the latest tagged release, as well as the latest builds from Appveyor. It is also present with Load offsets. This worked in previous releases of DXC.

Simple replication case:

```
Texture2D textureToLoad	: register(t0);

SamplerState bilinearClamp	: register(s0);

struct VertexOut
{
	float4 posH : SV_POSITION;
	float2 tex : TEXCOORD;
};

float4 sampleNeighbor(float2 uv, int2 offset)
{
	return textureToLoad.SampleLevel(bilinearClamp, uv, 0, offset);
}

float4 main(VertexOut pIn) : SV_TARGET
{
	//float4 initialColor = textureToLoad.Load(int3(pIn.posH.xy, 0));
	//float4 color = initialColor;

        // fine
	float4 a = textureToLoad.SampleLevel(bilinearClamp, pIn.tex, 0, int2(1, 1));
	return a;

        // fails
	//const int2 offset = int2(1, 1);
	//float4 b = textureToLoad.SampleLevel(bilinearClamp, pIn.tex, 0, offset);
	//return b;

        // fails
	//float4 c = sampleNeighbor(pIn.tex, int2(1, 1));
	//return c;
}
```

Error message from latest tagged release (v1.6.2104)

```
Error Message:
Shaders/Test_PS.hlsl:25:21: error: Use constant value for offset (SPIR-V spec does not accept a variable offset for OpImage* instructions other than OpImage*Gather)
```

Error message from Appveyor build

```
Error Message:
fatal error: generated SPIR-V is invalid: [VUID-StandaloneSpirv-Offset-04663] Image Operand Offset can only be used with OpImage*Gather operations
  %58 = OpImageSampleExplicitLod %v4float %57 %54 Lod|Offset %float_0 %55

note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```

Was this a work-around that has been disabled recently? I haven't updated my local DXC since mid-last year, so it's hard to tell when this might have been introduced.

**Comment by jaebaek** [comment] 2021-06-01 00:55
spirv-val recently added a validation rule to restrict only the constant offset to be used as `Offset` Operand of `OpImageSampleExplicitLod`.
In your code, after we inlining the function calls, all offsets for `SampleLevel` and `Load` are constants, so it should work without any issue in theory. I fixed the DXC bug that exists in the latest tagged release (v1.6.2104) and confirmed it is working fine.

One question .. what was the compile option for each case?
If you did not run it with `-fcgl` or disable the spirv-opt, it should work.
I guess .. you turned off the spirv-opt and inlining SPIR-V did not work ..?

**Comment by pearcewf** [comment] 2021-06-01 01:11
Thanks for getting back to me. This is the command line I used for the above examples:
```
dxc.exe -WX -spirv -fspv-target-env=vulkan1.1 -Zi -Od -E main -Fo ../Lib/Shaders/Compiled/Test_PS.spv -T ps_6_0  -nologo Source/Shaders/Test_PS.hlsl
````

**Comment by pearcewf** [comment] 2021-06-01 01:30
Just wanted to follow up after a bit more testing and confirm what I thought to be true in my edits above. This occurs only (and always) with optimizations disabled (-Od). If I enable any level of optimization (O1, O2, O3) it is not present.

**Comment by jaebaek** [comment] 2021-06-01 01:34
Thanks. Yes. DXC can determine the obvious case i.e., literal constant offset but it has to rely on spirv-opt for the inlining or loop-unrolling case because it needs some complicated analysis. If there is no other issue, may I close this issue?

**Comment by pearcewf** [comment] 2021-06-01 01:43
I guess before closing - do you know of or have any recommendation for successfully compiling that shader with optimizations disabled (i.e., the way it used to work)? Basically, a way to replicate the old behavior?

Other than that, yeah I think it's ok to close if this isn't something that can be addressed.

**Comment by jaebaek** [comment] 2021-06-01 01:55
Since the spirv-val change https://github.com/KhronosGroup/SPIRV-Tools/pull/4118 let us define the "validity" of the code in the different way, the variable offset that becomes a constant after inlining is no longer valid without the function inlining.

It seems that the only workaround we can try is to let the DXC run spirv-opt if it contains variable offset regardless of the optimization option. However, I am afraid if it is not the behavior HLSL developers expect.

Other than that .. the only way making it working currently is to manually inline the function. I know it would be painful to update the large amount of shaders.

I will consider it more and get back.

**Comment by pearcewf** [comment] 2021-06-01 01:57
No worries, and thank you for all you help.

Let's go ahead and close this. No need to try and find an obscure fix for something that's working as intended.

Thank you again for your help and the useful information you provided 👍

**Comment by jaebaek** [comment] 2021-06-01 02:00
Thank for reporting this issue :) It also helps me to consider this issue once more. I want to figure out what developers expect. I will reopen this issue if the idea of enforcing spirv-opt execution would be the right direction.

**Closed by jaebaek** 2021-06-01 02:00 UTC
Labels: spirv

**Comment by jaebaek** [comment] 2021-06-10 03:07
I conducted some experiments to check the behavior of DXIL backend.

The following code is obviously wrong, but the DXIL backend does not report a validation error if we use `-fcgl` option to compile the shader.
```
SamplerState      gSampler  : register(s5);
Texture2D<float4> t         : register(t1);
 
float4 sample(int2 offset, float clamp) {
    uint status;
    return t.Sample(gSampler, float2(0.1, 0.2), offset, clamp, status);
}
 
float4 main(int2 offset: A) : SV_Target {
    float4 val = 0;
    for (int i = 0; i < 3; ++i)
        val = sample(offset, i);
    return val;
}
```
On the other hand, compiling it without `-fcgl` reports a validation error.

DXIL backend does not report a validation error for the following code regardless of `-fcgl`:
```
SamplerState      gSampler  : register(s5);
Texture2D<float4> t         : register(t1);
 
float4 sample(int offset, float clamp) {
    uint status;
    return t.Sample(gSampler, float2(0.1, 0.2), offset, clamp, status);
}
 
float4 main(int2 offset: A) : SV_Target {
    float4 val = 0;
    for (int i = 0; i < 3; ++i)
        val = sample(i, offset.x);
    return val;
}
```

To match the behavior of DXIL backend, we should
1. update spirv-val to not report a validation error for the above case when `--before-legalize-hlsl` option is enabled.
2. in DXC, conduct the legalization if `-fcgl` is not enabled or pass `--before-legalize-hlsl` option to spirv-val if `-fcgl` is enabled.

I recently submitted the spirv-val update: https://github.com/KhronosGroup/SPIRV-Tools/pull/4316
#3820 is the PR for the DXC part of this workaround.
