### ISSUE TITLE
dxcompiler crash when function is missing a return value

### ISSUE THREAD

**Issue by BitMD** [microsoft/DirectXShaderCompiler#2488] opened 2019-09-25 02:33 UTC
The following code should result in a compilation error due to the missing function return value.  Instead, the compiler crashes.

This was tested with the latest dxcompiler release (1.4.1907.0) and the crash still repros.

<code>
struct RayIntersection
{
    float3 origin;
};

struct AttributeData
{
    float2 barycentrics;
};

bool SomeFunction()
{
   // missing return here causes a crash in dxcompiler.dll
}

[shader("anyhit")]
void AnyHitMain(inout RayIntersection rayIntersection : SV_RayPayload, AttributeData attributeData : SV_IntersectionAttributes)
{
     SomeFunction();
}

</code>

**Comment by pow2clk** [comment] 2020-08-14 20:55
Tex fixed this with #3004 So this is a dupe of #2975

**Closed by pow2clk** 2020-08-14 20:55 UTC
Labels: bug
