### ISSUE TITLE
Support ninja compatable depfile

### ISSUE THREAD

**Issue by ScatteredRay** [microsoft/DirectXShaderCompiler#3509] opened 2021-02-25 23:24 UTC
Integrating DXC into our build process, we need a way to rebuild shaders when their dependencies change. it's pretty common for other compilers to support emitting a depfile for instance as used by Ninja: https://ninja-build.org/manual.html#ref_headers

The DXC command line compiler doesn't seem to support this, but it would be greatly useful to have.

**Comment by Lssikkes** [comment] 2021-07-03 15:57
I'm currently using a workaround with /Vi, with a helper executable converting that to CL.EXE compatible dependency syntax so that Ninja can handle the output. It's far from ideal, and to make matters worse, preprocessor-only mode doesn't emit /Vi in DXC.exe whereas FXC.exe does. i.e. I need to compile at least one permutation of the shader correctly to dump the dependencies.

**Comment by pow2clk** [comment] 2021-11-18 20:51
@ScatteredRay, this is being worked on by @jaebaek here https://github.com/microsoft/DirectXShaderCompiler/pull/4017

As such, I'm closing this as a duplicate of #2063

**Closed by pow2clk** 2021-11-18 20:51 UTC
