### ISSUE TITLE
Detect unix path separator as well

### ISSUE THREAD

**Issue by sunillnaik** [microsoft/DirectXShaderCompiler#2652] opened 2020-01-17 09:01 UTC
Below line of code should respect unix path separator as well,
https://github.com/microsoft/DirectXShaderCompiler/blob/0532d8cd08c9535af2ca5407a3c6289766312f53/tools/clang/tools/dxclib/dxc.cpp#L780

Example:
`if (!m_Opts.DebugFile.empty() && (m_Opts.DebugFile.endswith(llvm::StringRef("\\")) || m_Opts.DebugFile.endswith(llvm::StringRef("/")))) {`

**Comment by pow2clk** [comment] 2020-09-25 15:37
I'm a bit confused by the source line you reference in dxc.cpp. I wonder if you meant to reference:

https://github.com/microsoft/DirectXShaderCompiler/blob/634a23537df7e85512437a4976f9bf9fcd095e18/lib/DxcSupport/HLSLOptions.cpp#L154

Which would make sense. I think `is_separator()` is platform specific. It should allow unix path separators for those build. I agree there's little reason to limit it to `\` even on Windows.

**Comment by pow2clk** [comment] 2021-05-27 20:02
I take back my earlier comment, path::is_separator already accepts both `\` and `/` on Windows : https://github.com/microsoft/DirectXShaderCompiler/blob/e6ba792e2d9bff8c1401e8bb7e8835d5f8a8b17a/lib/Support/Windows/MSFileSystem.inc.cpp#L225-L230

The bug is old and it's not clear what the problem is specifically so I'm closing it out. Please reopen with more details if there is still an issue.

**Closed by pow2clk** 2021-05-27 20:02 UTC
