### ISSUE TITLE
[spirv] backend has issues with min16float shader..

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectXShaderCompiler#1095] opened 2018-02-26 12:26 UTC
Ok,
so similar to my previous Mandelbrot double precision HLSL experiment and opened issue with doubles, I moved hlsl kernel computations to use min16float..
NOTE I already tested min16float kernel giving more than 50% performance improvement (fps) on Intel HD 530 GPUs vs original program using float computation (http://users.skynet.be/fquake/MandelDX11.zip):
(note program has source code but has to be minimally modified and recompiled as it depends as prebuilt in zip on dxcompiler_42 which has no support to min16float)

I would love to test port this mandelbrot program to Vulkan using HLSL source code using your SPIR-V backend..

I tried to compile to spirv running:
 dxc -E CSMandelJulia_scalarFloat -T cs_5_0 mandelfp16v2.hlsl -spirv
returns:

> mandelfp16v2.hlsl:45:5: warning: conversion from larger type 'float' to smaller type 'min16float', possible loss of data
>   b = b*0.5f;
>     ^
> mandelfp16v2.hlsl:9:22: warning: resource binding #0 in descriptor set #0 already assigned
> cbuffer cbCSMandel : register( b0 )
>                      ^
> mandelfp16v2.hlsl:7:30: note: binding number previously assigned here
> RWTexture2D<float4> output : register (u0);
>                              ^
> fatal error: generated SPIR-V is invalid: Expected input to have different bit width from Result Type: FConvert
> note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

note without spirv argument correctly generates DXIL with code like:
```
 fadd fast half %mul26.8, %cond
  %mul28.8 = fmul fast half %mul25.8, %mul25.8
  %sub29.8 = fsub fast half %add27.8, %mul28.8
  %mul30.8 = fmul fast half %mul25.8, %sub.8

```
vs original code which generated DXIL like:

> fmul fast float

@antiagainst can share if interest on fixing/implementing support for min16float on shaders..
mapping optimally may require Float16 SPIR-V cap., I think only exposed by AMD VK_AMD_gpu_shader_half_float?

here is "mandelfp16v2.hlsl " source code :
```
// Coded by Jan Vlietinck, 18 Oct 2009, V 1.8
//http://users.skynet.be/fquake/


#define UNROLL 32

RWTexture2D<float4> output : register (u0);

cbuffer cbCSMandel : register( b0 )
{
  
	float a0, b0, da, db;
	float  ja0, jb0; // julia set point
	
	int max_iterations;
	bool julia;  // julia or mandel
	int   cycle;
};





[numthreads(16, 16, 1)]
//****************************************************************************
void CSMandelJulia_scalarFloat( uint3 Gid : SV_GroupID, uint3 DTid : SV_DispatchThreadID, uint3 GTid : SV_GroupThreadID, uint GI : SV_GroupIndex )
//****************************************************************************
{ 
	int counter =  max_iterations & (~(UNROLL-1));
	
	min16float u,v;
	u = (min16float)(a0 + da*DTid.x);
	v = (min16float)(b0 + db*DTid.y);


  min16float a,b;
  a = (julia) ? (min16float) ja0 : u;
  b = (julia) ? (min16float) jb0 : v;

  bool inside;
	min16float ur, vr, t;
  ur = u;
  vr = v;

  b = b*0.5f;

  do
	{ 
	  [unroll]
	  for (int i=0; i<UNROLL/2; i++)
	  {
		  t =    u*u + a - v*v;  
		  v = 2*(u*v + b); 
		  u =    t*t + a - v*v;  
		  v = 2*(t*v + b); 
		}

    inside = u*u+v*v < 4.0f;
		counter -= (inside) ? UNROLL : 0;
  	ur =       (inside) ? u : ur;
		vr =       (inside) ? v : vr;		
	} while ( inside && counter!=0);


  u = ur;
  v = vr;
  do
  {
	  t =    u*u + a - v*v;  
    v = 2*(u*v + b); 
    u = t;	    
    inside = (u*u+v*v < 4.0f) && (counter!=0);
	  counter -= (inside) ? 1 : 0;		
	} while (inside); 	


  float4 color;
  
  float c = (float) (counter + cycle)*2*3.1416f / 256.0f;  // color cycle
  color.r = (1+cos(  c)              )/2; 
  color.g = (1+cos(2*c + 2*3.1416f/3))/2; 
  color.b = (1+cos(  c - 2*3.1416f/3))/2; 
  color.a = 1;
  
  
  output[DTid.xy] = (counter == 0) ? 0 : color;
  
}
```

**Comment by antiagainst** [comment] 2018-02-27 00:11
Hey @oscarbg, thanks for the report! Yep, we will support `min16float`. @ehsannas  will take a look and fix this.

Just keep in mind that `min16float` will be translated into 32-bit floats unless you specify `-enable-16bit-types`: https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#normal-scalar-types

**Comment by oscarbg** [comment] 2018-02-27 12:15
thanks @antiagainst..
and also to @ehsannas ..
thanks for reminding me to -enable-16bit-types..
I see from docs will map nicely to SPV_AMD_gpu_shader_half_float in that case which is nice..
based on docs also seems min16int types are implemented on SPIR-V backend that map to Int16 capability, right?
if yes, might try to test also eventually with a fixed function min16int HLSL shader mandelbrot demo..

also let me ask you some questions:
seeing Vega Vulkan driver exposing all these 16bit int/float extensions:
VK_AMD_gpu_shader_int16 
VK_AMD_gpu_shader_half_float_fetch
VK_KHR_16bit_storage
is there any case where they could used for enhanced mapping of "new relaxed precision" support in SM6.2?

I mean for ex. VK_AMD_gpu_shader_int16 exposes:

```
This extension adds support for 16-bit signed and unsigned integer component types for the following instructions described in the GLSL.std.450 extended instruction set:
Frexp

```
is also support for this operation on min16int types in HLSL 6.2?

now changing to VK_KHR_16bit_storage:

```
The `VK_KHR_16bit_storage` extension allows use of 16-bit types in shader
input and output interfaces, and push constant blocks.
```

does this mean that declaring a function in HLSL with min16int as argument or return type or a cbuffer as

cbuffer cbCSMandel : register( b0 )
{
  
	int16min a0, b0, da, db;
}

mapping to SPIR-V correctly should need support for SPV_KHR_16bit_storage?

and finally about VK_AMD_gpu_shader_half_float_fetch:
```
this extension adds support for 16-bit float Result Type which can now be used by the following image instructions:

OpImageFetch
OpImageGather
OpImageRead
...
```
is this supported on HLSL: textures that return min16float values or his vector variants?

briefly asking if these extension are more "powerful" than HLSL relaxed precision already is or really you haven't still make use of it..
thanks for all your work..

**Comment by antiagainst** [comment] 2018-02-27 21:36
@oscarbg:

> based on docs also seems min16int types are implemented on SPIR-V backend that map to Int16 capability, right?

Yes, `min16int` is translated into 16-bit integer type requiring `Int16` capability, if you specify `-enable-16bit-types`. We follow the [translation table for DXIL](https://github.com/Microsoft/DirectXShaderCompiler/wiki/16-Bit-Scalar-Types#dxil-scalar-type) and do corresponding CodeGen for SPIR-V.

> if yes, might try to test also eventually with a fixed function min16int HLSL shader mandelbrot demo..

SG. Please do not hesitate to file issues if you find something not working.

For extension support, we haven't finalized the plan on how to properly control extensions used in CodeGen yet. The extensions generated right now are either KHR ones or the only one available for a specific HLSL feature. Specifically for the extensions we've mentioned, I think we may do SPV_KHR_16bit_storage to support using 16bit types in resources and stage IOs.

**Comment by ehsannas** [comment] 2018-03-01 17:25
@oscarbg 
I have merged #1105 which should add a lot of the missing coverage regarding 16-bit floats. The code you have attached above also compiles successfully now.

**Comment by ehsannas** [comment] 2018-03-01 17:26
I will close this issue. Please open new separate issues if there are specific extension feature requests so that each one can be prioritized accordingly. Thanks for reporting! :)

**Comment by oscarbg** [comment] 2018-03-02 15:15
Hi @ehsannas,
sad to say but after testing some time, seems the issue is not completely solved..
let's see:
regarding original:
dxc -E CSMandelJulia_scalarFloat -T cs_5_0 mandelfp16v2.hlsl -spirv
yeah it works now but as you say it uses floats as type but then adding -enable-16bit-types : 
dxc -E CSMandelJulia_scalarFloat -T cs_5_0 mandelfp16v2.hlsl -spirv -enable-16bit-types
says
dxc failed : enable-16bit-types is only allowed for shader model >= 6.2 and HLSL Language >= 2018.
ok but:
dxc -E CSMandelJulia_scalarFloat -T cs_6_2 mandelfp16v2.hlsl -spirv -enable-16bit-types
doesn't output anything..
also tried both /Fc and /fh options in case was an issue with std output but no files were generated..
can you reopen issue please..
thanks for your support to both of you..

**Comment by ehsannas** [comment] 2018-03-02 15:20
hmm... I'll give it another try.

**Comment by oscarbg** [comment] 2018-03-02 15:28
thanks..

**Comment by ehsannas** [comment] 2018-03-05 15:57
Hi @oscarbg , When I run the shader with your command line options, i get this error (and hence no SPIR-V output):
```
error: generated SPIR-V is invalid: Capability Float16 is not allowed by Vulkan 1.0 specification (or requires extension)
```
This is an error that's generated by the SPIR-V Validator that runs on the generated SPIR-V.

If you want to get the SPIR-V output, please run with the "-Vd" command line option which indicates the validator should not be run on the generated SPIR-V. i.e.

```
dxc.exe -E CSMandelJulia_scalarFloat -T cs_6_2 test.hlsl -spirv -enable-16bit-types -Vd
```

Once you do that, you'll see that the compiler is emitting:
```spir-v
               OpCapability Float16
               OpCapability Shader
               OpExtension "SPV_AMD_gpu_shader_half_float"
               ...
```

Which is legal because we do emit the necessary extension. So I believe this is a bug for the SPIR-V Validator. I have filed https://github.com/KhronosGroup/SPIRV-Tools/issues/1375.

In the meantine, use "-Vd" to unblock your work.

Let me know if you run into any issues. Otherwise feel free to close this issue. Thanks

**Comment by oscarbg** [comment] 2018-03-05 16:46
Hi,
many thanks.. 
seems DXC still has a bug with min16float, this time with optimization flags.. so I will leave it open still :-(..
Ok let me explain how it goes..
I check adding -Vd and still see nothing.. 
it seems to be my problem as after adding "-Vd" still don't see nothing and I thought that if you checked and worked correctly something was wrong..
I redownload another build having your commit like from here:
https://ci.appveyor.com/project/marcelolr/directxshadercompiler/build/1.0.2015/artifacts
still the same..
think a littler and by luck just see default compiler options and see:
 -O3 Optimization Level 3 (Default)
don't know if your the build you develop has also same option by default so I check with -O0 to see if it helps..
and voila now I see as you say:
```
fatal error: generated SPIR-V is invalid: Capability Float16 is not allowed by Vulkan 1.0 specification (or requires extension)
note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible
```
if I have seen this warning perhaps I had not bothered with that as I hope had figured to disable validation even if I didn't know that between the lines DXC was validating the SPIR-V output..
and you are right "-Vd" is good enough right now..
so briefly I see your compiler error with:

> dxc.exe -E CSMandelJulia_scalarFloat test.hlsl -enable-16bit-types  -T cs_6_2 -spirv  -O0

and fix it finally with:

> dxc.exe -E CSMandelJulia_scalarFloat test.hlsl -enable-16bit-types  -T cs_6_2 -spirv  -O0 -Vd

so the bug seems to be to require disabling all compiler optimiz. ("-O0") for obtaining SPIR-V using min16float code..
-O3 works with either no -enable-16bit-types so it's a min16float related bug..
finally one thing to say:

It's also very strange, as I remember very recently to have run spirv-val without errors on SPIR-V shaders (translated from GLSL using glslang) that have also:
 ```
               OpCapability Float16
               OpCapability Shader
               OpExtension "SPV_AMD_gpu_shader_half_float"
```
maybe error because of SPIR-V version 1.0? not recent enough spirv-val? just ideas..

thanks for opening the SPIRV-tools issue already..

**Comment by ehsannas** [comment] 2018-03-05 17:31
I was able to reproduce the behavior you are seeing. There is indeed an error coming from the SPIR-V optimizer. I have filed https://github.com/KhronosGroup/SPIRV-Tools/issues/1376 to address that issue.
I will close this one since the generated SPIR-V is correct. Thanks for reporting! :-)

**Comment by ehsannas** [comment] 2018-03-05 19:41
Upon further discussion, it seems that we should not emit ``OpCapability Float16``, and should only emit the extension. The drivers that support this extension should work once they see the extension in the SPIR-V binary even in the absence of the capability.

SPV_AMD_gpu_shader_half_float does not enable SPIR-V's Float16 capability.

**Comment by ehsannas** [comment] 2018-03-05 19:41
Fix coming soon

**Comment by oscarbg** [comment] 2018-03-06 06:36
Thanks..
seems this sample is a good one at catching exisiting issues even on SPIRV-Tools.. 
Must say all in all is very strange, as here I'm using SPIRV-Tools from Vulkan SDK 1.0.68:
```
spirv-val --version
SPIRV-Tools v2018.1-dev v2018.0-6-g9e19fc0
```
and spirv-val doesn't catch any issues with the generated SPIR-V with Float16 cap:
I run spirv-dis just to check has mantained Float16 and SPV_AMD_.. ext:
spirv-as test.spv.txt -o test.spv
spirv-dis test.spv -o testdis.spv.txt
spirv-val test.spv
no errors and also
spirv-opt test.spv -O -o test2.spv
optimzes spir-v correctly seeing textual form:
spirv-dis test2.spv -o test2dis.spv.txt
I attach all generated files in case helpful:
[tests.zip](https://github.com/Microsoft/DirectXShaderCompiler/files/1783779/tests.zip)

**Comment by oscarbg** [comment] 2018-03-06 07:59
I just opened an issue for glslangValidator tool as is clrealy including Float16 cap. also..

**Comment by ehsannas** [comment] 2018-03-06 20:37
The change has been merged.

The SPIRV-Tools related issue should be discussed on the SPIR-V Tools github repo. I'm closing this one.

Thanks

**Closed by ehsannas** 2018-03-06 20:37 UTC

**Comment by oscarbg** [comment] 2018-03-12 09:54
Hi @ehsannas  @antiagainst ,
just tested with latest DXC compiler builds and latest SPIRV-tools and as you say both fixed..
anyway,sorry for asking more questions :-):
what about int16?
I say because I'm testing glslang HLSL int16 support which
(https://github.com/KhronosGroup/glslang/issues/1271)
still has some issues but anyway even I was able with some hacks to somewhat obtain SPIR-V I see it has both:

>                OpCapability Int16
>                OpExtension "SPV_AMD_gpu_shader_int16"

is this OK?
I know know should probably ask SPIRV-Tools  devs but as you seem supportive and also may be of interest to you what are you outputting with min16int shaders?
    OpCapability Int16 is enough for all min16int ops HLSL supports or there are some ops that might need   OpExtension "SPV_AMD_gpu_shader_int16" support?
thanks..

**Comment by oscarbg** [comment] 2018-03-12 15:35
Hi @ehsannas @antiagainst ,
one final question for today I promise :-)
is related to mandelbrot  HLSL code, SPIRV-Cross has added support for it recently and testing a the SPIR-V generated of that shader by DirectXShaderCompiler, it failed to translate to HLSL for reasons unrelated to min16float.. 
@HansKristian-ARM says (issue here: https://github.com/KhronosGroup/SPIRV-Cross/issues/484):
> You cannot place bools in buffers in SPIR-V, so this is invalid SPIR-V in any case. There was no checking before, so it just assumed 4 bytes. If glslang emits code like that, it's a bug in glslang.
must say that even if that is not supported on SPIR-V please allow this non-standard behaviour on DXC..

thanks..

**Comment by antiagainst** [comment] 2018-03-13 19:41
@oscarbg:

> OpCapability Int16 is enough for all min16int ops HLSL supports or there are some ops that might need OpExtension "SPV_AMD_gpu_shader_int16" support?

According to [SPV_AMD_gpu_shader_int16](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/AMD/SPV_AMD_gpu_shader_int16.html), it only adds supports for `Frexp` and `FrexpStruct` in GLSL.std.450. We are not using `Frexp` but we are using `FrexpStruct` to translate [`frexp()`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509604(v=vs.85).aspx). But I'm not sure how you can use 16-bit with `frexp()` though. I don't think the frontend support that yet.

Regarding bools in buffers, it's a bug that also got reported as #1136. We'll fix that. We'd appreciate if you can file separate issues for different bugs. It's better for tracking/searching and more noticeable.
