### ISSUE TITLE
[SPIR-V] HLSL to SPIRV explicit location error

### ISSUE THREAD

**Issue by Eichenherz** [microsoft/DirectXShaderCompiler#4022] opened 2021-10-20 16:58 UTC
I have to following shader:
```hlsl
[[vk::push_constant]]
struct {
	float2 scale;
	float2 translate;
} pushBlock;

struct imgui_vertex
{
	float x, y;
	float u, v;
	uint rgba8Unorm;
};

[[vk::binding( 0 )]] StructuredBuffer<imgui_vertex> uiVtxBuff;
[[vk::binding( 1 )]] Texture2D fontAtals;
[[vk::binding( 2 )]] SamplerState fontSampler;


struct vs_out
{
	[[vk::location( 0 )]] float4 col : COLOR0;
	[[vk::location( 1 )]] float2 uv : TEXCOORD0;
};

[ shader( "vertex" ) ]
vs_out VsMain( 
	in uint vtxID : SV_VertexID,
	out float4 pos : SV_Position
){
	imgui_vertex uiVtxAttrs = uiVtxBuff[ vtxID ];
	
	pos = float4( float2( uiVtxAttrs.x, uiVtxAttrs.y ) * pushBlock.scale + pushBlock.translate, 0.0f, 1.0f );
	vs_out output;
	output.col = unpack_u8u32(  uiVtxAttrs.rgba8Unorm ).xyzw;
	output.uv = float2( uiVtxAttrs.u, uiVtxAttrs.v );
	
	return output;
}

[ shader( "pixel" ) ]
float4 PsMain( vs_out input ) : SV_Target
{
	return input.col * fontAtals.Sample( fontSampler, input.uv );
}
```

I'm compiling this ( with DXC ofc ) with the following options:
"-spirv",
"-fspv-target-env=vulkan1.2",
"-T",
"lib_6_6"
but this gives me back the error: "partial explicit stage output location assignment via vk::location(X) unsupported".
Even like this:
```hlsl
[ shader( "vertex" ) ]
void VsMain( 
	in uint vtxID : SV_VertexID,
	out float4 pos : SV_Position,
	[[vk::location( 0 )]] 
	out float4 col : COLOR0,
	[[vk::location( 1 )]] 
	out float2 uv : TEXCOORD0
){
	imgui_vertex uiVtxAttrs = uiVtxBuff[ vtxID ];
	
	pos = float4( float2( uiVtxAttrs.x, uiVtxAttrs.y ) * pushBlock.scale + pushBlock.translate, 0.0f, 1.0f );
	col = unpack_u8u32(  uiVtxAttrs.rgba8Unorm ).xyzw;
	uv = float2( uiVtxAttrs.u, uiVtxAttrs.v );
}

[ shader( "pixel" ) ]
float4 PsMain( 
	[[vk::location( 0 )]] 
	in float4 col : COLOR0,
	[[vk::location( 1 )]] 
	in float2 uv : TEXCOORD0
) : SV_Target
{
	return col * fontAtals.Sample( fontSampler, uv );
}
```
Without explicit location I get errors at VkPipeline creation about shader inputs/outputs not being written or read.

**Comment by jaebaek** [comment] 2021-10-21 17:33
@Eichenherz Thank you for reporting this issue. We will take a look!

**Comment by sudonatalie** [comment] 2023-08-23 14:08
Sorry that this went unanswered for so long but the issue is that there is no Location assignment on the function return. See example in the docs here: [Explicit Location number assignment](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst#explicit-location-number-assignment). It would be nice if the error message was improved to say which semantics were missing an explicit location number assignment but unfortunately the way this is currently implemented means that wouldn't be a trivial change, and I don't think it's a high priority to refactor, so I'm going to close this issue.

**Closed by sudonatalie** 2023-08-23 14:08 UTC
Labels: spirv
