### ISSUE TITLE
malloc() : corrupted top size.

### ISSUE THREAD

**Issue by Sameeranjoshi** [microsoft/DirectXShaderCompiler#3808] opened 2021-06-01 06:54 UTC
Hello, 
I am trying to add a small snippet in the compiler for new feature.
With the command 
`../../build/bin/dxc -E main -T ps_6_0 -Fo myshader.bin -Zi -Fd myshader.pdb -D MYDEFINE=1 test.hlsl`

I see following error:
```
malloc(): corrupted top size
```
The error doesn't seem to come from the code snippets I added, it somewhat related to the malloc allocation which fails due to less memory allocated to [links](https://www.google.co.in/search?q=malloc%28%29%3A+corrupted+top+size&sxsrf=ALeKk0157wWoctgHqKEc3Pp9S1u27HzQww%3A1622529416620&source=hp&ei=iNW1YIiTI_SCrtoPs_qNoAM&iflsig=AINFCbYAAAAAYLXjmNJzg3uPe3XxiOduKtm3PX0-D6AL&oq=malloc%28%29%3A+corrupted+top+size&gs_lcp=Cgdnd3Mtd2l6EAMyAggAMgIIADICCAAyAggAMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeUMMBWMMBYOkDaABwAHgAgAHzAYgB8wGSAQMyLTGYAQCgAQKgAQGqAQdnd3Mtd2l6&sclient=gws-wiz&ved=0ahUKEwiI94yM6fXwAhV0gUsFHTN9AzQQ4dUDCAc&uact=5)

Can someone provide the support for the issue, as it's an Undefined behavior and can literally cause anything?
Thanks.

**Comment by Sameeranjoshi** [comment] 2021-06-01 06:57
Ohh and I forgot to mention that I am on linux and not on windows.

**Comment by jaebaek** [comment] 2021-06-02 07:20
If you followed [this instruction](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/DxcOnUnix.rst#building-dxc) to build the Linux version of DXC, it currently does not support DXIL backend. I have not tried building DXIL backend on Linux but I speculate we have to update the cmake files.

**Comment by Sameeranjoshi** [comment] 2021-06-02 12:37
Yes I followed the same I can build on linux successfully and can test as well.

**Comment by jaebaek** [comment] 2021-06-07 10:18
If you do not use `-Fo myshader.bin -Zi -Fd myshader.pdb`, does it work?
like `../../build/bin/dxc -E main -T ps_6_0 -D MYDEFINE=1 test.hlsl`

**Comment by Sameeranjoshi** [comment] 2021-06-07 11:39
Unfortunately again

**Comment by Sameeranjoshi** [comment] 2021-06-07 11:39
the same issue.

**Comment by pow2clk** [comment] 2021-06-14 19:38
Hi @sameeranjoshi!

I can confirm that the linux build will generate DXIL by default. It does get some rudimentary per-PR testing.  Can you provide the offending shader? Am I correct that what is failing is a modified version of DXC? Does this not occur with the code in ToT now? If that's the case, then I fear the bug is yours and there's nothing we can do

**Comment by pow2clk** [comment] 2021-06-14 19:48
Also worth noting, when it comes to memory corruption, it's very common for the flaw to be noticed far from where it was introduced, so even though the error you're seeing doesn't occur while the code you added is running, that doesn't mean it's not the cause of the corruption.

If you can provide a way to reproduce this with the code that is in the repo, we'll take a look at it, otherwise, we can't investigate this and it should be concluded that the problem is in the added code

**Comment by pow2clk** [comment] 2021-06-23 19:05
Not having a repro with the code committed to github, I'm closing this. If you find such a repro, feel free to reopen.

**Closed by pow2clk** 2021-06-23 19:05 UTC
Labels: linux
