### ISSUE TITLE
Incorrect code gen when mul intrinsic is applied on bool vector types

### ISSUE THREAD

**Issue by vcsharma** [microsoft/DirectXShaderCompiler#2467] opened 2019-09-19 00:19 UTC
This was originally part of the bug #2464, but now filing it as a separate issue as the root cause for this appears to be different from other issues related to mul intrinsics. It tries to cast i1 to double and applies dot operation..

```
// %dxc -T vs_6_0 -E main -DELEM_TY1=bool2 -DELEM_TY2=bool2 -DRET_TY=bool %s

cbuffer CB {
  ELEM_TY1 e1;
  ELEM_TY2 e2;
};

RET_TY main(): OUT
{
	return mul(e1, e2);
}
```

```
define void @main() {
  %1 = call %dx.types.Handle @dx.op.createHandle(i32 57, i8 2, i32 0, i32 0, i1 false)  ; CreateHandle(resourceClass,rangeId,index,nonUniformIndex)
  %2 = call %dx.types.CBufRet.i32 @dx.op.cbufferLoadLegacy.i32(i32 59, %dx.types.Handle %1, i32 0)  ; CBufferLoadLegacy(handle,regIndex)
  %3 = extractvalue %dx.types.CBufRet.i32 %2, 2
  %4 = extractvalue %dx.types.CBufRet.i32 %2, 3
  %5 = icmp ne i32 %3, 0
  %6 = icmp ne i32 %4, 0
  %7 = uitofp i1 %5 to double
  %8 = uitofp i1 %6 to double
  %9 = extractvalue %dx.types.CBufRet.i32 %2, 0
  %10 = extractvalue %dx.types.CBufRet.i32 %2, 1
  %11 = icmp ne i32 %9, 0
  %12 = icmp ne i32 %10, 0
  %13 = uitofp i1 %11 to double
  %14 = uitofp i1 %12 to double
  %15 = call double @dx.op.dot2.f64(i32 54, double %13, double %14, double %7, double %8)  ; Dot2(ax,ay,bx,by)
  %16 = fcmp fast une double %15, 0.000000e+00
  %17 = zext i1 %16 to i32
  call void @dx.op.storeOutput.i32(i32 5, i32 0, i32 0, i8 0, i32 %17)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void
}
```

**Comment by vcsharma** [comment] 2019-09-27 02:52
This is likely related to #2432.

**Comment by llvm-beanz** [comment] 2024-06-13 15:38
This isn't actually related to #2432. #2432 is how `literal` is resolved, which we addressed in HLSL 202x.

This bug is caused by SeamHLSL not scoring boolean conversions, so it returns them as "Exact match" instead of as a conversion. That results in the first overload in the overload set being visited getting marked as an "exact match", then we short-circuit building out a full overload set. In this case because `mul` takes a `numeric` argument, the only overload put in the overload set is `float`. The same issue occurs in #6633.

**Comment by damyanp** [comment] 2024-06-18 17:09
We're not planning on addressing this in DXC, and this issue is not present in Clang.

**Closed by damyanp** 2024-06-18 17:09 UTC
Labels: bug
