### ISSUE TITLE
[SPIR-V] interface variables not listed in OpEntryPoint

### ISSUE THREAD

**Issue by a3YsM5jc** [microsoft/DirectXShaderCompiler#5205] opened 2023-05-11 15:09 UTC
The HLSL version of GL_EXT_spirv_intrinsics can be used to specify a storage class to declare an interface variable, but the compiler does not add the variable to the list of variables in OpEntryPoint.

Example:
Normal raygen shader that works fine:
`OpEntryPoint RayGenerationNV %raygen "raygen" %3 %4 %outputImage %topLevelAS %payload`

Same raygen shader, but with intrinsics from SPV_NV_shader_invocation_reorder:
`OpEntryPoint RayGenerationNV %raygen "raygen" %3 %4 %outputImage %topLevelAS`

I wrote a raygen shader which uses intrinsics for SPV_NV_shader_invocation_reorder, but DXC shows the following error:
> fatal error: generated SPIR-V is invalid: Interface variable id <11> is used by entry point 'raygen' id <2>, but is not listed as an interface
>   %payload = OpVariable %_ptr_RayPayloadNV_Payload RayPayloadNV
> 
> note: please file a bug report on https://github.com/Microsoft/DirectXShaderCompiler/issues with source code if possible

Could you please add a new function to the spirv_intrinsics extension to mark/list interface variables?

Attaching an HLSL shader which can be used to reproduce the issue.
Command line: `dxc -T lib_6_6 -spirv  -fspv-target-env=universal1.5 raygen.hlsl`

[raygen.zip](https://github.com/microsoft/DirectXShaderCompiler/files/11453641/raygen.zip)

**Comment by sudonatalie** [comment] 2023-08-09 15:42
This error can be addressed by moving the `payload` variable to being a global `static`, which will add it to the `OpEntryPoint`. Assigning to @s-perron for a further look though in case there are any improvements we want to consider here as part of https://github.com/microsoft/hlsl-specs/pull/59.

**Comment by s-perron** [comment] 2023-08-14 14:15
@a3YsM5jc Can you explain why you need to use all of the spirv intrinsic? I noticed you has SPIRV and DXIL specific code. When I tried the DXIL version of the HLSL with the spir-v, it seems to correctly use the [SPV_KHR_ray_tracing extension](https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_ray_tracing.asciidoc).

> This error can be addressed by moving the payload variable to being a global static

The intrinsics are small changes to the spir-v that are mean to be transparent to the rest of the compilation. For variables, the compiles does not add function scope variables to the interface variable because they are local, and not part of the interface for the shader.

For this use case, defining the variable outside of the function is the correct code pattern because the PayLoad storage class is defined outside of the function in SPIR-V. I would use the `groupshared` qualifier instead of `static` because it is meant to be shared between multiple invocations, and not be externally visible. That seems to be the closes to what you want.

I don't think we need to improve the spir-v intrinsics for this use case. The problem is that the spir-v are not user friendly. This will need to be part of the documentation once we make the changes.

**Closed by s-perron** 2023-08-14 14:15 UTC
Labels: spirv
