### ISSUE TITLE
[HLSL 2021] function template partial specialization is not allowed when declaring two functions with the same name

### ISSUE THREAD

**Issue by MrArnal** [microsoft/DirectXShaderCompiler#4263] opened 2022-02-15 14:03 UTC
The following snippet is failing with "function template partial specialization is not allowed"

    template <typename T>
    struct MyTex2D
    {
        uint heapId;

        template <typename Arg0>
        T Load(Arg0 arg0)
        {
            return Get().Load(arg0);
        }

        template <typename Arg0, typename Arg1>
        T Load(Arg0 arg0, Arg1 arg1)
        {
            return Get().Load(arg0, arg1);
        }

        Texture2D<T> Get()
        {
            return (Texture2D<T>)ResourceDescriptorHeap[heapId];
        }
    };

    cbuffer constantBuffer : register(b0)
    {
        MyTex2D<float4> tex;
    };

    float4 main() : SV_Target
    {
        float4 output = tex.Load(int3(0, 0, 0));
        return output;
    }

**Comment by llvm-beanz** [comment] 2022-03-09 17:42
I have an understanding of the problem here but I haven't yet come up with a solution.

The problem is in how HLSL handles default templates. C++ template rules require an empty parameter list for certain uses of templates with default options (i.e. Texture2D<> instead of HLSL's Texture2D).

The way this is implemented in DXC is all identifiers get routed through template lookup paths. This works... mostly. The problem here is that the first `Load` method gets processed and marked as a template identifier (so far so good), then the second `Load` gets marked as a specialization of the first one (because it gets looked up when it shouldn't).

The correct solution to this is going to require reworking how DXC supports defaulted templates. I'm working on figuring that out, but it may take me a while to sort.

**Closed** 2022-04-13 03:09 UTC
Labels: bug, hlsl2021
