### ISSUE TITLE
[SPIR-V] Ability to control OpEntryPoint export name

### ISSUE THREAD

**Issue by Themaister** [microsoft/DirectXShaderCompiler#4356] opened 2022-03-27 12:49 UTC
When using -E foo, it seems like the entry point name is also forced to foo, and I can't find any option to export all entry points as just "main" (target engine in question does not use multiple entry point SPIR-V).

If it does not exist, it would be good to have an option to control the output entry point name, since I wouldn't have to reflect out the entry point name from SPIR-V to be able to use it in a pipeline.

**Comment by jaebaek** [comment] 2022-03-28 21:07
Let me clarify your question. When we have an entry function `foo`, do you want to compile it with `-E foo` but set its Name operand of [OpEntryPoint](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpEntryPoint) as "main"?

**Comment by Themaister** [comment] 2022-03-29 11:04
Correct. Ideally, it would be possible to set OpEntryPoint name separate from the HLSL entry point -E. So e.g.

`dxc -spirv -Fo foo.spv foo.hlsl -E foo -fspv-entry-point main`.

**Comment by sudonatalie** [comment] 2022-03-30 17:49
Thanks for the suggestion! Closing this as a duplicate of #2972 but we'll take this opportunity to re-triage it for consideration.

**Closed by sudonatalie** 2022-03-30 17:49 UTC
Labels: spirv
