### ISSUE TITLE
DXC++ issue, last argument assumed as input file name

### ISSUE THREAD

**Issue by Nielsbishere** [microsoft/DirectXShaderCompiler#3173] opened 2020-10-01 12:49 UTC
In the latest build I pulled from appveyor (and a few before), DXC assumes the last argument passed is the input file name.
If you don't have an input file, it used to default to the file name "hlsl.hlsl", which could've been used as a hint and checked for compile error parsing.
Now it takes the last argument, regardless of if that argument is an input name or not. (So if your argument is /O3 it will use that in the error message).
I manually fixed it by just always pushing hlsl.hlsl in the last argument when I compile, but I still view this as a bug.

**Comment by bob80905** [comment] 2021-12-16 23:14
Hello, I have begun looking at this issue.
Would you be able to provide any more information on what arguments you gave to produce this behavior, or if this behavior is still occurring on the latest version?

**Comment by Nielsbishere** [comment] 2021-12-20 10:33
args:
`{ L"/O3", L"/Zpc", L"/Qstrip_debug", L"/Qstrip_priv", L"/remove-unused-functions" }`

shader:
```hlsl
Texture2D<float4> rgba : register(t0);
RWTexture2D<float> transparency : register(u0);

[numthreads(16,16,1)]
void main(int3 loc : SV_DispatchThreadID) {
  transparency[loc.xy] = ergba[loc.xy].a;          //Trigger compiler error to check
}
```

output:
```
/remove-unused-functions:7:26: error: use of undeclared identifier 'ergba'; did you mean 'rgba'?
  transparency[loc.xy] = ergba[loc.xy].a;
                         ^~~~~
                         rgba
/remove-unused-functions:2:19: note: 'rgba' declared here
Texture2D<float4> rgba : register(t0);
                  ^
```

expected (does output correctly if you force last argument to be hlsl.hlsl):
```
hlsl.hlsl:7:26: error: use of undeclared identifier 'ergba'; did you mean 'rgba'?
  transparency[loc.xy] = ergba[loc.xy].a;
                         ^~~~~
                         rgba
hlsl.hlsl:2:19: note: 'rgba' declared here
Texture2D<float4> rgba : register(t0);
                  ^
```

**Comment by bob80905** [comment] 2022-01-04 19:35
"/remove_unused_functions" isn't a valid flag for dxc, and so the parser can only assume it is the input file because no other input file was specified, and it starts with a "/". This is expected behavior.
I also tried /O3 as the final argument, and it did not treat /O3 as the input file, because /O3 is recognized as a valid flag.
I will close this bug by design.

**Closed by bob80905** 2022-01-04 19:35 UTC
