### ISSUE TITLE
[spirv] spir-v:ddx doesn't work for half3

### ISSUE THREAD

**Issue by johnson3d** [microsoft/DirectXShaderCompiler#2622] opened 2019-12-15 03:46 UTC
HLSL like this will get a spir-v error:
half3 PosVS;
half3  t1 = ddx(PosVS);

Then i change the code like this:
float3 PosVS;
half3  t1 = (half3)ddx(PosVS);

It's OK!

**Comment by ehsannas** [comment] 2019-12-15 04:37
Thanks for reporting @johnson3d

**Comment by jaebaek** [comment] 2019-12-16 22:15
Hi @johnson3d thank you for reporting this issue.
I tested the sample code you provided but I cannot reproduce this bug.
Could you please let me know githash of your DXC binary or try it with the [top of tree](https://ci.appveyor.com/project/antiagainst/directxshadercompiler/branch/master/artifacts)?

If you reproduce the bug, please let me know what command line options you used as well.

Thanks!

**Comment by jaebaek** [comment] 2020-01-17 21:20
Since there is no way to reproduce it, I close this issue for now. Please open it again if this issue still exists.

**Closed by jaebaek** 2020-01-17 21:20 UTC
Labels: spirv
